### ISSUE TITLE
Establish well defined cert dir and detect certs automatically

### ISSUE THREAD

**Issue by dhiltgen** [docker/classicswarm#1113]
To simplify standing up swarm, it would be nice if swarm had a well known dir it looked for certs in and if present, used them automatically.  This could then be volume mounted in the container to make it easier to get a swarm up and running.

I don't have a strong opinion on the exact path, but perhaps something like /etc/docker/ssl with well known filenames like ca.pem, cert.pem, and key.pem

**Comment by amitshukla** [comment]
@dhiltgen any changes to this request?

**Comment by dhiltgen** [comment]
Not at this time - I still see this as a "nice to have" as it would make it just a tad easier for people to stand up TLS protected swarm clusters.
