### ISSUE TITLE
Authorization (ACLs) support in Swarm as a first step towards multi tenancy.

### ISSUE THREAD

**Issue by doronp** [docker/classicswarm#1199]
## Overview

Swarm currently doesn't support multiple tenants or general authorization roles. It may be crucial for some users to be able to manage their docker cluster  using Swarm while being able to isolate between the different tenants and users. This means that while several tenants are using the same docker engines and other resources to run their containers they will have isolation in terms of the cluster management. (The scope of this issue is just the management. Run-time isolation in the engine level is out of scope for this issue)
## Very simple example

Suppose we want to isolate the users of different tenants.

Let there be tenant A and tenant B defined on some identity service.
Tenant A has user Alice and user Bob.
Tenant B has user Mike.
Say Alice creates a container on the Swarm cluster successfully. Call it C.
Mike now submits list containers requests - He gets empty list back.
Bob now submits list containers requests - He gets C back.

As you can see I assumed a 'policy' in which users on the same tenant can see each others containers. This does not have to be this way, those kind of rules as other fine grained ACLs showed be definable via the authorization plugin.
## Details

As Docker engine is likely to introduce [authorization support via a generic authorization plugin](https://github.com/docker/docker/issues/13697)
and as there is reason in effort & code reuse such as [uniform docker-swarm API](https://github.com/icecrime/docker-api) it may be sensible to have a similar mechanism in Swarm as it is 'one big aggregated engine'.
As Swarm does not necessarily contacts the engines in its cluster for all requests it receives (e.g. list containers) and as some of the API may behave differently in Swarm it may be necessary to have a bit different logic. However - Lots of shared abstractions remains.

This issue may encapsulate several issue for this context which are required in order to achieve the described goal amongst:
- [Docker like](https://github.com/docker/docker/blob/master/docs/extend/plugins.md) generic authorization plugin mechanism to enables multiple back-ends to implement enforcement of the authorization defined API in Swarm.
- Adding support for tenancy related data and entities depending on the chosen approach but may be similar to [Kubernetes approach](https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/admin/authentication.md)
- Having some clean way to perform authorization related operation using the generic plugin (Pre/Post operations or more powerful Swarm handler wrapper)

At this point I'd not like to present a full blown solution, but to get feedback and let the proposal evolve.

Signed-off-by: Doron Podoleanu doronp@il.ibm.com

**Comment by abronan** [comment]
Thanks for the proposal @doronp and the thorough research on issues that are on the engine side, I do think this is important and that we should allow to clearly separate objects living in the cluster based on authorizations.

We can still **emulate** this behavior on top of Swarm: you can have your own authorization mechanism, apply labels on containers and filter on those labels based on authorizations or refuse operations like removing a container which is not on that filtered list.

This is above Swarm though and we can find a way to include this by default. This is a work to do in the Engine so that Swarm uses the API for authorization that is applicable on a single docker engine as well as a cluster of docker engines.

**Comment by doronp** [comment]
@abronan . Indeed I started with a prototype based on labels and filters above Swarm then integrated it into Swarm. If it is OK with you I will clean it up and issue a pull request.
