### ISSUE TITLE
Access node by DNS

### ISSUE THREAD

**Issue by etlweather** [docker/classicswarm#1220]
Even though the documentation clearly shows to advertise an IP address:

```
$ swarm join --advertise=<node_ip:2375> token://<cluster_id>
```

I tried doing it with a fully qualified host name.

```
$ swarm join --advertise=myhost.example.com:2375 consul://consul.example.com:8500
```

As a result, the `swarm manage` process logged:

```
lookup myhost.example.com: no such host
```

I know the container running `swarm manage` can do host lookup because it's able to resolve `consul.example.com`. So it seems to really be expecting an IP address and no do host lookup on the nodes.
I think it would be nice to be able to use the host name.

**Comment by vieux** [comment]
@etlweather is `myhost.example.com` in your `/etc/hosts`, pointing to `127.0.0.1` ?

**Comment by etlweather** [comment]
@vieux - no, but it's my DNS server. It's also not localhost.

**Comment by xenoterracide** [comment]
related, same issue? I would like to be able to do `docker swarm init --advertise=myhost.example.com` then nodes would look up the host ip with dns and obey dns caching rules.
