### ISSUE TITLE
CLI command to list cluster ids

### ISSUE THREAD

**Issue by cindyc** [docker/classicswarm#1222]
The cluster_id/token is required in swarm list, manage, join commands, but there is no command to list the cluster_ids: 

```
docker run --rm swarm
Usage: swarm [OPTIONS] COMMAND [arg...]

A Docker-native clustering system

Version: 0.4.0 (d647d82)

Options:
  --debug           debug mode [$DEBUG]
  --log-level, -l "info"    Log level (options: debug, info, warn, error, fatal, panic)
  --help, -h            show help
  --version, -v         print the version

Commands:
  create, c Create a cluster
  list, l   List nodes in a cluster
  manage, m Manage a docker cluster
  join, j   join a docker cluster
  help, h   Shows a list of commands or help for one command

Run 'swarm COMMAND --help' for more information on a command.
```

So after a token is 'swarm create', it has to be copied and stored somewhere for later use. 

Also, if 'swarm create' could provide an option to define a name for a cluster, or generate a random name for a cluster, it'll be much easier to use than tokens.

**Comment by vieux** [comment]
@cindyc thanks we will keep this feature in minds

**Comment by Pensu** [comment]
+1
