### ISSUE TITLE
There should be documentation on how to remove a node from the swarm

### ISSUE THREAD

**Issue by vincentwoo** [docker/classicswarm#1341]
Per @abronan's request, opening an issue to track lack of docs on this topic. Node removal is kind of tricky, and users need to be away of ways it can fail, as well.

see #197 for reference

**Comment by vincentwoo** [comment]
@abronan, any movement on this? Would still really love some guidance on how to remove nodes. I also need to be able to say "remove this node from the pool for future containers, but keep any containers on it running i/o through the swarm manager".

**Comment by MHBauer** [comment]
This is not be relevant, but I can imagine (ab)using constraints for this. The only problem is the daemon needs to be restarted to change labels.

Make a label that marks a node as "bad", and then subject any future runs to a `not` constraint. Voila, anything that was already on it stays on it, but nothing new starts on it. Unfortunately you have to restart docker to label a deamon, so this doesn't work in theory or in practice.

**Comment by vincentwoo** [comment]
Oof, that's pretty brutal. I think there really needs to be a better user story here - running a bunch of potentially long jobs on a cluster that routinely gets reprovisioned seems like a very common use case for this stuff.

**Comment by thaJeztah** [comment]
I know there's an issue for updating daemon settings through an API in docker, which still needs more discussion, but perhaps we should have a discussion about just changing labels; this sounds like a good use case for being able to change daemon labels at runtime

**Comment by abronan** [comment]
@thaJeztah @vincentwoo after discussing about it today, we are likely to improve the whole node management scenario to allow for explicit removal of nodes, not only relying on implicit discovery from a KV store or the Hub token discovery to remove the node in case it cannot renew its TTL (so you'll be able to remove a node explicitly by issuing a `swarm remove <node-name> consul://<url-consul>` for example which explicitly removes the entry from Consul and notifies the Manager about this removal). Not sure how we will proceed for simpler discovery implementations like `nodes` because the Manager would need dedicated API endpoints.

This point confuses a lot of users as well as labeling the daemons (which cannot be updated at runtime).

Node removal is not explicit as of today, even though improving docs can help, I think the right solution is to move forward with explicit removal of nodes and document it correctly alongside the cases where a node is removed automatically because it's not healthy.

**Comment by vincentwoo** [comment]
That sounds like the Right Thing To Do. When do you think you'll have something for us to test?

**Comment by abronan** [comment]
@vincentwoo I guess we'll put up a Proposal first to see if everyone agrees on the new Node management scheme. Feel free to provide some feedbacks when the proposal/issue will be up :)

If I take the example of explicit node removal, using the kv discovery it's trivial to implement as we rely on Watch events on deletion and we remove the node entry (and associated Engine data) on the Manager. This should require some more changes for other discovery methods though.

Also an improvement would be to best-effort re-schedule/rebalance containers running on the deleted node (if stateless), @aluzzardi has something in the way for that as a first step.

**Comment by vincentwoo** [comment]
Happy to comment on the proposal when it goes up. Can you ping me here, then?

Regarding rebalancing - I'd like an option to explicitly *NOT* do that. As you suspect, it gets tricky with state.

**Comment by abronan** [comment]
@vincentwoo PTAL at #1486 and #1488

Any feedback would be greatly appreciated :smile:

**Comment by aluzzardi** [comment]
Note that #1486 doesn't handle removing a node from Swarm - it only tackles reporting.

Removal will come as another proposal. That depends on providing a new, cluster-aware nodes API (#735).

**Comment by vincentwoo** [comment]
Yeah, I read through both and neither proposals seem to address "how does one remove a node from the swarm."

The points about node management and persistence are certainly real, they just don't concern me.

**Comment by aluzzardi** [comment]
@vincentwoo Working on that :)

**Comment by amitshukla** [comment]
Node management (#1486) is tracking a complete solution. Closing this issue.

**Comment by vincentwoo** [comment]
@amitshukla everything in that PR claims that it does not cover node removal. Why did you close this issue? Can you point me at the part of the PR that is removal-related?

**Comment by abronan** [comment]
Reopening as this is still an issue. Node Management does not answer this question completely. We still need better docs.

**Comment by rolfedh** [comment]
@amitshukla Please describe the agreed-upon method for node removal then and assign this back to me.

**Comment by vincentwoo** [comment]
@amitshukla @rolfedh any progress on this? I think the priority of this issue should be escalated - it's hard for me to see how you can ship a distributed system for node management without explicit docs on how to remove nodes

**Comment by robwithhair** [comment]
How are you supposed to remove a node?  I assumed simply shutting down the node would remove it from the cluster?

**Comment by vincentwoo** [comment]
monthly checkup! @amitshukla, you still appear to not have assigned this task to the proper recipient.

**Comment by cejojohn** [comment]
urgh, this is strange, we don't have this yet? @vincentwoo you've got anything?

**Comment by vincentwoo** [comment]
Nah, I'm not even going to try to use Swarm until I see this laid out.

**Comment by npcode** [comment]
@robwithhair How to remove a node: Stop swarm-agent of the node and wait 5 mins. This way might not be proper but works.

**Comment by sheerun** [comment]
With docker 1.12 I was able to:

```sh
docker swarm leave # on worker node
docker node rm worker # on master node
```

**Comment by sheerun** [comment]
Ideally I'd be able to remove worker node directly  from master node I guess (i.e. if `docker swarm` accepted acting node, something like `docker swarm leave --as worker`).

**Comment by jeffbaier** [comment]
The swarm subcommand in the docker engine is "swarmkit" and is not the same as this swarm.

**Comment by ORESoftware** [comment]
having trouble demoting the last manager in the swarm so I can remove/delete the entire swarm

**Comment by vincentwoo** [comment]
Oh, forgot about this thread. I have no idea where the Docker people landed but our makeshift solution is to have all nodes have a "healthy" label, and remove it from nodes we wish to remove from the swarm. This will cause swarm to stop scheduling new containers on those nodes while allowing the remaining containers on those nodes to gracefully drain.

**Comment by dongluochen** [comment]
Given node management including this function is implemented in the new Docker Swarm mode, classic Swarm (this project) is unlikely to re-implement such function and extend Docker API. I think the traditional way of removing a node from Swarm is the way to go. If you want to remove a node, stopping it from heartbeating with discovery (etcd, consul, zookeeper).
