### ISSUE TITLE
Duplicate networks created when using Compose/Swarm/Networking

### ISSUE THREAD

**Issue by dnephin** [docker/classicswarm#1356]
Bringing this over from: https://github.com/docker/compose/issues/2280

From @dave-tucker:

Running through the same example in #2279 on Docker Swarm with `--x-network-driver overlay`
I have big problems after `up -d && stop && rm`

When I bring `up` my compose file again...
Instead of re-using the network (as happens in the single host use case), Compose creates a new network with the same name!

```
$ docker network ls
NETWORK ID          NAME                        DRIVER
bf7b620324cd        swl-demo0/bridge            bridge
c95de382559f        swl-demo0/none              null
6969ca97b168        swl-demo1/host              host
088077f4f115        counter                     overlay
1da7cb004cc3        swl-demo0/host              host
80b98c58f67d        swl-demo1/none              null
ad8432162868        swl-demo1/docker_gwbridge   bridge
1d63fedd167f        swl-demo1/bridge            bridge
2f0520ac885e        counter                     overlay
f8702a176805        swl-demo0/docker_gwbridge   bridge
```

I cannot do this manually with Swarm on the CLI as I get an error

```
$ docker network create -d overlay counter
Error response from daemon: 500 Internal Server Error: network with name counter already exists
```

Not sure if this is a Swarm issue, or a Compose one... but hoping we can figure it out soon!

/cc @dnephin @aanand @vieux @mavenugo

**Comment by dnephin** [comment]
I discussed this with @mrjana, and we believe this constraint should be enforced by swarm. 

I'll dig into this some more to see if I can create a test case for this.

**Comment by cpuguy83** [comment]
If the nodes are all hooked up to the same store, then it the network should be everywhere anyway. No?

**Comment by vieux** [comment]
`docker network create` against swarm only does one create on one random machine.

If you see two `counter` network, it's because two `network create` were made against swarm (by compose?)

**Comment by vieux** [comment]
I'm not sure swarm should prevent multiple global scope networks with the same name, since libnetwork allows it

**Comment by vieux** [comment]
after a quick chat with @dave-tucker I understand the issue better.

If compose against engine doesn't create multiple networks then it's something we have to fix in swarm, there should be no difference for compose.

On a side note, swarm uses overlay as default network driver when it's not specified. so `--x-network-driver overlay` shouldn't be required when talking to swarm.

**Comment by vieux** [comment]
@dnephin my guess is that it's fixed in https://github.com/docker/swarm/pull/1346 we are going to do an rc3 tomorrow.

In rc2, inspect using names is broken for global scope networks, so compose cannot find the network and creates a new one.

**Comment by vieux** [comment]
@dnephin is it fixed ?

**Comment by dnephin** [comment]
@dave-tucker reported this originally, I think he has a case to verify it.  It'll be a few days before I'm back to try it out.

**Comment by mujiburger** [comment]
That seems to have fixed it for overlay networks, but not bridge networks.  I need a user defined bridge network on each node.  Compose/swarm can't currently handle this situation (see docker/compose#3146), so I have to create them by hand and then tell compose to use them.

This is fine so long as there is a single node:
```
hostname:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
8dd2889c85a2        docker1/docker_gwbridge   bridge
d7c06a5c8af0        docker1/none              null
62eb312da8d1        docker1/host              host
b95728a2cc57        docker1/bridge            bridge
16e38fd03e3e        docker2/docker_gwbridge   bridge
190b08979c6c        docker2/bridge            bridge
93c26372be2c        docker2/none              null
15974d79db83        docker2/host              host
hostname:~/test$ docker network create --driver bridge docker1/test_testnet
ca688452c273a484426b017edc122506fec591e9856aa18116d2fb8608a91954

hostname:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
190b08979c6c        docker2/bridge            bridge
93c26372be2c        docker2/none              null
b95728a2cc57        docker1/bridge            bridge
8dd2889c85a2        docker1/docker_gwbridge   bridge
16e38fd03e3e        docker2/docker_gwbridge   bridge
15974d79db83        docker2/host              host
d7c06a5c8af0        docker1/none              null
62eb312da8d1        docker1/host              host
ca688452c273        docker1/test_testnet      bridge

hostname:~/test$ docker-compose up
Starting test_test_1
Attaching to test_test_1
test_test_1 exited with code 0

hostname:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
ca688452c273        docker1/test_testnet      bridge
16e38fd03e3e        docker2/docker_gwbridge   bridge
15974d79db83        docker2/host              host
8dd2889c85a2        docker1/docker_gwbridge   bridge
62eb312da8d1        docker1/host              host
190b08979c6c        docker2/bridge            bridge
93c26372be2c        docker2/none              null
b95728a2cc57        docker1/bridge            bridge
d7c06a5c8af0        docker1/none              null
```

as soon as I add another node things go haywire:
```
hostname:~/test$ docker network create --driver bridge docker2/test_testnet
36acb723d081211371fed9d3aa3014113e816a845d31ecfd5fb8ee0eba52798a

hostname:~/test$ docker-compose up
Creating network "test_testnet" with driver "bridge"
Starting test_test_1
ERROR: No such network: test_testnet

hostname:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
93c26372be2c        docker2/none              null
ca688452c273        docker1/test_testnet      bridge
583a5f2b9dfd        docker1/test_testnet      bridge
d7c06a5c8af0        docker1/none              null
b95728a2cc57        docker1/bridge            bridge
8dd2889c85a2        docker1/docker_gwbridge   bridge
62eb312da8d1        docker1/host              host
16e38fd03e3e        docker2/docker_gwbridge   bridge
190b08979c6c        docker2/bridge            bridge
15974d79db83        docker2/host              host
36acb723d081        docker2/test_testnet      bridge

hostname:~/test$ docker-compose up
Creating network "test_testnet" with driver "bridge"
Starting test_test_1
ERROR: No such network: test_testnet

hostname:~/test$ docker network ls
NETWORK ID          NAME                                   DRIVER
8dd2889c85a2        docker1/docker_gwbridge   bridge
16e38fd03e3e        docker2/docker_gwbridge   bridge
190b08979c6c        docker2/bridge            bridge
93c26372be2c        docker2/none              null
36acb723d081        docker2/test_testnet      bridge
62eb312da8d1        docker1/host              host
2411dec5e10c        docker1/test_testnet      bridge
15974d79db83        docker2/host              host
d7c06a5c8af0        docker1/none              null
ca688452c273        docker1/test_testnet      bridge
583a5f2b9dfd        docker1/test_testnet      bridge
b95728a2cc57        docker1/bridge            bridge
```

notice that each subsequent compose-up run creates a duplicate test_testnet on the first node and can't connect the container to it.  Attempting to create the network by hand again fails,  It seems like the compose call should also fail:

```
hostname:~/test$ docker network create --driver bridge test_testnet
Error response from daemon: 500 Internal Server Error: network with name test_testnet already exists

hostname:~/test$ docker network create --driver bridge docker1/test_testnet
Error response from daemon: 500 Internal Server Error: network with name test_testnet already exists
```

It seems like swarm shouldn't allow compose to create duplicate bridge networks on a host anymore than it should allow creation of duplicate overlay networks.

**Comment by mujiburger** [comment]
After a few hours of digging into the compose and swarm code, I understand more of the complexity of the problem.  The reason duplicates fail when called with `docker network create` is that request has `CheckDuplicate:true`  There isn't even a way to set that flag in the docker-py library used by compose.  It wouldn't really fix the problem if there were.  Setting it by hand results in a `500 Internal Server Error: network with name test_testnet already exists` which is a fatal error on the compose side that stops execution before services have even been created.  That actually might be a little bit better behavior than creating duplicate networks, but it would probably be best if the python client would allowed compose to set the request option instead of having swarm default to something different than the engine api.

Until there is a new network driver, a global scope bridge of some kind, this seems out of reach.

**Comment by schmunk42** [comment]
Ran into the same issue, multiple networks with the same name, but different IDs were created (with swarm 1.2.5 and engine 1.12.3).

I can inspect the network(s) by ID, but not by its name.

**Comment by schmunk42** [comment]
I dug a bit on this one...

For our current swarm, we ended up in creating a [custom green-blue redeployment script](https://github.com/dmstr/docker-roj/blob/2b1bb4d358188683a6cd34a4dfd0d1cd1d75d593/data/example/bin/roj-redeploy.sh), which handles network errors and does some cleanup. (Currently, this has to follow strict naming conventions to work). But you should be able to run the script against any stack without fixed port mappings for debugging.

This is an [example output](https://gist.github.com/schmunk42/0df6caa20c504ce28e2bf7086f0b5586) of the script handling network errors during redeployments.

From our observations the problems seem related to an out-of-sync state for the networks between the swarm nodes and the service discovery (consul in our case). It does (mostly) not take more than 60 seconds for the retries to succeed, which is the heartbeat of the swarm.

Duplicated networks with the same name were created multiple times during our tests.

**Comment by mklinke** [comment]
We have also managed to create two networks with the same name and different ID in a swarm. The deployment is automated and may have performed a retry. However, I'd expect the swarm to prevent such scenarios. We're just using the regular `docker stack deploy` and `docker stack rm` commands. The default network that gets created is usually removed with `docker stack rm`, but apparently there may be cases when this is not sufficient. Or maybe repeated calls to `docker stack deploy` are the problem, as we are retrying the deploy command in case of failures.
