### ISSUE TITLE
Some feedback from the Getting Started experience with docker swarm

### ISSUE THREAD

**Issue by danehammer** [docker/classicswarm#1404]
With some encouragement on Twitter from @aluzzardi and @abronan (I am @devops_hobo on Twitter, btw), I just wanted to share what I thought as I set myself up a swarm on some ARM processors. In fact now, it's 2 old laptops running ubuntu, a Raspberry Pi, and an [ODROID C1](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G141578608433).

Overall, the doc was pretty solid. I don't have a lot of networking knowledge, so I struggle to even ask the right questions when it comes to things like "can X talk to Y on port Z?" Especially when I start playing with a docker-machine built VM in VirtualBox on my Mac, trying to talk to these other machines on my home network.

So because I hoped to manage things from the boot2docker VM on my Mac, I started there, but it's hard to meld the two docs, the "Getting Started" style doc that uses Virtual Box (I've seen this style for swarm and for docker networking), and then the "real" use when you do more of the stuff by hand. I wasn't able to figure out the idea of that boot2docker VM managing the swarm, so I eventually got it working with one of the laptops being in the swarm, and then also managing the swarm. It's just difficult for me to translate the networking pieces (IP addresses, ports, port mapping from VM to docker container, etc).

I did have a strange issue that kept hanging me up, and I don't know if this is due to the `hypriot/rpi-swarm` or `armhf/swarm` images I'm running, or the `swarm` image itself, where if I didn't start the agents before the master, nothing would show up in `docker -H tcp://<master_ip>:2376 info`. Once I killed a master container and restarted it, things all worked.

One very specific comment on the Getting Started doc, I found the `<manager_port>` use jarring, because I couldn't figure out what I was supposed to use for it. I ended up doing 2376, but it was more due to trial and error than following the doc. And I kept misunderstanding what was used for what, so the first attempt at running a swarm agent I did `swarm join --addr=<manager_ip>:<manager_port>` because, well, I was telling it to _join_ a swarm, that verbiage made sense to me. So just clarifying what the meaning of `node_ip`, `manager_ip`, and `manager_port` in that doc might help. Oh, that doc being: http://docs.docker.com/swarm/install-manual/

Thanks for the help on Twitter! Now I'm off to set up an overlay network.

**Comment by aluzzardi** [comment]
Thanks for the feedback - this is very helpful!

We'll be going through some docs overhaul in the future - this will definitely help.

/cc @docker/swarm-maintainers @bfirsh

**Comment by thaJeztah** [comment]
ping @moxiegirl probably one for on your list as well

**Comment by moxiegirl** [comment]
@danehammer Thank you for the feedback.  We really appreciate the time it takes to provide such detail.  In particular, I think it is important to reflect that not everyone coming to Swarm is a networking export.  Your patten of starting with the "local virtualbox" and moving to the more "manual" was particularly interesting.  We expect that a significant number of users want to work this patten --- so we are planning on updating the Swarm documentation significantly in this cycle.   We'll be sure to include hone both guides in our revision.  

@mgoelzer You'll find this interesting as well given our meeting last week. @nigelpoulton fuel for the work in January.

**Comment by amitshukla** [comment]
@moxiegirl do you think you have incorporated this into the doc plan and we can close this issue?

**Comment by moxiegirl** [comment]
@amitshukla I think we do.
