### ISSUE TITLE
Docker pull from swarm manager dont work with private repositories

### ISSUE THREAD

**Issue by pksorensen** [docker/classicswarm#1484]
I have a swarm cluster setup:

```
pksorensen@swarm-master-1:~$ docker info
Containers: 3
Images: 4
Role: replica
Primary: 10.0.0.4:2375
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 swarm-node-0: 192.168.0.4:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.528 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-37-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 swarm-node-1: 192.168.0.5:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.528 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-37-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 swarm-node-2: 192.168.0.6:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.528 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-37-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
CPUs: 6
Total Memory: 10.58 GiB
Name: 7349355417e0
```

if i connect to one of the nodes

```
pksorensen@swarm-node-0:~$ docker info
Containers: 1
Images: 29
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-37-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.36 GiB
Name: swarm-node-0
ID: UHAG:UYDD:65H4:CGOG:27GX:R2IH:NDOO:7KZ3:626B:7BDE:UMMG:WXIR
Username: pksorensen
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

it is seen that it has been logged in. and i can also pull from privte registry

```
 docker pull ascend/tiling
Using default tag: latest
latest: Pulling from ascend/tiling
0a85502c06c9: Pull complete
0998bf8fb9e9: Pull complete
a6785352b25c: Pull complete
e9ae3c220b23: Pull complete
f0bbbe367a97: Pull complete
ee550b463bfa: Pull complete
cdcb93bdbe0f: Pull complete
b51a675802fb: Pull complete
189a77dc8ee8: Pull complete
e15bdd92c59a: Pull complete
e20ef21083d6: Pull complete
14b64f774b36: Pull complete
fa42812ac9a0: Pull complete
f22166f664b1: Pull complete
c6c09aa0bcbb: Pull complete
44a57bdcf915: Pull complete
dfb34aae2677: Pull complete
b74310f3be47: Pull complete
211cba7f3bdc: Pull complete
27f1c8cc5f3c: Pull complete
02eef01677eb: Pull complete
Digest: sha256:02a1dda664fbca329db0a613390978ec10ff29213a8eaeb1a92baaaa16f59460
Status: Downloaded newer image for ascend/tiling:latest
```

but when I do a pull from the swarm manager it do not work.

```
pksorensen@swarm-master-1:~$ docker pull ascend/tiling
Using default tag: latest
swarm-node-1: Pulling ascend/tiling:latest... : Error: image ascend/tiling:latest not found
swarm-node-0: Pulling ascend/tiling:latest... : Error: image ascend/tiling:latest not found
swarm-node-2: Pulling ascend/tiling:latest... : Error: image ascend/tiling:latest not found
Error: image ascend/tiling:latest not found

```

what is required to be able to pull images on swarm nodes from the docker swarm manager?

The issues started here : https://github.com/Azure/azure-docker-extension/issues/61#issuecomment-161211069 but I now belive that this is related to swarm and not azure docker.

**Comment by tdensmore** [comment]
You need to copy your private repo credentials to each swarm node. I know, right? I would have expected that to happen automatically too. But it doesn't. 

Try something like this (for docker running on an AWS instance as the 'ubuntu' user):

`  $PATH/docker-machine /usr/bin/scp ./dockercfg $SWARM-NODE:/home/ubuntu/.dockercfg`

**Comment by s093294** [comment]
Have you tested this? I have copied over /.docker/config.json which has the auth config. I can test also with .dockercfg but https://github.com/docker/swarm/issues/374#issuecomment-162233976 indicates that its a underlaying issue with swarm.

as my issue also indicate, i can login to a node and do a pull so it is already logged in.

**Comment by emilebosch** [comment]
@vieux any updates on this?

**Comment by amitshukla** [comment]
@emilebosch this has been fixed in Swarm 1.1.0. Can you please try with the RC?
docker pull swarm:1.1.0-rc2

**Comment by stvnwrgs** [comment]
@amitshukla i just tried rc2. Seems it does not work for me.

`docker -H "swarm-manager:23755" run -i -t --env TEST_SCRIPT=test.js stvnwrgs/private`
`Error response from daemon: Error: image stvnwrgs/private`

I am able to pull the image from the servers (manager and node) directly.

`docker -H swarm-manager info`

```
Containers: 3
Images: 3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 c-1-node-1.c.x.internal: 10.240.0.4:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.056 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.0-coreos-r2, operatingsystem=CoreOS 935.0.0, storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-01-30T18:05:12Z
 c-1-node-2.c.x.internal: 10.240.0.6:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.056 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.0-coreos-r2, operatingsystem=CoreOS 935.0.0, storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-01-30T18:04:16Z
 c-1-node-3.c.x.internal: 10.240.0.5:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 2.056 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.4.0-coreos-r2, operatingsystem=CoreOS 935.0.0, storagedriver=overlay
  └ Error: (none)
  └ UpdatedAt: 2016-01-30T18:05:10Z
CPUs: 6
Total Memory: 6.168 GiB
Name: 62997dc909b1
```

`docker -H swarm-manager version`

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   5cb6f21
 Built:        Thu Jan 21 22:34:44 UTC 2016
 OS/Arch:      linux/amd64
```

`docker info` on manager

```
docker info
Containers: 1
Images: 8
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-coreos-r2
Operating System: CoreOS 935.0.0
CPUs: 1
Total Memory: 997.4 MiB
Name: c-1-manager.c.x.internal
ID: RVG6:L5GY:3WZT:WG6Y:RL7B:OC5P:6XAG:RO7X:UHUI:LXS7:6NM2:HEWH
Username: stvnwrgs
Registry: https://index.docker.io/v1/
```


Am i missing something?

**Comment by vieux** [comment]
@stvnwrgs the credentials for the hub are stored locally, next to the client, not the daemon.
It looks like you have the credentials on `swarm-node-0` but not on `swarm-master`

can you do a `docker login` from the `swarm-master` machine ? so it will save the credentials on this machine as well ?

**Comment by amitshukla** [comment]
Plus, detail on private registry authentication in the 1.10 release is here: https://github.com/docker/swarm/blob/master/docs/swarm-api.md#registry-authentication

**Comment by michaelzangerle** [comment]
Any updates on this issue? I have basically the same setup as @s093294 has (but Docker 1.10.2 and Swarm 1.1.2) and I can pull from the swarm-nodes and through the swarm master when it's a public repository. I can also pull a private repository directly on the swarm-nodes but when I try to pull from a private repo through the swarm-master I get `Error: image [...] not found`.

I tried setting the `X-Registry-Auth` header in `~/.docker/config.json` as suggested by @amitshukla but it had no effect ... Do I have to set anything else besides `HttpHeaders` in the config.json? I sort of expected that I also have to define the the url like in `auths`.

**Comment by azpekt** [comment]
I`m having similar issues with AWS ECR. Is there anything for enabling passthrough auth apart from authenticating from every node in cluster?
Thanks

**Comment by pgporada** [comment]
This is a pain for my company as well. We switched out of Amazon ECS due to the lack of scheduling capabilities and didn't need every bell and whistle that Mesos or Kubernetes provides.

**Comment by jmalloc** [comment]
I can't say I understand how this works _at all_, but I can manage to pull down images from private repositories to our swarm if my `config.json` file contains an `auths` entry with an empty string key:

```json
{
    "auths": {
        "": {
            "auth": "...",
            "email": "..."
        },
    }
}
```

I still require an entry for `https://index.docker.io/v1/` when I am using a node directly.

**Comment by dyoder** [comment]
Having the same issue as @azpekt re: AWS ECR.

**Comment by vieux** [comment]
@dyoder @azpekt did you follow the guide at https://github.com/docker/swarm/blob/master/docs/swarm-api.md#registry-authentication ?

**Comment by amitshukla** [comment]
@dyoder @azpekt ping ^^

**Comment by azpekt** [comment]
will try to and update as soon, as possible

**Comment by amitshukla** [comment]
@azpekt any update?

**Comment by azpekt** [comment]
@amitshukla - yes, it works! weee!
quick script i wrote to call each time i need to deploy things in swarm
```bash
#!/bin/bash -e
#
if [ $# -lt 1 ]
    then
    echo "No options found!"
    exit 1
fi

while getopts "a:" opt
do
    case $opt in
a)  AUTH_HOST=($OPTARG)
;;
*)  echo "No reasonable options found!"
;;
esac
done

eval $(/usr/local/bin/docker-machine env --swarm $AUTH_HOST)

echo "Getting auth token for ECR from:
- $AUTH_HOST
"
AUTH_TOKEN=$(/usr/local/bin/docker-machine ssh $AUTH_HOST "/usr/local/bin/aws ecr get-login --region us-east-1" | awk '{print $6}')
AUTH_URL=$(/usr/local/bin/docker-machine ssh $AUTH_HOST "/usr/local/bin/aws ecr get-login --region us-east-1" | awk '{print $9}')

echo "amending local config.json for docker to pick up auth..."

cat /root/.docker/config.json | jq ".auths[\"$AUTH_URL\"].auth = \"$AUTH_TOKEN\"" > /root/.docker/tmp.config.json && mv /root/.docker/tmp.config.json /root/.docker/config.json

exit 0
```

**Comment by JoeDoyle23** [comment]
I just ran into the ECR issue as well. It looks like the answer is not to use `aws ecr get-login` but `aws ecr get-authorization-token`! From there you get JSON with the authorizationToken which can be parsed out and should be able to be sent in the X-Registry-Auth header to Swarm.

**Comment by schmunk42** [comment]
I had this issue with an upgraded swarm; all nodes running on `1.11.0` and `swarm-1.2.1-rc1`.
I was unable to pull images, despite the fact I had pulled images from our private repo before on this swarm.

It started working again after I created a new `master` with `1.10.3` and `swarm-1.2.0`.
And even more strange, after that - now I can also pull with the master `1.11.0` which was broken.

Could this be an issue with API version mismatches? How does swarm proxy a request, considering the API version, does it proxy calls in the same version?

From the case mentioned above:

 - docker 1.10.3 (API 1.22)
 - **docker 1.11.0 (API 1.23)**
 - swarm 1.1.3 (API 1.22)
 - swarm 1.2.0 (API 1.22)

If I have a swarm manager (1.2.0) running on a node with 1.11.0 and my other nodes are also 1.11.0 - does the manager communicate with its nodes in `1.22` or `1.23`?

**Comment by OferE** [comment]
@JoeDoyle23  - I followed your advice and i still can't do it - can u please explain the process? what do u mean by "parse out"?

Thanks!

**Comment by holycheater** [comment]
It works for me if I do as @jmalloc suggests by adding empty auth host to config.json

Also, docker login does not work. Looks like it does not pass a host to use.

```
Error response from daemon: Get https:///v1/users/: http: no Host in request URL
```

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.0
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   a6c1f14
 Built:        Wed Apr 13 05:58:31 UTC 2016
 OS/Arch:      linux/amd64
```

**Comment by datacarl** [comment]
All I had to do was point my client to the swarm master and then `docker login https://index.docker.io/v1/`. 

docker -v `Docker version 1.11.1, build 5604cbe`
swarm -v `swarm version 1.2.0 (a6c1f14)`

**Comment by datacarl** [comment]
Eh.. scratch that. It only works with compose. I.e. `docker-compose up` can pull the image, but `docker run <image>` fails with `docker: Error response from daemon: Error: image <image> not found.` 😕

I feel like I'm missing something (apart from the images).

**Comment by wouterla** [comment]
I've had the same issue.

I've run with both swarm 1.2.0 and 1.2.1, but I suspect this only started with docker going to 1.11.1.

Tried the above advice, both adding the header in config.json and the empty entry in auths section.

I've worked around this for now by letting my ansible scripts pull directly on each of my swarm nodes. But this is unelegant and wasteful.

**Comment by robvelor** [comment]
Experiencing the same issue, it started happening on swarm `1.2.1` .  This is from a client running `1.10.3` pointing to machines in a swarm running `1.11.1`.  Image pulls from private registries works as expected with swarm `1.2.0` with the same setup.

**Comment by dnorth98** [comment]
Having the same problem and just spent a bunch of time looking into it.  Running docker 1.11.1 and swarm 1.2.2 all setup according to https://docs.docker.com/swarm/install-manual/

I've set the header (using the small script to b64 encode the username password) in the json

```
 "HttpHeaders": {
    		"X-Registry-Auth": "MYTOKEN"
	}
```

I've been looking at packet traces in tcpdump and what I see is:

On the swarm manager, I run:

`docker -H 127.0.0.1:4000 pull signiant/generator-microservice:master-8`

Where signiant/generator...is my private repo on dockerhub and my swarm manager is running on port 4000.

Running tcpdump on the master and looking for everything on port 4000 over loopback, these 2 'bits' stick out:

case 1 - token header does look like it's set for a GET on the info call.
```
..<L..<KGET /v1.23/info HTTP/1.1^M
Host: 127.0.0.1:4000^M
User-Agent: Docker-Client/1.11.1 (linux)^M
X-Registry-Auth: MYTOKEN^M
Accept-Encoding: gzip^M
```

However, further down, I see this:

```
.<O..<NPOST /v1.23/images/create?fromImage=signiant%2Fgenerator-microservice%3Amaster-8 HTTP/1.1^M
Host: 127.0.0.1:4000^M
User-Agent: Docker-Client/1.11.1 (linux)^M
Content-Length: 0^M
Content-Type: text/plain^M
X-Registry-Auth: e30=^M
Accept-Encoding: gzip^M
```

I've not done a replacement here..it's literally always e30= for the header every time.

Now, I did a tcpdump on one of the swarm nodes to see what it is getting and it looks like this:

```
..6T.+Z!POST /v1.23/images/create?fromImage=signiant%2Fgenerator-microservice&tag=master-8 HTTP/1.1^M
Host: 10.0.9.36:4243^M
User-Agent: Go-http-client/1.1^M
Content-Length: 0^M
Content-Type: text/plain^M
X-Registry-Auth: ^M
Accept-Encoding: gzip^M
```

So no header at all - not even the e30.

It certainly seems like the header is being read on the client ok but not being passed all the way through.

**Comment by jstoja** [comment]
I'm having the exact same issue.
Each node, when logged in on my registry, can pull the image. However, the swarm cannot.
I tried setting up the token too and it's not working.

The lead of @dnorth98 seems to be promising.

**Comment by hekaldama** [comment]
@vieux I am very interested in this as well. Please feel free to point at code so we can collaborate with PRs and such. Thanks!

**Comment by hekaldama** [comment]
Pulling the latest swarm image fixed this for me. On each of the managers in my HA cluster I did:
```
docker pull swarm
docker stop swarm_manager && docker rm swarm_manager
docker run --name swarm_manager \
  -d -p 4000:4000 swarm manage \
  -H :4000 --replication \
  --advertise <IP>:4000 consul://<CONSUL_HOST>:8500/<NAMESPACE>
```

I did this in a rolling fashion and all workers reconnected just fine.

**Comment by jmkgreen** [comment]
We've just done this with Docker 1.11.2 and Swarm 1.2.3 pulling from an authenticating private registry and watched as each host downloaded our updated container image just fine.

**Comment by coryleeio** [comment]
I was having the same problem with amazon ECR, using Docker 1.11.2 and swarm 1.2.3 worked for me as well.

**Comment by bgokden** [comment]
I just had the same problem with docker swarm mode cluster on aws

**Comment by sleepyfox** [comment]
Same problem with a Docker Swarm created from the "Swarm for AWS" CloudFormation template. I can pull, run and create services from public images without issue but private images stored on ECR give me a `docker: unauthorized: authentication required` error.

**Comment by psoares** [comment]
Same problem for me, using the Swarm for AWS cloudformation template. More specifically the Community Edition Edge version...

**Comment by kencochrane** [comment]
Related issue: https://github.com/docker/for-aws/issues/5#issuecomment-303192975

**Comment by destebanm** [comment]
Hey!

Swarm 1.2.6
Docker 17.05.0-ce

Trying to run containers with images in ECR.
If i do in manager node
`docker -H:4000 run -d xxxxxx.dkr.ecr.us-west-2.amazonaws.com/xxx/xxxx:1.1
`
I get _docker: Error response from daemon: unauthorized: authentication required._

So I have tried, following this instructions https://docs.docker.com/swarm/swarm-api/#authenticate-using-username-and-password, to write this in ~/.docker/config.json

"HttpHeaders": {
    "X-Registry-Auth": "HEADER string calculated"
}

But now, when I run 
`docker -H:4000 run -d xxxxxx.dkr.ecr.us-west-2.amazonaws.com/xxx/xxxx:1.1
`
I get 
WARNING: Error loading config file:/root/.docker/config.json - json: cannot unmarshal string into Go value of type configfile.ConfigFile

Has someone been able to get working swarm manager with ECR?

Thanks!

**Comment by jmcdonagh** [comment]
I don't know that this bug is still valid, I got ECR auth working by passing "--with-registry-auth" to the docker service create command (after eval $(aws ecr get-login --no-include-email))

**Comment by yuklia** [comment]
@jmcdonagh yes it is still an issue. "--with-registry-auth" - is right options BUT it will work only for 12 hours (after the last deploy) if your service will down after 12 hours you'll get **status: rejected**
No such image...

**Comment by ukreddy-erwin** [comment]
No solution working from above comments..
I am using docker swarm mode.
When I am trying to create a service, then I am getting this access error.

I have logged into docker hub on all the nodes using (docker login),still same issue.
Any idea?

**Comment by justincormack** [comment]
This repo is for classic swarm not swarm mode.

**Comment by ukreddy-erwin** [comment]
Same issue with classic swarm

**Comment by etopeter** [comment]
@justincormack please consider reopening this issue. This issue was opened back in the days when there was no swarm mode (Swarm 2.0).
Original first post is referencing swarm mode on docker version [1.9.1](https://docs.docker.com/engine/release-notes/prior-releases/#191-2015-11-21) which was released at the end of 2015.

Fun fact, I'm subscribed to to this issue because I was working on swarm mode in early 2016 and was experiencing the same issue. Since I moved on to Kubernetes. I was curious to see this issue being finally closed. Unfortunately its still not fixed.

**Comment by justincormack** [comment]
@etopeter we are planning to deprecate Classic Swarm, see https://github.com/docker/roadmap/issues/86. The users have moved on, whether to Kubernetes like you, or to Swarmkit, and no one has wanted to fix it in five years, and we have to prioritize engineering effort on things that people are actively using.

**Comment by ukreddy-erwin** [comment]
what is the repo for swarm mode?I can't find it

**Comment by justincormack** [comment]
https://github.com/docker/swarmkit

**Comment by justincormack** [comment]
Yes, almost all of the issues on this repo recently are not for this code, which is why we want to deprecate it. We are fixing the docs to not point here.
