### ISSUE TITLE
Document how to profile a swarm

### ISSUE THREAD

**Issue by moxiegirl** [docker/classicswarm#1543]
Document how to profile a swarm

**Comment by aluzzardi** [comment]
@moxiegirl It can be profiled in exactly the same way as the engine, which is not documented either. We should probably come up with a common document about that.

Both engine and swarm use a "standard" for profiling (as in, no custom tooling needed - you just point a profiler to the API and that's it) so not sure if we should document that (since we'd be documenting a tool (pprof) which already has documentation) or just mention somewhere that swarm and engine support pprof profiling.

**Comment by moxiegirl** [comment]
@aluzzardi Thank you for the clarification.  @nigelpoulton will be helping on all the Swarm updates beginning in Jan.  I can't assign him but this will ping him and he can pick it up.  (You could add his user to the project and then we can assign him and track him in the board.  Your call)

**Comment by ggaurav10** [comment]
Hi,

Whentrying to profile swarm using "go tool pprof". I am getting the following error:

```
# go tool pprof http://127.0.0.1:2376/debug/pprof/trace
Fetching profile over HTTP from http://127.0.0.1:2376/debug/pprof/trace
http://127.0.0.1:2376/debug/pprof/trace: Get http://127.0.0.1:2376/debug/pprof/trace: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
failed to fetch any profiles

# go tool pprof http://127.0.0.1:2376/pprof
Fetching profile over HTTP from http://127.0.0.1:2376/pprof
http://127.0.0.1:2376/pprof: Get http://127.0.0.1:2376/pprof: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
failed to fetch any profiles
```

Below is the configuration details:
```
# /var/xxxx/packages/swarm/bin/swarm --version
swarm version 1.2.8 (HEAD)

# go version
go version go1.9 linux/amd64

Swarm running with below options:
#./bin/swarm
--debug=true
--log-level=info manage 
--cluster-driver=swarm 
--host unix:///var/xxxxx/sys/run/swarm_manager/swarm_manager.sock 
--engine-failure-retry 10 
--host=0.0.0.0:2376 
--strategy=spread 
--filter=health 
--filter=port 
--filter=dependency 
--filter=affinity 
--filter=constraint 
--replication=false 
--replication-ttl=30s 
--advertise=xx.xx.xx.xx:2376 
--heartbeat=20s 
--api-enable-cors=false
--cluster-opt=swarm.overcommit=0.5 
--tls=true 
--tlscacert=/var/xxxxx/jobs/swarm_manager/config/docker.cacert 
--tlscert=/var/xxxxx/jobs/swarm_manager/config/docker.cert 
--tlskey=/var/xxxxx/jobs/swarm_manager/config/docker.key 
--tlsverify=true nodes://yy.yy.yy.yy:4243

```
Swarm is running with "debug" enabled. Is there anything that I am missing here?
