### ISSUE TITLE
Update the documentation with changes from the README files

### ISSUE THREAD

**Issue by moxiegirl** [docker/classicswarm#1548]
Months ago we peeled off the README material into the `docs` directory but left the README source behind.  Contributors continued updating the README.  This is the second of a two-part work cycle.

Part 1 is #1546 where I remove the README's to prevent further updates.  I'll point to places to read _and_ to update the docs.

Part 2 is this where I compare the last user updated README against the docs to make sure I don't leave any important information from the README out of the docs.

**Comment by rolfedh** [comment]
@moxiegirl Please reassign this task.
