### ISSUE TITLE
swarm  docker pull bug

### ISSUE THREAD

**Issue by kendiyqx** [docker/classicswarm#1559]
[root@localhost ]# docker -H tcp://XX.XX.X.XX:9000 run -m 512M docker.io.XX.net/nginx:latest
Error response from daemon: Failed to launch container: Failed to 'docker pull docker.io.XX.net/nginx:latest': exit status = exited with status 1 stderr = Error: image nginx:latest not found
[root@localhost ]# docker pull docker.io.XX.net/nginx:latest
latest: Pulling from nginx

fd929612d03e: Pull complete 
deb94812002f: Pull complete 
0cebb3f99e4d: Pull complete 
09515cbbce74: Pull complete 
a40be676a1a1: Pull complete 
0994788ebb88: Pull complete 
e1cb401b8718: Pull complete 
85b30b2b337f: Pull complete 
b245438526b7: Pull complete 
86ff62b28808: Pull complete 
bb63482c3ed8: Pull complete 
de0f9c8cb691: Pull complete 
Digest: sha256:cd7648473cd67dbc3a82e0dbbcc9d3b4ae855ed5ad4881f2c9a410f71d38ab2c
Status: Downloaded newer image for docker.io.XX.net/nginx:latest
[root@localhost]# 

swarm version：1.0.1

**Comment by vieux** [comment]
I see you are using `docker.io.XX.net/nginx:latest`

I'm guessing you have a private registry hooked up on `docker.io.XX.net` ?

If so, private registries will be supported on `docker run` in swarm 1.1
Right now you can use `pull` so pull the image on every node and then do the run


```
docker -H tcp://XX.XX.X.XX:9000 pull docker.io.XX.net/nginx:latest
docker -H tcp://XX.XX.X.XX:9000 run -m 512M docker.io.XX.net/nginx:latest
```

**Comment by disastrous-charly** [comment]
Hello,
I have the same issue since moving to swarm:1.0.0, it was working before.
We have a local registry, it doesn't find the image if none of the node had pull it.
If I'm trying with the swarm manager to pull, it's pulling on all the nodes.
Can I pull in only one node ? Do you know when the 1.1 will be release ?

**Comment by abronan** [comment]
Hi @disastrous-charly, do you have that same bug when trying with `swarm:1.0.1` or `master`?

**Comment by disastrous-charly** [comment]
Hello,
Just tried with 1.0.1 version, still have the issue when trying to run a image from private repo.
The error : `Error response from daemon: Error: image charly/super_app:1.0 not found` 

I will wait for 1.1 ;-)

**Comment by amitshukla** [comment]
@disastrous-charly can you please test with Swarm 1.1.0 RC2?
docker pull swarm:1.1.0-rc2

**Comment by disastrous-charly** [comment]
Hello,

Still have the same error :(
FYI, I upgraded my swarm master to docker 1.9.1. worker are in 1.9.0. Registry in 2.2.

Anything I could try ?

**Comment by vieux** [comment]
@disastrous-charly we are still lacking doc for this, but if you follow:

```
# Calculate the header
REPO_USER=yourusername
read -s PASSWORD
HEADER=$(echo "{\"username\":\"${REPO_USER}\",\"password\":\"${PASSWORD}\"}"|base64 -w 0 )
unset PASSWORD
echo HEADER=$HEADER

# Then add the following to your ~/.docker/config.json
"HttpHeaders": {
    "X-Registry-Auth": "<HEADER string from above>"
}
```

it should work.

**Comment by amitshukla** [comment]
@disastrous-charly also here: https://github.com/docker/swarm/blob/master/docs/swarm-api.md#registry-authentication

**Comment by disastrous-charly** [comment]
Hello all !
@vieux  Victoire ! It's working ! Thanks !

FYI : 
I upgraded my swarm master host, my 2 nodes, my private registry host to  docker 1.10
swarm master + nodes with swarm 1.1.0

The error when trying to pull without the header is now : 
`docker: Error response from daemon: Get https://cargo.irisa.fr:5000/v2/allgo/bigstat/manifests/1.0: no basic auth credentials`

With the header, everything is working great.

**Comment by amitshukla** [comment]
@kendiyqx @disastrous-charly can we close this issue now?

**Comment by disastrous-charly** [comment]
it's ok for me !

**Comment by slawekgh** [comment]
1. is it possible to run this solution with NGINX in front of private registry ?

2. where add "HttpHeaders" section in ~/.docker/config.json ? after auth section or before auth section? or maybe inside auth section? Can anybody give an example of such config.json file?

**Comment by slawekgh** [comment]
I found answers :-) 
1. yes, X-Registry-Auth header works also with nginx on front of private repo 
2. "HttpHeaders" section just after "auths":{}, only on swarm master

**Comment by slawekgh** [comment]
Is there any way to add 2 private repos ? That could mean 2 section with "X-Registry-Auth" 

I checked almost all variants of configuration and works only for last line of X-Registry-Auth , first lines are ignored
