### ISSUE TITLE
Do not use GOARCH for Architecture in `docker info`

### ISSUE THREAD

**Issue by tiborvass** [docker/classicswarm#1699]
Swarm should use, like Engine, `pkg/platform` in docker/docker to determine what architecture it is running on.

The problem with GOARCH is that since a 32bit binary can run on a 64 bit system, it will be shown as 32bit when in fact it is 64 bit.

As a side effect of using GOARCH, engine outputs `x86_64` while swarm outputs `amd64`.

**Comment by vieux** [comment]
I tried using `pkg/platform` and `pkg/parsers/operatingsystem` 

One of those 2 doesn't work on mac so I ended up using `GOARCH`

I'll try again and ping you if I have an issue.

**Comment by vieux** [comment]
@tiborvass also, why doesn't `version` use this fancy pkg https://github.com/docker/docker/blob/7a97e938e2229fa7a50b0f6e66c70eddcb9d2dc2/daemon/info.go#L133

**Comment by tiborvass** [comment]
@vieux thanks for those issues you raised. We're gonna address them :)

**Comment by vieux** [comment]
@tiborvass confirmed, it doesn't work on mac.

```
$ GOOS=darwin go build
# github.com/docker/docker/pkg/platform
../docker/pkg/platform/platform.go:18: undefined: runtimeArchitecture
```

Do you want me to update issues on docker/docker

**Comment by tiborvass** [comment]
@vieux sure, i'll fix it
