### ISSUE TITLE
Swarm API versions need refining

### ISSUE THREAD

**Issue by nishanttotla** [docker/classicswarm#1733]
I see ~~two issues~~ one issue with Swarm API versions
1. Currently, the Swarm API allows arbitrary version numbers. This doesn't make sense since Engine sets a lower limit (https://github.com/docker/docker/blob/012a3b6e74d753e1b0560d8f9b085b0fa0a80c0f/api/common.go#L19). I think Swarm should stay in sync with that. It makes sense to prevent issues such as #1727 caused by too many differences across API versions.
2. ~~A static API Version is returned for the `/version` endpoint in `api/handlers.go`. Now that we have the API version in the context, we should return that instead, while setting a static default, also like Engine does it.~~

@vieux @dongluochen @abronan thoughts?

**Comment by vieux** [comment]
Regarding #2, no they are different.
`api/handlers.go` should return a static number since it's the max version supported by the daemon (swarm) 
The version in context is the one the client is talking to you with, see on engine:

 ```
curl 0.0.0.0:2375/v1.12/version
{"Version":"1.10.0-dev","ApiVersion":"1.23","GitCommit":"69c381c","GoVersion":"go1.5.3","Os":"linux","Arch":"amd64","KernelVersion":"3.19.0-25-generic","BuildTime":"2016-01-29T09:27:23.291318833+00:00"}
```

ApiVersion is the engine version 1.23 even though I used 1.12 to talk to the engine.

**Comment by nishanttotla** [comment]
@vieux I get it now, you're right. Do you think we should fix the first one though?

**Comment by vieux** [comment]
@nishanttotla yes! according to https://docs.docker.com/engine/reference/api/docker_remote_api/ the minimum supported engine version by swarm (1.6.x) is using api 1.18, so 1.18 should be our minimum
