### ISSUE TITLE
Cluster of 10 PCs, multiple container in overlaynetwork, some containers can ping each other, others can't

### ISSUE THREAD

**Issue by carnuel** [docker/classicswarm#1748]
Hi,

Description of Setup:

10 hosts, one of which plays the role of the swarm manager
Discovery service consul on the host of the swarm manager
using an overlay network
the manager starts 9 containers with spread, one on each of the free nodes, some of them are able to ping each other, other's aren't.
They all appear in the docker -H 0.0.0.0:2375 info and   docker -H 0.0.0.0:2375 ps, can be entered with  docker -H 0.0.0.0:2375 exec -it ID bash. 
Some of the containers are working as expected, we are able to ping other containers, hosts and for e.g. google.
Other containers can ping hosts, google, but fail to ping any other container or to be pinged by them.
Which containers on which hosts have this problem changes everytime we start a new setup and seems to be completely random.

We tried out swarm:latest, :1.1.0-rc2 and 1.0.0

The same setup worked a few weeks ago. We are using ansible scripts and, shame on us, only pulled the :latest tag. We didn't write down the actual version. That's why we don't know which swarm version we used when it worked.

docker info:

```
Containers: 0
Images: 34
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-42-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.795 GiB
Name: ssds110
ID: N2W6:HP7F:KIAO:BHNR:LKE2:YNDM:BFO5:QAFB:CZFK:ZNKO:LX35:W4KL
WARNING: No swap limit support
```

We happy to provide further information and logs, please tell us which, as there are so many to choose from.

Edit:
 docker -H 0.0.0.0:2375 info

```
Containers: 9
Images: 36
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 9
 ssds111: IP.111:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds112: IP.112:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-47-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds113: IP.113:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds114: IP.114:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds115: IP.115:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds116: IP.116:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds117: IP.117:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds118: IP.118:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 ssds119: IP.119:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.984 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
CPUs: 18
Total Memory: 35.86 GiB
Name: 5c43445107cd
```

Thank you,
Manuel and Carlo

**Comment by vieux** [comment]
@carnuel did you update your engines ? are are they still in 1.9.1 ?

**Comment by carnuel** [comment]
We are still using Ubuntu 15.04 and just realized that docker 1.10 is not supported and will upgrade to ubuntu 15.10 soon.

**Comment by schmunk42** [comment]
@vieux Is there a special reason why `docker info` on a swarm is not including `docker` and `swarm` version? Should I open a new ticket for this?

**Comment by vieux** [comment]
@schmunk42 you mean `Server Version:` in docker info ? it was added in 1.10 apparently, I'm going to open a PR asap

**Comment by vieux** [comment]
@schmunk42 see https://github.com/docker/swarm/pull/1789

**Comment by amitshukla** [comment]
@carnuel is the problem resolved after upgrading to Engine 1.10?

**Comment by carnuel** [comment]
@amitshukla sorry for the late response. 

It works on ubuntu 15.10 with Engine 1.10.
 Though I am pretty sure we faced the same problem once during testing, i.e. we couldn't ping between some containers as mentioned above. But we weren't able to reproduce the error the day after.

 Altogether, it seems to work. We setup a cluster of containers on several hosts, tested a few things, took them down again, and repeated that multiple times.. It worked.

**Comment by deviantony** [comment]
I think I'm having a related situation here.

This morning, one container was unable to ping some other containers in the cluster. Have a look at the commands below:

Try to ping containerB from containerA: KO.

```shell
# docker -H  <SWARM_MANAGER>:4000 exec -i -t containerA bash -l -c 'ping containerB'
PING containerB (10.0.1.12) 56(84) bytes of data.
^C
--- db_balancer ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1007ms
```

Try to ping containerA from containerB: OK

```shell
# docker -H  <SWARM_MANAGER>:4000 exec -i -t containerB  bash -l -c 'ping containerA'
PING containerA (10.0.1.8): 56 data bytes
64 bytes from 10.0.1.8: icmp_seq=0 ttl=64 time=0.559 ms
64 bytes from 10.0.1.8: icmp_seq=1 ttl=64 time=0.306 ms
64 bytes from 10.0.1.8: icmp_seq=2 ttl=64 time=0.301 ms
64 bytes from 10.0.1.8: icmp_seq=3 ttl=64 time=0.387 ms
64 bytes from 10.0.1.8: icmp_seq=4 ttl=64 time=0.276 ms
^C--- web2 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.276/0.366/0.559/0.104 ms
```

And the weirdest part, just after that, try again to ping containerB from containerA: OK
```shell
# docker -H  <SWARM_MANAGER>:4000 exec -i -t containerA bash -l -c 'ping containerB'
PING containerB (10.0.1.12) 56(84) bytes of data.
64 bytes from containerB.myOverlayNet (10.0.1.12): icmp_seq=1 ttl=64 time=0.342 ms
64 bytes from containerB.myOverlayNet (10.0.1.12): icmp_seq=2 ttl=64 time=0.226 ms
64 bytes from containerB.myOverlayNet (10.0.1.12): icmp_seq=3 ttl=64 time=0.247 ms
^C
--- db_balancer ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.226/0.271/0.342/0.053 ms
```
