### ISSUE TITLE
Do not really on mux vars for container, network, volume names

### ISSUE THREAD

**Issue by doronp** [docker/classicswarm#1749]
e.g.

https://github.com/docker/swarm/blob/master/api/handlers.go#L452

This may prevent plugins from modifying the respected resources names before being processed.
Use the request instead.

**Comment by nishanttotla** [comment]
@doronp Can you clarify the issue a little further? What exactly are you trying to modify?

**Comment by doronp** [comment]
@nishanttotla 
Any plugin which changes anything is the URL will be able to modify the request but not the mux vars as it runs in another process.

**Comment by doronp** [comment]
See PR #1770
