### ISSUE TITLE
install with machine step 2 needs to be improved

### ISSUE THREAD

**Issue by moxiegirl** [docker/classicswarm#1771]
https://twitter.com/jjasghar/status/696752027251003392

![image](https://cloud.githubusercontent.com/assets/1347209/12894036/59804672-ce49-11e5-9d13-57c45378e435.png)

**Comment by nishanttotla** [comment]
Related #1767

The tutorial in the current form does not work. I'm working on fixing it now.

**Comment by nishanttotla** [comment]
@moxiegirl I think the issue here is also that JJ Asghar is confused that the two docs https://docs.docker.com/swarm/provision-with-machine/ and https://docs.docker.com/swarm/install-w-machine/ are different. Why do we have two of these?

**Comment by moxiegirl** [comment]
@nishanttotla `provision-with-machine.md` explains that it is possible but doesn't show how to do it step-by-step.  `install-w-machine` which we will rename to remove the `machine` assumes a local install in a Toolbox environment but uses the regular `swarm` image to provision.
