### ISSUE TITLE
swarm-docker build and spread strategy

### ISSUE THREAD

**Issue by auzias** [docker/classicswarm#1783]
Hi everyone!

**Edit: two problems were identified**
#### swarm-docker build -t custom-image

Despite the `swarm-docker build -t custom-image`, the `custom-image` has only been built on a single node (the first to appear through `swarm-docker info`).
#### Odd scheduling

Note also that an odd scheduling occurred while performing `swarm-docker run --rm -it debian`, `debian` image being on all nodes already. While the strategy is **spread** the containers were expected to _spread_ evenly on all the Swarm node, yet when  has been run 12 times, among the 12 containers started none were on `bugs9` (see the `swarm-docker info` below):

```
$swarm-docker ps --format "{{.ID}}: {{.Names}}"
c3b0bc858f5f: bugs6/fervent_ptolemy
cdd405717a2a: bugs7/jovial_varahamihira
9525d1bdcf8e: bugs8/loving_hamilton
bd9fb54eaee2: bugs6/drunk_ride
a802cb45b7b4: bugs7/tiny_mcnulty
8f46a90c65e1: bugs8/naughty_yonath
c60ea4d4520e: bugs8/insane_davinci
f9a153aa86d3: bugs6/sad_yalow
26dd825afd7f: bugs7/nauseous_ptolemy
551d4ddfbbf6: bugs6/gigantic_lamarr
feeb6e1af7be: bugs7/awesome_cray
bd0588c30cc6: bugs8/agitated_yonath
a99fb99ff18c: bugs9/weaveplugin
25444790065a: bugs8/weaveplugin
b731d3bf69f2: bugs7/weaveplugin
2683cb6afb80: bugs6/weaveplugin
56ce2f989ff2: bugs8/weaveproxy
3e38b9008571: bugs9/weaveproxy
41618f5e8d91: bugs8/weave
60c817817660: bugs9/weave
63266203e991: bugs7/weaveproxy
194019669b96: bugs6/weaveproxy
02a276b65872: bugs7/weave
04206b148ee2: bugs6/weave
```

---
#### Environment details

**`docker version`**

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64
```

**`docker info`**

```
Containers: 13
 Running: 4
 Paused: 0
 Stopped: 9
Images: 22
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: weavemesh bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 47.25 GiB
Name: bugs10
ID: D2BC:KHHI:XU3R:VZPV:5SYM:HKZE:VCI3:US2A:KXEM:6A7N:V53I:AAZQ
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 192.168.196.10:2375
```

**`swarm info`**

```
Containers: 34
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Role: primary
Strategy: spread #### Highlighting spread strategy ####
Filters: health, port, dependency, affinity, constraint
Nodes: 4
 bugs6: 192.168.196.6:2375
  └ Containers: 15
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 49.62 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
 bugs7: 192.168.196.7:2375
  └ Containers: 3
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 49.62 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
 bugs8: 192.168.196.8:2375
  └ Containers: 3
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 49.62 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
 bugs9: 192.168.196.9:2375
  └ Containers: 13
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 49.62 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs
Plugins: 
 Volume: 
 Network: 
CPUs: 48
Total Memory: 198.5 GiB
Name: 22b98c4a84d2
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
```

**`uname -a`**

```
Linux bugs20 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
``
```

**Comment by auzias** [comment]
@amitshukla the post has been edited, it appears there are two different issues (on build and on strategy).

**Comment by schmunk42** [comment]
Related issue from compose: https://github.com/docker/compose/issues/2721

**Comment by vieux** [comment]
@auzias regarding build it's a not an issue to me, if you really need the image in every node, you can do

```
docker build
docker save
docker load
```

or

```
docker build
docker push
docker pull
```


regarding the other issue,

the 1st PR shows 6 containers on bugs6 and the info later says 15, do you have stopped containers ?

Also can you do a docker version against swarm ? 

Thanks

**Comment by auzias** [comment]
@vieux thanks for the reply. What should be the expected outcoming of a `swarm-docker build` ?
Mine is that the image would be built on every node.

> the 1st PR shows 6 containers on bugs6 and the info later says 15, do you have stopped containers ?

Some containers were stopped on the local docker of one of the Swarm agent.

> Also can you do a docker version against swarm ? 

**`swarm-docker version`**
````
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:        
 OS/Arch:      linux/amd64
````

**Comment by jpetazzo** [comment]
@auzias: Swarm won't build on every node, because if you have a large cluster (think 1000 nodes) it will be very costly. Also, imagine that you have a build that causes a lot of I/O activity, and it gets scheduled on a machine hosting a database: it will cause a performance degradation.

As indicated by @vieux, the best solution is to build on a single node, then copy the image where needed. If you're interested, here is [a script](https://github.com/jpetazzo/orchestration-workshop/blob/master/build-tag-push.py) that automates this process for apps based on Compose.

I hope this helps!

**Comment by auzias** [comment]
Thanks @jpetazzo.
I see, that makes sense and seems obvious.

I would like to write it up in the swarm doc. If any page of the doc would mention, should it be in the [swarm-api](https://github.com/docker/swarm/blob/master/docs/swarm-api.md) page or another one?

A question remains though:
What should be the _expected_ outcoming of a `swarm-docker build` ?
IMHO, a warning or a cowardly error message.

**Comment by jpetazzo** [comment]
I'll let @vieux or @moxiegirl answer the question about docs.

Regarding your question:

> What should be the expected outcoming of a swarm-docker build ?

The more I work with Swarm, the more I think that it's OK for Swarm to refuse to do builds :-) but it's a though question.

**Comment by auzias** [comment]
@jpetazzo +1 for a message-refusal (if my vote count).

The behavior about build makes me think about the pull one. Shouldn't they be coherent?

**Comment by auzias** [comment]
> I'll let @vieux or @moxiegirl answer the question about docs.

Any news?

**Comment by amouat** [comment]
Just jumping in with my 2c; I don't think Swarm should do builds at all and should error out on Docker build calls. That's not really what Swarm is for. If you really want to do a build on a Swarm node, log into that node.

(I also think Compose probably shouldn't do builds, but that's a whole other topic and not as clear cut).

**Comment by liorsbg** [comment]
Yes this is totally confusing. Maybe output what machine the image was built on?
