### ISSUE TITLE
Don't co-schedule containers which use "new-style" links

### ISSUE THREAD

**Issue by aanand** [docker/classicswarm#1811]
When using links with custom networks, it's not necessary to co-schedule linked containers. As suggested by @bfirsh in https://github.com/docker/swarm/pull/388#issuecomment-180017222, this constraint therefore should be removed where possible, so that apps making use of links for aliasing (and not for enabling communication in the first place) can be distributed across the cluster.

@mavenugo explains in https://github.com/docker/swarm/pull/388#issuecomment-180297671 that it's an "old-style" link if and only if the container was started with `--net bridge`, if I understand correctly. So if the container was started with any other value for `--net`, the links co-scheduling filter should not be applied.

**Comment by tiborvass** [comment]
Ping @nishanttotla

**Comment by nishanttotla** [comment]
Thanks @aanand @tiborvass, I'll look into this before the next rc. How urgent is this?

**Comment by tiborvass** [comment]
I don't know it's from https://github.com/docker/docker/issues/23885#issuecomment-228905441 your judgement :)

**Comment by thaJeztah** [comment]
When using the Swarm API, isn't networking always overlay, so never legacy links?

**Comment by aanand** [comment]
I couldn't say. I understand that it's the default, but I don't know if there's a significant number of users still using bridge networking.
