### ISSUE TITLE
Documentation update - Evaluate Swarm in a sandbox

### ISSUE THREAD

**Issue by apetitbois** [docker/classicswarm#1831]
Command in the documentation to update the DOCKER_HOST is not working with docker-compose.

In file: swarm/docs/install-w-machine.md

Replacing
`$ DOCKER_HOST=$(docker-machine ip manager):3376`
with
`$ DOCKER_HOST=tcp://$(docker-machine ip manager):3376`

and

`$ DOCKER_HOST=<manager_ip>:<your_selected_port>`
with
`$ DOCKER_HOST=tcp://<manager_ip>:<your_selected_port>`

**Comment by nishanttotla** [comment]
@apetitbois this works for me. Can you let me know what issue you have when you use the current docs?

**Comment by apetitbois** [comment]
Everything works until I need to start my containers.

Docker compose will error out with this message :
docker.errors.TLSParameterError: If using TLS, the base_url argument must begin with "https://".. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.


If I include tcp:// (which is what docker-machine env would set the variable to), this resolves the issue.

**Comment by dnt17** [comment]
**Before**
`docker info`
`Swarm: inactive`

**After @apetitbois 's suggestion**
`docker info`
`Swarm:`
    `NodeID:`
        `IsManager: No`

Running on Darwin & VirtualBox 5.0
