### ISSUE TITLE
Documented instructions for production swarm on aws don't produce a working envrionment

### ISSUE THREAD

**Issue by brynmathias** [docker/classicswarm#1839]
Hi All,

I have followed the instructions at:
https://docs.docker.com/swarm/install-manual/ for producing a production replicated cluster

However I end up with the following when querying the swarm.

`ubuntu@ip-172-31-44-159:~$ docker -H :4000 info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 0
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-77-generic
Operating System: linux
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: c6e21b0e2293`

If I connect manually to consul I can see the slave instances have joined

`ubuntu@ip-172-31-44-159:~$ docker -H :2375 run swarm list consul://172.31.44.159:8500
time="2016-02-18T13:34:18Z" level=info msg="Initializing discovery without TLS"
172.31.26.38:2375
172.31.26.39:2375`

When trying to run I get the following:

`
ubuntu@ip-172-31-44-159:~$ docker -H :2375 run hello-world

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
1. The Docker client contacted the Docker daemon.
2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
3. The Docker daemon created a new container from that image which runs the
   executable that produces the output you are currently reading.
4. The Docker daemon streamed that output to the Docker client, which sent it
   to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/userguide/

ubuntu@ip-172-31-44-159:~$ docker -H :4000 run hello-world
docker: Error response from daemon: No healthy node available in the cluster.`

Any suggestions as to a solution?

Cheers,
Bryn

**Comment by nishanttotla** [comment]
cc @moxiegirl

**Comment by dongluochen** [comment]
@brynmathias Can you start swarm manager with debug option `-l debug` and check the logs? Also remove `-d` in docker run so you can see the logs on consul. 

```
 $ docker run -p 4000:4000 swarm -l debug manage -H :4000 --replication --advertise 172.31.44.159:4000  consul://172.31.44.159:8500
```

You should see logs like this. 
```
DEBU[0000] Watch triggered with 2 nodes                  discovery=consul
DEBU[0000] Start monitoring events                       id=H3JG:RGEY:HVEZ:5PH2:57XL:ELQV:TPT7:KQVW:PO4H:SKCL:4DSS:YH3Z name=ip-xxx

```
