### ISSUE TITLE
Request: Marathon Health Check on Swarm (or please get curl on swarm image)

### ISSUE THREAD

**Issue by Spritekin** [docker/classicswarm#1862]
Hi,
I have installed swarm on marathon. All runs perfectly but now I would like to add some health checks.
Adding an HTTP health check is very easy, however adding a command health check is not. This is a simple example with two health checks doing the same thing:

```
  "healthChecks": [
        {
            "protocol": "HTTP",
            "path": "/info",
            "gracePeriodSeconds": 10,
            "intervalSeconds": 30,
            "portIndex": 0,
            "timeoutSeconds": 10,
            "maxConsecutiveFailures": 3
        },
        {
            "protocol": "COMMAND",
            "command": { "value": "curl -f -X GET http://swarmtest.marathon.mesos:2376/info" },
            "gracePeriodSeconds": 10,
            "intervalSeconds": 60,
            "timeoutSeconds": 10,
            "maxConsecutiveFailures": 3
        }
]
```

The HTTP check works perfectly. The Command check doesn't. The reason is that the command is run INSIDE the swarm image and there is no "curl" in there so it will fail. 

If I set the command to something simple like "echo 1" it works just fine so that means the command is reaching the container. For those interested, marathon runs the health check as:
docker exec the-container-name sh -c \" echo 1 \""

A health check is considered successful if it receives a response before the timeout, regardless of the response per se.

So I thought... maybe I can docker it. But there is no docker daemon inside the image either.

Meanwhile I can mount curl into swarm on container startup as a workaround, but it would be nice to have it in there from the start.

**Comment by Spritekin** [comment]
Ok I found wget in there... trying to change my command to post using wget.

**Comment by Spritekin** [comment]
Nope... is a simplified wget that won't send jobs.

**Comment by vieux** [comment]
@Spritekin maybe this could help  ?https://github.com/mesosphere/multiverse/blob/version-1.x/repo/packages/S/swarm/0/marathon.json

**Comment by Spritekin** [comment]
Thanks viewx, but my problem is not running swarm, as I said is running fine. 
It is not running an HTTP health check either.
Is specifically running a COMMAND health check. A command health check is a command run inside the container and I want to run a hello-world.
Imagine this, if you get a shell into a running swarm container (i.e. docker exec -ti my-swarm-container /bin/sh) then how do you request a job from within.

**Comment by dongluochen** [comment]
I'm not very clear how this health check is triggered. Can you install curl first before your run your health check command? Or can you build the container image with curl?
```
  "command": { "value": "sudo apt-get install curl & curl -f -X GET http://swarmtest.marathon.mesos:2376/info" },
```

**Comment by Spritekin** [comment]
That's the point of this request. I'm asking to add this to the Dockerfile
RUN apk update && apk add curl

That way we can get curl and run health checks in marathon.

**Comment by Spritekin** [comment]
Please please add it. It just adds 2 MB to the image size and it works fine. Already tested.

This are my final marathon health checks:
```
  "healthChecks": [
        {
            "protocol": "HTTP",
            "path": "/info",
            "gracePeriodSeconds": 10,
            "intervalSeconds": 30,
            "portIndex": 0,
            "timeoutSeconds": 10,
            "maxConsecutiveFailures": 3
        },
        {
            "protocol": "COMMAND",
            "command": { "value": "curl -i -H \"Accept: application/json\" -H \"Content-Type: application/json\" -X POST -d '{\"Image\": \"hello-world\", \"HostConfig\": {\"CpuShares\": 10}}' http://$HOST:2376/containers/create?name=SwarmHealthCheck" },
            "gracePeriodSeconds": 60,
            "intervalSeconds": 60,
            "timeoutSeconds": 30,
            "maxConsecutiveFailures": 3
        }
    ]
```
