### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by eric-basley** [docker/classicswarm#1887]
since swarm migration,when trying to run a container, we get such an error message:
Error response from daemon: No such container <name>
Whereas image is available, listed and can be tagged on all swarm's nodes.
ex:
docker images
rp3:~# docker images
timetrack 0d133694cd4a eaaacce3d273 3 weeks ago 860.2 MB

rp3# docker run -d --net=swarm -e constraint:node==rp3 -v /opt/timetrack:/config timetrack:0d133694cd4a

Error response from daemon: Error: image library/timetrack:0d133694cd4a not found

But if we remove node's contraints, like
rp3# docker run -d --net=swarm -v /opt/timetrack:/config timetrack:0d133694cd4a

it works
# docker info

Containers: 335
Images: 34
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
rp3: 10.254.254.1:2375
└ Status: Healthy
└ Containers: 164
└ Reserved CPUs: 0 / 4
└ Reserved Memory: 0 B / 32.9 GiB
└ Labels: executiondriver=native-0.2, kernelversion=4.2.0-25-generic, operatingsystem=Ubuntu 15.10, storagedriver=btrfs
└ Error: (none)
└ UpdatedAt: 2016-02-16T08:56:43Z
rp4: 10.254.254.2:2375
└ Status: Healthy
└ Containers: 171
└ Reserved CPUs: 0 / 4
└ Reserved Memory: 0 B / 32.9 GiB
└ Labels: executiondriver=native-0.2, kernelversion=4.2.0-25-generic, operatingsystem=Ubuntu 15.10, storagedriver=btrfs
└ Error: (none)
└ UpdatedAt: 2016-02-16T08:56:30Z
Kernel Version: 4.2.0-25-generic
Operating System: linux
CPUs: 8
Total Memory: 65.8 GiB
Name: 4729f079685d
# docker -v

Docker version 1.9.1, build a34a1d5
# docker run -it swarm help

A Docker-native clustering system
Version: 1.1.0 (a0fd82b)

**Comment by vieux** [comment]
@eric-basley it means the images `timetrack:0d133694cd4a` is not present on node `rp3`

In the 1st case, you add a node constraint, so it's going to schedule on `rp3`, image isn't here so it's going to try to pull and it can't (local images only I assume) so it's going to fail.

In the 2nd case, you don't have node constraint, so swarm is going to pick a machine where the image exists (I guess `rp4`)

**Comment by eric-basley** [comment]
How to explain that this commande ( docker run -d --net=swarm -e constraint:node==rp3 -v /opt/timetrack:/config timetrack:0d133694cd4a) doesn't run neither on rp3 nor on rp4.

How to explain I can list, tag, push the image from both servers whereas I cannot run it ?

**Comment by janekolszak** [comment]
+1
I have the same problem. For some reason swarm doesn't respect constraint:node variable and it builds an image somewhere and tries to run it somewhere else.

**Comment by allencloud** [comment]
@janekolszak 
Since `docker build` supports resource limit, such as CPU, MEM, Swarm will take this into consideration to select a Node which satisfies with condition to finish the build job.

**Comment by janekolszak** [comment]
@allencloud 
I have a  constraint:node==some-node 
```
docker-compose up --build
```
tries to run the image on some-node, but for some reason the image is not there.

**Comment by gianarb** [comment]
Same problem for me. I am trying to start a container inside a specific node and the image is not there.
I don't know how force build on this specific node, I am looking to do that at the moment.

**Comment by m0ta** [comment]
Similar situation on docker `1.12.0 build 8eab29e` swarm `1.2.4 (5d5f7f0)` and compose `1.8.0 build f3628c7`. 

Three instances (Swarm, A and B) joined by docker swarm using consul. Identical specs. Trying to build and run image via Swarm instance using `docker-compose` but having "image not found" error for instance B. Instance A shows the built image alright when calling `docker ps` but nothing for B. `docker info` shows both node healthy. Also using `constraint:node==<node name>` for both A and B in compose file. 

Work-around right now is to push the image to docker registry like @gianarb said, so when `docker-compose` is called, instance B could pull the image from there. 

Any other suggestion?

**Comment by marcelnicolay** [comment]
When you have a swarm cluster and you're trying to run a container with some node constraint, this error could happen if the node doesn't have the image build... to fix this you can activate docker-machine in node, `eval $(docker-machine env node)`, and force the image build with `docker-compose build`.... after that you can switch again to swarm mode, `eval $(docker-machine env --swarm master)`, and run `docker-compose run`.

this worked for me, but i think that would be better if the swarm could replicate images among nodes.
