### ISSUE TITLE
Proposal: set desired state for rescheduled containers when node failure

### ISSUE THREAD

**Issue by allencloud** [docker/classicswarm#1891]
Although rescheduling container when node failure is an experimental feature, I think it can promote container 's HA a lot.

Now when rescheduling happens for a container, swarm create a new container and start it if the old container's state is running.Here is the code:[https://github.com/docker/swarm/blob/master/cluster/watchdog.go#L84-L89](https://github.com/docker/swarm/blob/master/cluster/watchdog.go#L84-L89)

```
if c.Info.State.Running {
    log.Infof("Container %s was running, starting container %s", c.Id, newContainer.Id)
    if err := w.cluster.StartContainer(newContainer); err != nil {
        log.Errorf("Failed to start rescheduled container %s", newContainer.Id)
    }
}
```

I do not  think just taking running into consideration is enough. As set the desired state for rescheduled container will meet a lot of production need, I suggest to set desired state for a container like the following state. A container could be one of  these states. [https://github.com/docker/docker/blob/v1.10.2/container/state.go#L74-L94](https://github.com/docker/docker/blob/v1.10.2/container/state.go#L74-L94)

```
// StateString returns a single string to describe state
func (s *State) StateString() string {
    if s.Running {
        if s.Paused {
            return "paused"
        }
        if s.Restarting {
            return "restarting"
        }
        return "running"
    }

    if s.Dead {
        return "dead"
    }

    if s.StartedAt.IsZero() {
        return "created"
    }

    return "exited"
}
```

Proposal:
After create container , we check old container's state,like the following order:

```
if running{
    if paused{
        startContainer
        pauseContainer
        return    
    }
    if restarting || running{
        startContainer
        return
    }
   return
}

if dead || created {
    return // do nothing
}

//exited
startContainer
stopContainer
```

when there is one action(such as startContainer) failed, swarm rolls back:
- remove new container if necessary
- add old container in original engine
- remove new container in new engine

Sincerely hope to get your feedback.

Thanks.

**Comment by allencloud** [comment]
WDYT @vieux @abronan @jimmyxian @nishanttotla

**Comment by vieux** [comment]
I don't really like the idea of 

```
startContainer
stopContainer
```

when it was exited, but I would be ok to implement pause
