### ISSUE TITLE
Swarm bootstrapping when using TLS and domains instead of IPs

### ISSUE THREAD

**Issue by michaelzangerle** [docker/classicswarm#1934]
I have a basic docker swarm setup including containers for swarm-master, swarm-nodes and etcd. I also added TLS according to the docs with a self signed certificate and created a overlay network where I can ping from one container to another one by using the their names. Up to this point everything works fine. 

In the next step I want to use a real certificate and also domains instead of IPs. So I start etcd as usually and then the client like this:

```
docker run --name node1 \
           -v /certs/cloud:/certs:ro \
           -h "swarm-node-1.cloud" \
           swarm join \
           --advertise=swarm-node-1.cloud:2376 \
           --discovery-opt kv.cacertfile=/certs/cloud.ca-bundle \
           --discovery-opt kv.certfile=/certs/cloud.crt \
           --discovery-opt kv.keyfile=/certs/cloud.key \
           etcd://discovery-1.cloud:4001
```

One problem is that the domain _discovery-1.cloud_ can not be resolved (of course!). Because of that I linked the swarm node container with the etcd container (`--link etcd:discovery-1.cloud`). The same problem appears again for the swarm master. But the swarm master also needs to know how he should resolve `swarm-node-1.cloud` and therefore I added `--add-host=swarm-node-1.cloud:192.168.10.27`. 

```
docker run --name manager -p 3376:3376 \
           --add-host=swarm-node-1.cloud:192.168.10.27 \
           --link etcd:discovery-1.cloud \
           -v /certs/cloud:/certs:ro \
           -h "swarm-manager.cloud" \
           swarm --debug \
           manage etcd://discovery-1.cloud:4001 \
           --tlsverify \
           --tlscacert=/certs/cloud.ca-bundle \
           --tlscert=/certs/cloud.crt \
           --tlskey=/certs/cloud.key \
           --discovery-opt kv.cacertfile=/certs/cloud.ca-bundle \
           --discovery-opt kv.certfile=/certs/cloud.crt \
           --discovery-opt kv.keyfile=/certs/cloud.key \
           --advertise=swarm-manager.cloud:3376 \
           -H tcp://0.0.0.0:3376
```

I think that these issues are just bootstrapping issues and wont be relevant when the overlay network is setup and the hostname of containers can be resolved. If there is a better way to bootstrap these containers then please let me know!

The setup seems to be working as I get this result from the swarm manager:

```
➜  ~ docker --tlsverify \
       --tlscacert=/certs/cloud/cloud.ca-bundle \
       --tlscert=/certs/cloud/cloud.crt \
       --tlskey=/certs/cloud/cloud.key \
       -H=localhost.cloud:3376 info

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 9
Server Version: swarm/1.1.2
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 mzangerle: swarm-node-1.cloud:2376
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 8.083 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-30-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-08T16:07:39Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 4.2.0-30-generic
Operating System: linux
Architecture: amd64
CPUs: 4
Total Memory: 8.083 GiB
Name: swarm-manager.cloud

```

To create an overlay network I previously had to add the `--cluster-advertise` and `--cluster-store` to the docker.conf:

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --dns 8.8.8.8 --dns 8.8.4.4 --cluster-advertise=192.168.10.27:0 --cluster-store=etcd://192.168.10.27:2379 --tlsverify --tlscacert=/certs/cloud/cloud.ca-bundle --tlscert=/certs/cloud/cloud.crt --tlskey=/certs/cloud/cloud.key
```

So I tried to adjust these flags with domain names instead of IP addresses as you can see here ...

```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --dns 8.8.8.8 --dns 8.8.4.4 --cluster-advertise=localhost.cloud:0 --cluster-store=etcd://discovery-1.cloud:2379 --tlsverify --tlscacert=/certs/cloud/cloud.ca-bundle --tlscert=/certs/cloud/cloud.crt --tlskey=/certs/cloud/cloud.key
```

But when I try to restart the docker daemon I get following error messages and it seems that docker does not accept domains for these flags:

```
FATA[0000] Error starting daemon: discovery advertise parsing failed (invalid cluster advertise IP address or interface name (swarm-node-1.cloud:0) : route ip+net: no such network interface)
```

**So my questions are:**
- Is there a better way to do this kind of bootstrapping?
- How can I create a overlay network when using TLS and domains?

In case it's needed here is my docker version:

```
➜  ~ docker --version
Docker version 1.10.2, build c3959b1
```

**Comment by yanndegat** [comment]
same question : is there a reason why it's only possible to advertise on IPs?
