### ISSUE TITLE
Allow setting of default (or global) rescheduling policy for Swarm manager

### ISSUE THREAD

**Issue by mrapczynski** [docker/classicswarm#2007]
I looked through existing issues and did not see any mention of this so I would like to bring it up for a future Swarm iteration.

It would be great to see a command line flag added to the startup options of a Swarm manager that specifies a _default_ rescheduling policy for containers that do not explicitly provide one.

I have a Swarm a cluster with labeled soft boundaries between production, test, and management daemons, and all of my containers have an appropriate constraint provided in their YML manifests for Compose.

In my use case, to enable automatic rescheduling on node failure, I will need to go back to the source code for each application, update the YML files (because they are checked into Git with the app), and the re-run each build in my CI that auto-deploys the container. It's a lot of unnecessary busy work for me.

In contrast, I have an upgrade script that hits all of my Docker nodes and upgrades Swarm on each in a matter of seconds. Adding an additional command line flag to that script to enable new behavior as part of the next upgrade is painless.

**Comment by jimmyxian** [comment]
I like this idea. +1 for this
