### ISSUE TITLE
IPv6 with swarm 'manage' doesn't work

### ISSUE THREAD

**Issue by shmcfarl** [docker/classicswarm#2058]
**docker-version:**

Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:12:47 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:12:47 2016
 OS/Arch:      linux/amd64
 Experimental: true

**docker info:**

Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: vagrant-ubuntu-trusty-64
ID: Q5RK:ESPZ:NMKC:KGRL:WLHV:PLQ2:7CIU:YSUX:42AV:WF6N:P6SP:NFPJ
Debug mode (client): false
Debug mode (server): false
WARNING: No swap limit support
Experimental: true

**Additional environment details (AWS, VirtualBox, physical, etc.):**
-Vagrant with Virtualbox
-etcd node = 2001:db8:cafe:14::a
-manager node = 2001:db8:cafe:14::b
-swarm node = 2001:db8:cafe:14::c
-All three are reachable over IPv6.
-Swarm version 1.2.0-rc1

**Steps to reproduce the issue:**
1. Run etcd on etcd host and make sure IPv6 works to that host:

`MY_IPv6="[2001:db8:cafe:14::a]"

./etcd \
-name etcd-01 \
-initial-advertise-peer-urls http://$MY_IPv6:2380 \
-listen-peer-urls="http://0.0.0.0:2380,http://0.0.0.0:7001" \
-listen-client-urls="http://0.0.0.0:2379,http://0.0.0.0:4001" \
-advertise-client-urls="http://$MY_IPv6:2379" \
-initial-cluster-token etcd-01 \
-initial-cluster="default=http://$MY_IPv6:2380" \
-initial-cluster-state new -debug`

**PUT/GET to etcd:**
`curl -L -g http://[2001:db8:cafe:14::a]:4001/v2/keys/message -XPUT -d value="IPv6 test"
{"action":"set","node":{"key":"/message","value":"**IPv6 test**","modifiedIndex":20,"createdIndex":20},"prevNode":{"key":"/message","value":"this works","modifiedIndex":17,"createdIndex":17}}`

`curl -L -g http://[2001:db8:cafe:14::a]:4001/v2/keys/message
{"action":"get","node":{"key":"/message","value":"**IPv6`test**","modifiedIndex":20,"createdIndex":20}}`
1. Run 'swarm join' from swarm node:
   `docker run swarm:1.2.0-rc1 join --advertise=[2001:db8:cafe:14::c]:2375 etcd://[2001:db8:cafe:14::a]:2379
   time="2016-03-30T22:26:04Z" level=info msg="Initializing discovery without TLS"
   time="2016-03-30T22:26:04Z" level=info msg="Registering on the discovery service every 1m0s..." addr="[2001:db8:cafe:14::c]:2375" discovery="etcd://[2001:db8:cafe:14::a]:2379"
   time="2016-03-30T22:26:07Z" level=error msg="client: etcd cluster is unavailable or`misconfigured"`
2. Run 'swarm manage' from manager node:
   `docker run -p 4000:2375 swarm:1.2.0-rc1 manage etcd://[2001:db8:cafe:14::a]:2379
   time="2016-03-30T22:25:53Z" level=info msg="Initializing discovery without TLS"
   time="2016-03-30T22:25:53Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
   time="2016-03-30T22:25:56Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
   time="2016-03-30T22:25:59Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
   time="2016-03-30T22:26:02Z" level=error msg="Discovery error: Unexpected watch`error""`

**Describe the results you received:**
If I replicate this exactly only with IPv4 addresses it works perfectly.  I know etcd is working on IPv6. When I do a 'tcpdump' to watch to see if the node or manager try to use IPv6, I see no traffic at all.

**Describe the results you expected:**
I expect to see swarm nodes listed on the etcd console as well as a "Registered Engine" show up on the manager.

**Additional information you deem important (e.g. issue happens only occasionally):**
Just to make sure this wasn't specific to etcd, I ran it against consul and get:
time="2016-03-30T22:52:36Z" level=info msg="Initializing discovery without TLS"
time="2016-03-30T22:52:36Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2016-03-30T22:53:06Z" level=error msg="Discovery error: Get http://[2001:db8:cafe:14::a]:8500/v1/kv/docker/swarm/nodes?consistent=: dial tcp [2001:db8:cafe:14::a]:8500: i/o timeout"

**Comment by dongluochen** [comment]
@shmcfarl From your **manager node**, can you use `curl` to access discovery info, like `http://[2001:db8:cafe:14::a]:8500/v1/kv/docker/swarm/nodes?consistent=`? I want to validate network reachability first.

**Comment by dongluochen** [comment]
@shmcfarl I think your problem could be caused by no IPv6 routing in your container. See https://docs.docker.com/engine/userguide/networking/default_network/ipv6/. If you haven't enabled IPv6 routing in docker daemon, the container created with the following command do not have route to the etcd. 

```
docker run -p 4000:2375 swarm:1.2.0-rc1 manage etcd://[2001:db8:cafe:14::a]:2379
```

You can do a validation with `docker run -it ubuntu sh` on the manager node. You can inspect its IPv6 routes.

**Comment by shmcfarl** [comment]
Thanks.  I do have routes for the containers to reach the etcd node and back (those are manually set).  Docker automatically enables forwarding and adds a route for its prefix when you set the --ipv6 --fixed-cidr-v6 option.  So, I don't think it is a route issue.

I can reach the etcd IPv6 address from containers in my manager and swarm nodes:
**Ubuntu container on manager:**
root@a3ef2491605d:/# ping6 2001:db8:cafe:14::a
PING 2001:db8:cafe:14::a(2001:db8:cafe:14::a) 56 data bytes
64 bytes from 2001:db8:cafe:14::a: icmp_seq=1 ttl=63 time=0.378 ms

Ubuntu container on swarm node:
root@3c3e29cbc546:/# ping6 2001:db8:cafe:14::a
PING 2001:db8:cafe:14::a(2001:db8:cafe:14::a) 56 data bytes
64 bytes from 2001:db8:cafe:14::a: icmp_seq=30 ttl=63 time=0.996 ms

Today, after a complete rebuild, I am getting a slightly different error on the manager node BUT I am at least seeing a connection on the etcd console after I run the 'swarm manage' command:
**etcd node:**
2016-03-31 20:46:41.151095 I | etcdserver: published {Name:etcd-01 ClientURLs:[http://[2001:db8:cafe:14::a]:2379]} to cluster 89b5c84d35f7a1e
2016-03-31 20:46:49.116770 D | etcdhttp: [PUT] /v2/keys/docker/swarm/nodes?dir=true remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:46:49.118482 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?quorum=true&recursive=true&sorted=true remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:46:49.120245 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?recursive=true&wait=true&waitIndex=0 remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:48:58.033601 D | etcdhttp: [PUT] /v2/keys/docker/swarm/nodes/%5B2001:db8:cafe:14::c%5D:2375 remote:[2001:db8:cafe:2:0:242:ac11:2]:46653
2016-03-31 20:48:58.035733 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?quorum=true&recursive=true&sorted=true remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:48:58.036965 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?recursive=true&wait=true&waitIndex=45 remote:[2001:db8:cafe:1:0:242:ac11:2]:50539

**Manager node:**
sudo ip -6 route add 2001:db8:cafe:2::/64 via 2001:db8:cafe:14::c
sudo docker run -p 4000:2375 swarm:1.2.0-rc1 manage etcd://[2001:db8:cafe:14::a]:2379
time="2016-03-31T21:05:46Z" level=info msg="Initializing discovery without TLS"
time="2016-03-31T21:05:46Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2016-03-31T21:05:49Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
time="2016-03-31T21:05:49Z" level=error msg="Discovery error: 102: Not a file (/docker/swarm/nodes) [56]"
time="2016-03-31T21:05:49Z" level=info msg="Registered Engine vagrant-ubuntu-trusty-64 at [2001:db8:cafe:14::c]:2375"

I get a similar output on etcd for the swarm node:

2016-03-31 20:49:58.034829 D | etcdhttp: [PUT] /v2/keys/docker/swarm/nodes/%5B2001:db8:cafe:14::c%5D:2375 remote:[2001:db8:cafe:2:0:242:ac11:2]:46653
2016-03-31 20:49:58.037591 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?quorum=true&recursive=true&sorted=true remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:49:58.039203 D | etcdhttp: [GET] /v2/keys/docker/swarm/nodes?recursive=true&wait=true&waitIndex=46 remote:[2001:db8:cafe:1:0:242:ac11:2]:50539
2016-03-31 20:50:58.034758 D | etcdhttp: [PUT] /v2/keys/docker/swarm/nodes/%5B2001:db8:cafe:14::c%5D:2375 remote:[2001:db8:cafe:2:0:242:ac11:2]:46653
2016-03-31 20:50:58.0

Lastly,  I can run commands against the Manager node and things look pretty good. 
docker -H tcp://[2001:db8:cafe:14::b]:4000 info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 2
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 vagrant-ubuntu-trusty-64: [2001:db8:cafe:14::c]:2375
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.019 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-83-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-31T21:08:06Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-83-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 1.019 GiB
Name: 53b135914fb1
Debug mode (client): false
Debug mode (server): false

I don't know if anything changed in the code wise overnight but a rebuild seems to have helped.  

I am still a little concerned about this:
time="2016-03-31T21:05:49Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
time="2016-03-31T21:05:49Z" level=error msg="Discovery error: 102: Not a file (/docker/swarm/nodes) [56]"

**Comment by dongluochen** [comment]
You are using the same swarm:1.2.0-rc1 image. Can you enable debug log to see if there is more info on discovery? 
```
docker run -p 4000:2375 swarm:1.2.0-rc1 -l debug manage etcd://[2001:db8:cafe:14::a]:2379
```

You can use `list` to show the members in discovery. 
```
docker run swarm:1.2.0-rc1 -l debug list etcd://[2001:db8:cafe:14::a]:2379
```

**Comment by shmcfarl** [comment]
Seems like discovery is working ok.  Also, I don't get any errors after the "engine update succeeded" happens.

time="2016-03-31T21:47:13Z" level=debug msg="Watchdog enabled"
time="2016-03-31T21:47:13Z" level=info msg="Listening for HTTP" addr=":2375" proto=tcp
time="2016-03-31T21:47:16Z" level=error msg="Discovery error: client: etcd cluster is unavailable or misconfigured"
time="2016-03-31T21:47:16Z" level=error msg="Discovery error: 102: Not a file (/docker/swarm/nodes) [112]"
time="2016-03-31T21:47:16Z" level=debug msg="Watch triggered with 2 nodes" discovery=etcd
time="2016-03-31T21:47:16Z" level=debug msg="Start monitoring events" id="M7QK:YVJI:CS4N:WESA:2S4H:TSLU:DM7X:R4VK:BP4F:TB6Z:5CZZ:NZNR" name=vagrant-ubuntu-trusty-64
time="2016-03-31T21:47:16Z" level=debug msg="Start monitoring events" id="35AP:4LSB:FQ7D:NUMG:KYWH:RRC3:CYDY:RGM2:NWKT:AERJ:SI4U:LOTX" name=vagrant-ubuntu-trusty-64
time="2016-03-31T21:47:16Z" level=info msg="Registered Engine vagrant-ubuntu-trusty-64 at [2001:db8:cafe:14::d]:2375"
time="2016-03-31T21:47:16Z" level=info msg="Registered Engine vagrant-ubuntu-trusty-64 at [2001:db8:cafe:14::c]:2375"
time="2016-03-31T21:47:34Z" level=debug msg="Watch triggered with 2 nodes" discovery=etcd
time="2016-03-31T21:47:44Z" level=debug msg="Watch triggered with 2 nodes" discovery=etcd
time="2016-03-31T21:48:03Z" level=debug msg="Engine update succeeded" id="M7QK:YVJI:CS4N:WESA:2S4H:TSLU:DM7X:R4VK:BP4F:TB6Z:5CZZ:NZNR" name=vagrant-ubuntu-trusty-64
time="2016-03-31T21:48:10Z" level=debug msg="Engine update succeeded" id="35AP:4LSB:FQ7D:NUMG:KYWH:RRC3:CYDY:RGM2:NWKT:AERJ:SI4U:LOTX" name=vagrant-ubuntu-trusty-64

**Comment by shmcfarl** [comment]
It doesn't like the 'list' run:

docker run swarm:1.2.0-rc1 -l debug list etcd://[2001:db8:cafe:14::a]:2379
time="2016-03-31T22:00:20Z" level=debug msg="Initializing discovery service" name=etcd uri="[2001:db8:cafe:14::a]:2379"
time="2016-03-31T22:00:20Z" level=info msg="Initializing discovery without TLS"
2016/03/31 22:00:23 client: etcd cluster is unavailable or misconfigured

**Comment by dongluochen** [comment]
It looks like discovery issue with etcd. I have a consul set up and it works ok. cc @abronan.

**Comment by dongluochen** [comment]
@shmcfarl Do you see the same messages with IPv4?

**Comment by shmcfarl** [comment]
No. I get no errors at all if I use IPv4.

**Comment by dongluochen** [comment]
@shmcfarl Do I understand correctly that this is not a blocking issue on your side?

**Comment by shmcfarl** [comment]
As of a full rebuild and walking through this again, it is not a blocking issue but I do still see the errors.  I can check against the etcd store and see the nodes are there so I don't know what exactly it is whining about but Swarm seems to be happy.

**Comment by dongluochen** [comment]
It looks like an initial IPv6 connection issue to Etcd. But swarm manager would retry and it succeeds.

**Comment by shmcfarl** [comment]
That is exactly what I am seeing on this rebuild. It errors at first and then I never see the etcd messages about availability or misconfiguration again. Almost like some sort of race condition.
