### ISSUE TITLE
alignment of error message to match docker daemon for imageNotFoundError

### ISSUE THREAD

**Issue by dweinstein** [docker/classicswarm#2091]
it seems there is a difference between the error message one gets from the docker daemon vs using swarm. do you think we could align the two to be the same or at least send the same status message (I haven't confirmed if they do already) -- for sure it seems to be a different message:

https://github.com/docker/swarm/blob/ccb2bea9cf56a4fb1bddf6df160fc4e8497a3417/cluster/swarm/cluster.go#L140

vs

https://github.com/docker/docker/blob/4a7bd7eaef0038b006cf23adface84081e5aab3b/vendor/src/github.com/docker/engine-api/client/errors.go#L18

**Comment by doronp** [comment]
@dweinstein Can you please add steps to reproduce in which you include the command you have used both on Engine and Swarm and off course version and so on? Thanks!
