### ISSUE TITLE
`docker swarm info` and `docker info` show some different details

### ISSUE THREAD

**Issue by allencloud** [docker/classicswarm#2096]
Hi, all, 
I found that `docker swarm info` and `docker info` showed some different details in docker 1.10.0 and swarm/master.

Here are some aspects related to this situation:
- Images
- OSType
- Operating System
- Architecture
- Plugins(nothings)

**How to reporduce:**
I have only one docker host(192.168.2.59:2376) with swarm manager on it. Here is how I start my swarm manager on 192.168.2.59:

```
$GOPATH/bin/swarm -l debug manage -H tcp://0.0.0.0:2375 nodes://192.168.2.59:2376
```

Here is `docker -H tcp://127.0.0.1:2375` output:

```
root@ubuntu:~# docker -H tcp://127.0.0.1:2375 info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 41
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 ubuntu: 192.168.2.59:2376
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-08T04:40:31Z
  └ ServerVersion: 1.10.0
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 2.052 GiB
Name: ubuntu
```

And here is `docker -H tcp://127.0.0.1:2376` output:

```
root@ubuntu:~# docker -H tcp://127.0.0.1:2376 info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 55
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 365
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: RDEJ:ZCV6:CJH5:UCNB:P5RR:66LB:JZSO:YACX:TBL3:PYMV:2F77:KBUA
WARNING: No swap limit support
```

**Comment by doronp** [comment]
**Images** - I only manage to reproduce for short amount of time - The Swarm data is being refreshed and it gets back to being correct. 
Can you elaborate - how to reproduce this and for how long you can be in a state in which the image count is not the same?

    **OSType** - Put operating system value here?
    **Operating System** - Remove by leaving empty and use OTtype instead^^?

    **Architecture** - This is the arch on which Swarm is running, I'd actually change Arch to Architecture in the engine info output.

    **Plugins**(nothings) - No plugin support in Swarm yet -  should remove volume and network and add relevant later (on plans to add volumes or network to Swarm AFAIK) - So we can put 'None' for now.

More over I've noticed that the OS and arch descriptor in get version and get info are not uniform. So we can handle that while at it.

Comments?
