### ISSUE TITLE
docker swarm fails to start rescheduled container

### ISSUE THREAD

**Issue by ndeloof** [docker/classicswarm#2133]
running https://github.com/ndeloof/rpi-voting-app/tree/master/vote-apps on 4 Rapsberry Pis. This is Docker voting app, adapted by @jmMeessen to run on ARM.
Running Swarm 1.2.0 (ndeloof/rpi-swarm, based on hypriot's script)

docker-compose up do deploy the app on the cluster. Voting app lands on pi #4.
Kill pi4 - really kill it by power unplug, not a king system shutdown
## Expected :

container is rescheduled on another pi, restarted, and service restored.
## Actual :

failure is detected, container is re-created on another node, attempt to start it bu fail :

```
time="2016-04-15T18:21:25Z" level=info msg="Removed Engine pi4" 
time="2016-04-15T18:21:25Z" level=info msg="Rescheduled container 7d233bb937df415a62b77a5e88f40e241c518b130cb85232d5eaa38aa05e6966 from pi4 to pi2 as 320470a2a63f975ed5ab8f28bec2ac6fb4e438f3c25d583caf33afbe46af2811" 
time="2016-04-15T18:21:25Z" level=info msg="Container 7d233bb937df415a62b77a5e88f40e241c518b130cb85232d5eaa38aa05e6966 was running, starting container 320470a2a63f975ed5ab8f28bec2ac6fb4e438f3c25d583caf33afbe46af2811"
time="2016-04-15T18:21:26Z" level=error msg="Failed to start rescheduled container 320470a2a63f975ed5ab8f28bec2ac6fb4e438f3c25d583caf33afbe46af2811: 500 Internal Server Error: service endpoint with name voteapps_voting-app_1 already exists\n" 
time="2016-04-15T18:21:26Z" level=info msg="Rescheduled container e23d927e42625e63d0b6c6ed284fa05b208972caecf1b7640b51998e96679c46 from pi4 to pi3 as 4ab4282dc488c553ea10392550f9ba0bdab9d6026b6c3c793c3858be89b7ac19" 
time="2016-04-15T18:21:26Z" level=info msg="Container e23d927e42625e63d0b6c6ed284fa05b208972caecf1b7640b51998e96679c46 was running, starting container 4ab4282dc488c553ea10392550f9ba0bdab9d6026b6c3c793c3858be89b7ac19" 
time="2016-04-15T18:21:27Z" level=error msg="Failed to start rescheduled container 4ab4282dc488c553ea10392550f9ba0bdab9d6026b6c3c793c3858be89b7ac19: 500 Internal Server Error: service endpoint with name voteapps_worker_1 already exists\n"
```

Looks to me the overlay network forbid the new container to start as the previous instance hasn't been cleaned before, so the endpoint still exists.

**Comment by ndeloof** [comment]
@vieux @abronan any thoughts ?

**Comment by vieux** [comment]
@ndeloof I'll take a look asap.

**Comment by schmunk42** [comment]
Same here on our staging swarm with `1.1.3` - custom rescheduling. 

We were starting stacks with `docker-compose`; two stacks which have containers connected in a network together (separate compose files, with container affinity constrains) show errors.

So I tried to manually remove the network
```
docker network rm myapp_default/app.myapp.com# docker network rm myapp_default
Error response from daemon: 500 Internal Server Error: network myapp_default has active endpoints
```

Inspected it...

```
root@sepp-roj:/repo/stacks/auto/myapp/app.myapp.com# docker network inspect myapp_default
docker network inspect myapp_default
[
    {
        "Name": "myapp_default",
        "Id": "f67879d64b0229990bcd9c43e1e57630fd548eba0afabdf85b33022afee73d80",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.18.0/24",
                    "Gateway": "10.0.18.1/24"
                }
            ]
        },
        "Containers": {
            "ep-61307b606ed6ee0176cbd6acb7b3d031a182851bc343c9ac4c4466cb7700136d": {
                "Name": "myapp_worker_1",
                "EndpointID": "61307b606ed6ee0176cbd6acb7b3d031a182851bc343c9ac4c4466cb7700136d",
                "MacAddress": "02:42:0a:00:12:05",
                "IPv4Address": "10.0.18.5/24",
                "IPv6Address": ""
            },
            "ep-8252faf56a8732db71ddb35ce90a803ad9fc44fd92cfa684aa6c5faef8b23ead": {
                "Name": "myapp_redis_1",
                "EndpointID": "8252faf56a8732db71ddb35ce90a803ad9fc44fd92cfa684aa6c5faef8b23ead",
                "MacAddress": "02:42:0a:00:12:02",
                "IPv4Address": "10.0.18.2/24",
                "IPv6Address": ""
            },
            "ep-8265326f50459e8f6314b9f9496fcf84aa628eb840a6885ac3eb6266d66a1de6": {
                "Name": "myapp_nginx_1",
                "EndpointID": "8265326f50459e8f6314b9f9496fcf84aa628eb840a6885ac3eb6266d66a1de6",
                "MacAddress": "02:42:0a:00:12:04",
                "IPv4Address": "10.0.18.4/24",
                "IPv6Address": ""
            },
            "ep-da381f7ad537a548457878900e588538ce46d277b0ae03c6db4c578be7c65ceb": {
                "Name": "myapp_php_1",
                "EndpointID": "da381f7ad537a548457878900e588538ce46d277b0ae03c6db4c578be7c65ceb",
                "MacAddress": "02:42:0a:00:12:03",
                "IPv4Address": "10.0.18.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {}
    }
]
```

And tried to remove the containers, which fails 💥 

```
root@sepp-roj:/repo/stacks/auto/myapp/app.myapp.com# docker inspect myapp_php_1
docker inspect myapp_php_1
[]
Error: No such image or container: myapp_php_1
```

Trying to figure out a way to start the stacks, without renaming them.

PS: I think our `overlay` is not working 100% properly, but this does not affect our deployments at the moment, since they all end up on the same node.

**Comment by schmunk42** [comment]
Possibly related:
- https://community.getcarina.com/t/overlay-network-seems-to-have-a-stale-endpoint-and-cant-be-removed/139
- https://github.com/docker/swarm/issues/2149

**Comment by schmunk42** [comment]
After trying "everything" from `docker rm` over `docker network rm`, `docker-compose down`, etc..
The only workaround I found is to manually remove the keys from our *consul* discovery service.

If a container is registered with a network, but the container is no longer existing (for some reason - eg. node constraints failed in our case), it is not possible to remove the network (retried with swarm `1.2.1-rc1`) or to remove the container from the network (since docker complains about a non-existing container 😄).

There should either be a `--force` option for `network rm` or `network disconnect`.

**Comment by pballester** [comment]
same problem rescheduling a container in a overlay network generated by docker-compose, i think the same, new container is failing to start because the previous instance hasn't been cleaned.

**Comment by OlgaIvantsova** [comment]
The same problem on swarm 1.2.1

**Comment by dongluochen** [comment]
`network disconnect` has force option since Docker 1.10. Can you let us know if that can manually resolve your problem? If yes, Swarm can take this logic to clean up an endpoint. 

```
$ docker -H swarm-master-0:2375 network disconnect --help

Usage:	docker network disconnect [OPTIONS] NETWORK CONTAINER

Disconnects container from a network

  -f, --force        Force the container to disconnect from a network
  --help             Print usage
```

**Comment by doronp** [comment]
more in #2149

**Comment by svscorp** [comment]
@dongluochen after removing a container from a network it runs in another issue:

System error: nosandbox: error locating sandbox id e671d6cc9648672e5776020a09354310d764c4edc13dd67e60efc0d50e23860f: no sandbox found

**Comment by dongluochen** [comment]
@ndeloof @svscorp @schmunk42 #2436 fixes the issue of rescheduling containers with overlay network. The fix is included in [Swarm 1.2.5](https://github.com/docker/swarm/releases/tag/v1.2.5). Can you test 1.2.5 to see if your problem is resolved? Your feedback is appreciated.

**Comment by goruha** [comment]
on swarm 1.2.5
This fix create container but does not start it, even if you set restart always.
in logs I see

`time="2016-09-03T18:33:09Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="TCTR:BV5C:25BT:GRGL:L5DN:JBAF:VONJ:Z5NH:JARW:BVH4:CITP:JQAS" name=ip-10-0-2-212 
time="2016-09-03T18:33:09Z" level=warning msg="Failed to remove network endpoint from old container hopeful_bassi: Error response from daemon: endpoint hopeful_bassi not found" 
time="2016-09-03T18:33:09Z" level=info msg="Rescheduled container 9dc721640eb7497ece709cf5572cc352379c77b482c62f1fbfe6aacd99bc4161 from ip-10-0-2-212 to ip-10-0-2-249 as 27f6ba6aecefad13b17cebbffb221b146071851e9b562e11a8b4b60745aeca15" 
time="2016-09-03T18:34:05Z" level=error msg="Update engine specs failed: Cannot connect to the Docker daemon. Is the docker daemon running on this host?" id="TCTR:BV5C:25BT:GRGL:L5DN:JBAF:VONJ:Z5NH:JARW:BVH4:CITP:JQAS" name=ip-10-0-2-212 
time="2016-09-03T18:35:15Z" level=info msg="Removed Engine ip-10-0-2-212" 
`

**Comment by loockass** [comment]
Any news in this case?

In our project we run into same problem.
One of cluster hosts were restarted and then we cannot run bunch of containers because they still exists in network.  
We use same workaround as @schmunk42 mentioned - endpoinds were manually removed from key/value storage in consul.
