### ISSUE TITLE
Problem with network (overlay)

### ISSUE THREAD

**Issue by mamciek** [docker/classicswarm#2140]
After restart swarm works fine, but after a while, when some number or containers are created and running I am experiencing problem with network connection between containers (timeouts). I have noticed that it correlates with log entries:

Apr 19 11:36:23 node3 docker[3069]: time="2016-04-19T11:36:23.397441341+02:00" level=warning msg="2016/04/19 11:36:23 [WARN] serf: Query queue depth: 954\n"
Apr 19 11:36:23 node3 docker[3069]: time="2016-04-19T11:36:23.397524902+02:00" level=warning msg="2016/04/19 11:36:23 [WARN] serf: Event queue depth: 899\n"
Apr 19 11:36:24 node3 docker[3069]: time="2016-04-19T11:36:24.397677127+02:00" level=warning msg="2016/04/19 11:36:24 [WARN] serf: Event queue depth: 899\n"
Apr 19 11:36:24 node3 docker[3069]: time="2016-04-19T11:36:24.397806735+02:00" level=warning msg="2016/04/19 11:36:24 [WARN] serf: Query queue depth: 954\n"

Restart fixes the problem for a short time. I am using overlay networks.

 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

**Comment by dongluochen** [comment]
cc @mavenugo.

**Comment by schmunk42** [comment]
I see this with `1.11.0` and `swarm-1.2.1-rc1`.
