### ISSUE TITLE
swarm 1.2.0 fails to talk to docker 1.6.1

### ISSUE THREAD

**Issue by hsmade** [docker/classicswarm#2150]
When creating a swarm with one engine on version 1.6.1, it fails to add the engine because of:
Failed to validate pending node: Error reading remote info: json: cannot unmarshal number into Go value of type bool  Addr=172.17.0.1:2375
This does work with version 1.1.3

To replicate:
$ sudo ./bin/docker-1.6.1  -d -H 0.0.0.0:2375 -H unix:///var/run/docker.sock &
INFO[0000] +job init_networkdriver()  
INFO[0000] +job serveapi(tcp://0.0.0.0:2375, unix:///var/run/docker.sock) 
INFO[0000] Listening for HTTP on tcp (0.0.0.0:2375)  
INFO[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] -job init_networkdriver() = OK (0)  
WARN[0000] Your kernel does not support cgroup swap limit. 
INFO[0000] Loading containers: start.  
..
INFO[0000] Loading containers: done.  
INFO[0000] docker daemon: 1.6.1 97cd073; execdriver: native-0.2; graphdriver: aufs 
INFO[0000] +job acceptconnections()  
INFO[0000] -job acceptconnections() = OK (0)  
INFO[0000] Daemon has completed initialization          

$ ./bin/docker-1.6.1 run -ti -p 3375:2375 swarm:1.2.0 --debug manage -H 0.0.0.0:2375 nodes://172.17.0.1:2375

--------8<-------

DEBU[0000] Failed to validate pending node: Error reading remote info: json: cannot unmarshal number into Go value of type bool  Addr=172.17.0.1:2375

**Comment by allencloud** [comment]
I think it is an engine-api's handling error:
https://github.com/docker/engine-api/blob/master/client/info.go#L22

Swarm uses engine-api to communicate with docker engine.

I will try to check if we can solve it in engine-api

**Comment by allencloud** [comment]
I started a docker engine 1.6.1, and get /info details from it.
I find that in the response field `Debug` is 0 which is a number, while in engine-api it should be the type of bool, so imcompatiblity happens.
