### ISSUE TITLE
Auto scaling like kubernetes horizontal

### ISSUE THREAD

**Issue by yank1** [docker/classicswarm#2151]
Is there any solution like [kubernetes horizontal](https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/horizontal-pod-autoscaling) to _auto_ scale compose with Swarm?

Thx

**Comment by dongluochen** [comment]
Not available today. Swarm uses Docker-Compose to scale statically. CPU/QPS monitoring is needed to do auto scaling. Swarm doesn't have that yet.

**Comment by 030** [comment]
Perhaps [this ](https://github.com/docker/swarm/issues/2151)solves the issue?

**Comment by 030** [comment]
@yank https://stackoverflow.com/questions/41668621/how-to-configure-autoscaling-on-docker-swarm

**Comment by 030** [comment]
@dongluochen Could you indicate what tickets could be linked to this issue in order to implement autoscaling in docker swarm?

**Comment by sugun999** [comment]
Hi,

Looking for this feature to have with docker swarm to be able scale container apps based on CPU usage automatically like in kubernetes.

**Comment by GolanBarkan** [comment]
+1

**Comment by sugun999** [comment]
Hi,

Anyone has any other alternative solutions to achieve automatic container scaling with docker swarm based on CPU usage?

**Comment by althaf1088** [comment]
+1 . Without scaling swarm is not complete :(

**Comment by Nepoxx** [comment]
Devil's advocate: is this really docker swarm's responsibility? Docker swarm is a container management system, not a host management system. You can use AWS' auto-scaling with docker swarm just fine, you simply need your auto-scaling group to join the swarm when they're ready and the load will be spread. Other clouds work the same.

I'd love to see swarm handle this, but I'm not convinced it should, can anyone convince me otherwise?

**Comment by RehanSaeed** [comment]
I see Docker implementing this in their CLI and stack/compose files using some simple rules e.g. if CPU reaches 80% or memory reachers 60%, scale up and redistribute my containers accross the new node.

Docker would then provide an extensibility point for Cloud vendors like AWS/Azure. They could develop plugins like they do for volume mounts that implement the ability to add or remove Docker nodes.
