### ISSUE TITLE
Lost container  static IP setting when swarm rescheduling

### ISSUE THREAD

**Issue by killkill** [docker/classicswarm#2155]
I create a private network by bridge on two swarm nodes(node01/node02) :

```
docker network create \
  --driver=bridge --subnet=192.168.217.0/24 --ip-range=192.168.217.0/24 \
  --gateway=192.168.217.111 \
  -o "com.docker.network.bridge.name"="br0" br0
```

run a container by swarm manager:

```
docker -H $SWARM_MANAGER \
     run -d -P  --name dahuang002  --hostname dahuang002 \
     --ip 192.168.217.152 --net br0 \
     -e reschedule:on-node-failure --restart=always   my-nginx:v1
```

of course , swarm lunch a container get static IP 192.168.217.152 on node01 in my envirement , perfect work . 

I shutdown all containers on node01 and kill docker daemon to simulate node down，about 20s ， swarm manager knows  nodes01 down and toggle this container  reschedule later .
Container dahuang002 start on node02 as I want，but it lost static IP。
Inspect container dahuang002，it got another static IP 192.168.217.1，lost the parameter --IP config.

**Comment by killkill** [comment]
Any Idea ?

**Comment by dvenza** [comment]
I have this problem, too.

**Comment by doronp** [comment]
@killkill @dvenza 
Can you please put here the output for network ls?
Those two bridges are not the same network they just have the same name do they not?
