### ISSUE TITLE
No elected primary cluster manager error 

### ISSUE THREAD

**Issue by marsmensch** [docker/classicswarm#2157]
## What I have
- 3 nodes cluster
- manager node runs Consul 0.6.x server
- each node runs Swarm 1.2.0 with Consul as KVS
- Swarm is setup to use consul://MANAGER_IP:8500 for discovery
## Details

Since upgrading from Swarm 1.1.3 to 1.2.0 i have seen multiple cases where the cluster shows the _"No elected primary cluster manager"_ error. 

I replicated this with a publicly available repo.

**Steps to reproduce follow:**
1. Clone https://github.com/bdwilliams/vagrant-docker-swarm-boilerplate
2. vagrant up
3. Run docker ps agains the swarm master ( host "vagrant1")

The error does not occur when changing the swarm image version to 1.1.3 (changed in compose file). 

**Command:**  `vagrant ssh vagrant1 -c 'docker -H tcp://172.17.8.101:2375 ps`
**Expected:**   Show running containers in the cluster
**Result:**       Running containers in the cluster are shown

```
$ vagrant ssh vagrant1 -c 'docker version'
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```

**Command:**    `vagrant ssh vagrant1 -c 'docker -H tcp://172.17.8.101:2375 p`s
**Expected:**   Show running containers in the cluster
**Result:**     Error message "Error response from daemon: No elected primary cluster manager" is shown

```
$ vagrant ssh vagrant1 -c 'docker version'
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```
## Possibly related

I have found #2138 and #1782 which should both be fixed. Regression?

**Comment by abronan** [comment]
Hi @marsmensch,

I see in your Compose file that you are using a `--replication-ttl` at `4s` (which is a low value, for example in swarm we only use it in the CI to speed up tests). What if you bump it to `10s` or `15s`? The reason it was working with `swarm-v1.1.3` was that the session would **stick** in case something went wrong or the renew session failed. But this would cause errors when the store failed, leaving the key locked forever by the recovering Manager. So the current behavior is that the session is much more volatile on store failure or slow setups (like probaby, Vagrant). So I guess tell that the Leader is switching pretty often with such a low value.

Also, other question: when you see the `no elected leader` failure, does this recover after some time?

Thanks!

**Comment by marsmensch** [comment]
Hi @abronan,

i tried to bump the TTL to 10s and 15s and still got not joy. The following is an excerpt from the Swarm manager container logs:
```
time="2016-04-25T07:12:36Z" level=info msg="Leader Election: Cluster leadership lost"
time="2016-04-25T07:12:36Z" level=error msg="Unexpected response code: 500 (Invalid Session TTL '7500000000', must be between [10s=24h0m0s])"
time="2016-04-25T07:12:46Z" level=info msg="Leader Election: Cluster leadership lost"
time="2016-04-25T07:12:46Z" level=error msg="Unexpected response code: 500 (Invalid Session TTL '7500000000', must be between [10s=24h0m0s])"
time="2016-04-25T07:12:56Z" level=info msg="Leader Election: Cluster leadership lost"
time="2016-04-25T07:12:56Z" level=error msg="Unexpected response code: 500 (Invalid Session TTL '7500000000', must be between [10s=24h0m0s])"
time="2016-04-25T07:13:06Z" level=info msg="Leader Election: Cluster leadership lost"
time="2016-04-25T07:13:06Z" level=error msg="Unexpected response code: 500 (Invalid Session TTL '7500000000', must be between [10s=24h0m0s])"
```
I have no idea why the session TTL is interpreted as "7500000000", but i guess this is the culprint. Afaik consul has a max TTL of 14h. Removing the  `--replication-ttl` flag completely for Swarm 1.2.0 works for me.

Also did some more testing today and it does not recover.

Thank you for looking into it!

**Comment by abronan** [comment]
@marsmensch Sorry my mistake, you should bump it to at least `20s` because you are using Consul and it does not accept a TTL `< 10s` (because Consul divides the original TTL by 2x, also `7500000000` is in nanoseconds so this is `7.5s`). This should work using those values (default value without the flag is `60s` so that's why it works).

Otherwise you can still tweak Consul to accept a lower TTL value, you can take a look at #2153 for more infos.

**Comment by marsmensch** [comment]
Thank you @abronan, got it. The default will work for me!

I am still thinking about, if Swarm should implement some kind of logic (or a baseline) for the supported backends. Even a log message would help to lead other in the right direction. If nothing else, i am volunteering to write some docs in the appropriate section. What do you think?

Also the swarm integration tests [1] seem to use a container with a very old version of consul, a switch to https://github.com/gliderlabs/docker-consul would be great!

[1] https://github.com/docker/swarm/blob/master/test/integration/discovery/consul.bats

**Comment by 14msitaqadeer** [comment]
I also hit with the issue like that while installing consul on three different nodes:
ERRO[3353] discovery error: Unexpected response code: 500 (No cluster leader)
