### ISSUE TITLE
Container run on node join

### ISSUE THREAD

**Issue by etoews** [docker/classicswarm#2170]
When a node joins a Swarm cluster, it would be very useful to be able to specify a container to run on that node immediately after the node has joined the cluster.

Some examples of services that would make use of such a feature are [Docker Registry](https://github.com/docker/distribution), [Registrator](https://github.com/gliderlabs/registrator), [a Consul agent](https://www.consul.io/intro/getting-started/agent.html), [Docker Bench](https://github.com/docker/docker-bench-security), etc. 

We can see an example of the need for this @jpetazzo's [Orchestration Workshop](https://github.com/jpetazzo/orchestration-workshop/blob/master/www/htdocs/index.html#L4771-L4787). That he mentions "Swarm might do that automatically for us in the future." gives me hope that this feature is already being seriously considered.

Obviously it's a short leap to generalizing this feature into post-node-join and pre-node-disjoin hooks but it's probably best to focus on a container run on node join to start with.

**Comment by allencloud** [comment]
@everett-toews 
Is my understanding right?
You hope to specify a container to run on specific node.
And what is the relationship between this and node joining?

**Comment by dongluochen** [comment]
It's under the issue of global scheduling https://github.com/docker/swarm/issues/601. We have plan to implement them in the future. It requires persistent state management.

> When new nodes join the cluster, global containers should be scheduled on them.

**Comment by everett-toews** [comment]
@allencloud I hope to run a container on all nodes automatically (even when a new node joins the cluster).

The issue that @dongluochen referenced fits my use case. Thanks for that!
