### ISSUE TITLE
confused about scheduler.SelectNodesForContainer

### ISSUE THREAD

**Issue by adohe** [docker/classicswarm#2188]
FYI. I am just learning your scheduler code, I got confused when I noticed that `SelectNodesForContainer` method returns a node list, but always use the first one(`nodes[0]`), why not just make the scheduler return the first one(also the best one, since some sort has done). Besides I think there is no need to use `int64` to type weight of node, `int` is enough.

**Comment by allencloud** [comment]
I think `SelectNodesForContainer ` is useful, because in the future if swarm supports `global scheduling`, `SelectNodesForContainer` will be needed.

While, this is my own understanding. @AdoHe

**Comment by dongluochen** [comment]
Remember having similar conversation. I think the function signature of `SelectNodesForContainer` was intended to schedule multiple containers, e.g., a user wants to create 5 copies of nginx. With the list return it'd be easy to pick top 5 nodes and start the containers in parallel. I think this could be generalize to select top K nodes without sorting the whole list. But docker CLI doesn't have primitive for scheduling `n` copies of containers. I think it's a mix of intention and reality, it'd be clean up though.

**Comment by AdoHe** [comment]
I will do some improvement here and make a more clean interface.
