### ISSUE TITLE
docker stats fails resource clean up in test

### ISSUE THREAD

**Issue by dongluochen** [docker/classicswarm#2192]
On master branch, `api/stats` and `mesos/api/stats` do not clean up docker so next test cannot start properly and timeout. It may be related to Engine's re-architecture. 

See #2146.

**Comment by nishanttotla** [comment]
@dongluochen can we close this issue now?

**Comment by dongluochen** [comment]
@nishanttotla No. The issue of that failure is not clear yet. PR #2191 is to fix test. We still need to investigate the issue.
