### ISSUE TITLE
deploy containers on swarm cluster using compose file without using docker machine

### ISSUE THREAD

**Issue by shujamughal** [docker/classicswarm#2198]
Hi All,

I have build a swarm cluster without using docker machine. if we use docker machine then we can deploy using following 

eval "$(docker-machine env --swarm <name of swarm master machine>)"
$ docker-compose up

but without docker-machine how to access swarm master to deploy containers using compose file?

Regards
Shuja

**Comment by nishanttotla** [comment]
@shujamughal you can point your `DOCKER_HOST` to swarm ip:port, then use docker-compose
