### ISSUE TITLE
Unhealthy node block docker-compose pull image

### ISSUE THREAD

**Issue by jianchen2580** [docker/classicswarm#2209]
I have delete a node through **docker-machine rm**, When I try to run **docker-compose up**, the delete node still try to pull image and return error
`ERROR: Post https://xx.xx.xx.xx:2376/v1.15/images/create?fromImage=ehazlett%2Finterlock%3Alatest: dial tcp xx.xx.xx.xx:2376: i/o timeout`

`docker info`
`
swarm-node2: xx.xx.xx.xx:2376
  └ Status: Unhealthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.016 GiB
  └ Labels: com.tropo-ops.group=frontend, executiondriver=, kernelversion=4.2.0-18-generic, operatingsystem=Ubuntu 15.10, provider=amazonec2, storagedriver=aufs
  └ Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
  └ UpdatedAt: 2016-05-05T08:36:23Z
  └ ServerVersion: 1.11.1
`
`docker-compose -f demo.yml up -d`
`
swarm-node2: Pulling ehazlett/interlock:latest... : Post https://54.87.142.138:2376/v1.15/images/create?fromImage=ehazlett%2Finterlock%3swarm-node4: Pulling ehazlett/interlock:latest... : downloaded
swarm-frontend: Pulling ehazlett/interlock:latest... : downloaded
...
ERROR: Post https://54.87.142.138:2376/v1.15/images/create?fromImage=ehazlett%2Finterlock%3Alatest: dial tcp 54.87.142.138:2376: i/o timeout`

**Comment by dongluochen** [comment]
What is your compose file? Swarm doesn't use `Unhealthy` node for task scheduling.
