### ISSUE TITLE
Clarification: add new node filter to scheduler

### ISSUE THREAD

**Issue by sainath14** [docker/classicswarm#2223]
Can we extend node filter to add a new constraint on node selection?

**Comment by allencloud** [comment]
@sainath14 
You can follow the doc https://github.com/docker/swarm/blob/master/docs/scheduler/filter.md.
Actually you can use `constraint` to specify the node_id of node to select one.

**Comment by sainath14** [comment]
@allencloud similar to port management which is a limited resource in each node, we would like to enable swarm to manage a different resource on each node. Can we extend swarm scheduler to manage different resources in the same lines as ports?

**Comment by dongluochen** [comment]
What resources do you try to filter on?

**Comment by sainath14** [comment]
@dongluochen For example, if i want to manage the available number of sr-iov network devices? Consider i am using those network interfaces inside containers. they are limited on a given host. how flexible is docker swarm to add new filters like this?

**Comment by dongluochen** [comment]
It's a resource allocation problem. Under current Swarm framework you may consider the following 2 approaches. 

`Containerslots` filter was added recently for [abstract resources](https://github.com/docker/swarm/blob/b2de64872b65db4d88b33b1a77bf9a951a3a2577/docs/scheduler/filter.md). You can specify container slot count on a node from Docker daemon. Each container would occupy a slot. 

```
$ docker daemon --label containerslots=3
```

Another way is to map your resource to memory or CPU. When all memory or CPU are reserved, new requests with resource reservation fail. 

Both approaches doesn't handle arbitrary resource allocation, e.g., you have 3 different types of GPUs on each node. The concept of `containerslots` can be extended to deal with that. It could be a future task.

**Comment by sainath14** [comment]
@dongluochen  "map your resource to memory or CPU."
In my case the resource is a device - sriov network device. What do you refer to when you say "map to memory or CPU?"

**Comment by dongluochen** [comment]
It's a hack to use CPU or memory to represent your dedicated resource. Let's say you have 4 sr-iov devices on a node and 16GB memory. You want  to run 4 containers each uses one device. You can put constraint memory = 4GB for each container. The 4 containers use up the memory on the node. Subsequent container requests to the node with memory limit will be rejected.
