### ISSUE TITLE
Duplicate sentence in "Overview Swarm with TLS"

### ISSUE THREAD

**Issue by langston-barrett** [docker/classicswarm#2226]
Second paragraph under "Learn the TLS concepts" is

> Public key infrastructure is a combination of security-related technologies, policies, and procedures, that are used to create and manage digital certificates. These certificates and infrastructure secure digital communication using mechanisms such as authentication and encryption.

and the sixth is 

> Public key infrastructure (PKI) is the combination of technologies, policies, and procedures that work behind the scenes to enable digital certificates. Some of the technologies, policies and procedures provided by PKI include:

**Comment by allencloud** [comment]
Great. @siddharthist 
And a PR is appreciated to make everyone know what is your thoughts on how to better express the meaning. :)
