### ISSUE TITLE
Swarm should detect subnet conflicts when creating overlay networks

### ISSUE THREAD

**Issue by vikstrous** [docker/classicswarm#2232]
Swarm should detect this error: https://github.com/docker/docker/issues/19499 and it should try to recover from it by gathering information about the subnets available on all nodes and then picking an available subnet instead of the default one.

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
Could I try fixing this issue?

**Comment by vikstrous** [comment]
I should add that on newer kernels, there's no error message. It succeeds and then the local network with the overlapping range is not accessible from within containers that are on the overlay network. Swarm should detect that case too.

**Comment by dongluochen** [comment]
@mavenugo Is there work item on networking side to address this problem?

**Comment by dongluochen** [comment]
@jmzwcn We welcome contribution including idea, code, test, and issue comments! Please go over https://github.com/docker/swarm/blob/master/CONTRIBUTING.md. You may write your fix proposal in this thread before submitting PR.

**Comment by jmzwcn** [comment]
By tracking codes, I find we seem to could do this validation at swarm/cluster.go func CreateNetwork(line 463), such as adding a method(similar to 'func checkNameUniqueness'), within it, we could take some unique verifications, including name, subnet,...

@dongluochen, how do you think please?

**Comment by vikstrous** [comment]
When the subnet is not set, I expect swarm to contact all nodes, gather information about all networks that exist on all of them, find a subnet that is safe to use on all of them and use that one.

They only issue with this idea is that you can't specify how big you want your subnet to be. I think this is another area where using the docker protocol makes things awkward. Maybe you can accept a subnet with the format `"/24"` (no ip) where 24 is the size of the network?

**Comment by jmzwcn** [comment]
ping @dongluochen

**Comment by dongluochen** [comment]
@vikstrous Swarm and Docker use the same engine-api that it cannot accept subnet not in CIDR format. 

@jmzwcn I think it make sense to find a unique subnet (/24) by examining existing subnets. Swarm should already have all subnet info from every node. Maybe we can define a method `FindAvailableSubnet(existingSubnets []*net.IPNet, ipSpace *net.IPNet, bitMaskLen uint) (*net.IPNet, error)`. It can return a subnet with expected size. With this target subnet Swarm manager can issue network create command with `--subnet=[]` option. WDYT?

**Comment by jmzwcn** [comment]
@vikstrous, @dongluochen,
Please refer to [here](https://github.com/docker/libnetwork/blob/master/network.go#L1150), actually libnetwork have similar check, but it seems only available for kernel(>=3.16)?

**Comment by allencloud** [comment]
@jmzwcn 
Since docker 1.10， docker engine only needs a kenerl version of 3.10.

**Comment by dongluochen** [comment]
@jmzwcn I think you are right. From the description of https://github.com/docker/docker/issues/19499,  kernel < 3.16 may have this subnet conflict problem. If we want to eliminate this problem for kernel < 3.16, Swarm would needs to collect the subnets and find an available one, then use `--subnet` to create subnet explicitly.

**Comment by jmzwcn** [comment]
As libnetwork, I think swarm could also explicitly use --subnet to avoid this problem before kernel <3.16, I am not sure if we should handle this issue.
