### ISSUE TITLE
Unexpected number of images returned by docker info

### ISSUE THREAD

**Issue by mbentley** [docker/classicswarm#2234]
In swarm 1.1.3, I am seeing that the number of docker images reported back isn't showing what I would expect:

```
$ docker info
Containers: 51
 Running: 51
 Paused: 0
 Stopped: 0
Images: 601
Server Version: swarm/1.1.3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 6
 mbentley-demo01: 172.31.17.160:12376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:03Z
 mbentley-demo02: 172.31.28.203:12376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:30Z
 mbentley-demo03: 172.31.22.45:12376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:12Z
 mbentley-demo04: 172.31.31.1:12376
  └ Status: Healthy
  └ Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:44Z
 mbentley-dtr: 172.31.20.139:12376
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:14Z
 mbentley-master: 172.31.25.61:12376
  └ Status: Healthy
  └ Containers: 12
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.86 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.4 LTS, provider=amazonec2, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-12T13:34:34Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-53-generic
Operating System: linux
Architecture: amd64
CPUs: 6
Total Memory: 23.16 GiB
Name: 1732f33791f6
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

In my example, if you perform a `docker images` and check the number of images, it returns:

```
$ docker images | grep -v ^REPOSITORY | wc -l
     278
```

I am unsure if this number is the number of images in the cluster, irregardless of duplicates (e.g. - node1 and an image and node2 has an image, it would count as two) or if it is counting the intermediate images in the count.  I would expect the `docker info` output to match the number of images one would see from a `docker images`.

**Comment by allencloud** [comment]
@mbentley 
This question is really good.
To make it clear. We need to know several concepts.
`docker images` on one machine shows the **tagged images numbers* .
For example: you pulled an image `ubuntu:latest` and tagged it anonther name `ubuntu:latest2`, then `docker images` shows 2 images. Actually in the underlying filesystem, there is only the number of layers in ubuntu:latest images.

And `docker info` against Swarm, output only shows 1 image.
But `docker images` againt Swarm, output shows 2 images.

Hope it helps.

**Comment by mbentley** [comment]
Hmm, but that doesn't explain why I have a much larger number of images showing from `docker info` compared to `docker images`, both against swarm.  I'd expect it to be just the opposite based off of what you said.  It almost looks like it is checking to see how many images are on each node individually and tallying them.  If that is what it is actually doing, that's fine, but it's just not consistent with what you see from `docker images` against swarm which is what I would actually expect I suppose.
