### ISSUE TITLE
Compose + Swarm + Port Mapping error

### ISSUE THREAD

**Issue by yank1** [docker/classicswarm#2246]
Compose + Swarm + Port Mapping error

Environment: One node swarm.
## Step 1

```
redis: 
  image: daocloud.io/redis:3
  ports: 
    - "6378:6379"
  restart: unless-stopped 
```

`docker-compose up`

everythink ok.
## Step 2

```
redis: 
  image: daocloud.io/redis:2
  ports: 
    - "6378:6379"
  restart: unless-stopped 
```

`docker-compose up`

Error Message.

```
2016-05-17 17:00:04   Recreating 01a75d7735a8_redis_redis_1
2016-05-17 17:00:04  
2016-05-17 17:00:04   ERROR: for redis  Unable to find a node that satisfies the following conditions 
2016-05-17 17:00:04   [port 6378 (Bridge mode)]
2016-05-17 17:00:04
```

I know it's due to #2015 , but the compose+swarm cannot work in the upgrade image case.

**Comment by dongluochen** [comment]
You can do it with this sequence. 
`docker-compose up`
`docker-compose down`
update .yml
`docker-compse up`

**Comment by yank1** [comment]
@allencloud could you help us?

**Comment by allencloud** [comment]
@yank1 
Swarm just provides the same API as docker engine.
It is better for people to understand all procedures of docker-compose's action.
For instance, with a docker-compose.yml, `up` action will do what kinds of docker APIs.
with a same docker-compose.yml however changed some fields, `up` action behaves what kind of difference.

**Comment by OferE** [comment]
+1 - i also encountered this - even though the swarm configuration includes the port filter.
This is a real bug in the port filter  IMHO
