### ISSUE TITLE
cannot supply local bridge networks when using reschedule flag

### ISSUE THREAD

**Issue by doronp** [docker/classicswarm#2249]
docker -H localhost:4000 network create -d bridge localNet

docker -H localhost:4000 run -tdi -e reschedule:on-node-failure --net=LocalNet busybox
docker: Error response from daemon: Error response from daemon: network LocalNet not found.
See 'docker run --help'.

docker -H localhost:4000 run -tdi -e --net=LocalNet busybox
b7c4f76ddd7f9147a269b6384098c72ae7e5e832ba045e31b1ddbe2ebb534307

IMHO 
1 - cannot let create local networks without node context (see issue #2248)
2 - One option should be adopted:
- Do not support reschedule which uses local networks if we do not plan to support reschedule of the network as well and change that mislead error message accordingly and document
- Do support it :-)

**Comment by allencloud** [comment]
@doronp 
Yes, That's true.
However it is nothing to do with using reschedule flag.
```
docker -H localhost:4000 run -tdi --net=LocalNet busybox
```
will show the same error.

Swarm needs improvement at this area.

**Comment by doronp** [comment]
@allencloud Agree. Probably bumped into that while doing reschedule related stuff. I will take a look at a possible fix.

**Comment by allencloud** [comment]
Great. @doronp
Maybe we can first present a proposal, and have a warm discussion with the community. It is fantastic work.

Now I have suggestion about `The four top level concept of Docker: container, image, volume, network`, just take network as an example:

1.Background: Swarm use `func (networks Networks) Get(IDOrName string) *Network` to get a network.https://github.com/docker/swarm/blob/master/cluster/network.go#L110

2. I think `function Get` is not enough. Swarm takes many docker engines. Sometimes, same network name appears on the different nodes, while nodes has same name, too.

3. **Proposal**, we can add `func (networks Networks) GetNetworks(IDOrName string) []*Network`, to enhance the network dealing. And change `func Get`into `func GetNetwork`.

WDYT? @dongluochen  @vieux @nishanttotla @abronan
