### ISSUE TITLE
Add topology metadata information for scheduling and scaling

### ISSUE THREAD

**Issue by sebglon** [docker/classicswarm#2252]
My scenario:

I have 4 node distributed over 2 datacenter and 2 blade by datacenter.
To have an High Aviability, no bottleneck and not all container on the same datacenter or blade, i search to integer this notion on ranking

If i compare with Ceph, it use crush map to define topology.

I think, that it is interesting to open scheduler in plugin or add new schduler with topology constraint

**Comment by dongluochen** [comment]
@sebglon Thanks for the suggestion! Topology aware scheduling needs notation like Ceph crush map to define location, or simply a node label in form of 'A.B.C' to represent location like 'datacenter.row.rack'. Scheduler would take location as a ranking factor. /cc @aluzzardi for future scheduler design. 

Swarm's current approach is anti-affinity. For example, `affinity:container!=~redis*` schedule a new redis container to a node without existing redis* containers. It spreads containers to different nodes, but not aware of topology.

**Comment by sebglon** [comment]
Thansk for your reply.
How can i help you to implement this feature?

Label on swarm node can be used to identify topoogy and store them on discovering.
Label value can be in fomr of 'A.B.C'

**Comment by dongluochen** [comment]
@sebglon It'd be great if we can make a proposal first (example like #1486). On the engine side, we can reserve a `location` label to represent topology information. When a container is scheduled, it may require some notation to set it to some service group. Containers in the same service group should be distributed with HA (high availability) resilient to hardware failure. 

There are some interesting problems here. If you have 1000 machines in row A and 1 machine in row B, the machine in row B becomes very popular. It may result in a hot spot. The scheduler needs proper ranking algorithm to balance it.
