### ISSUE TITLE
[Discussion]: scheduler process filters parallelly

### ISSUE THREAD

**Issue by adohe** [docker/classicswarm#2278]
This is not a normal proposal, it's more like a discussion. As what I have talked with @dongluochen in email, I am considering processing filters parallel. Just like this:
![swarm](https://cloud.githubusercontent.com/assets/1555564/15539775/ec80f126-22b6-11e6-8c9f-2024e4408d88.png)

This doesn't mean that we will start a goroutine for each node, we still use limited goroutines, like 16. I think this can improve scheduler performance especially in larger cluster, like 500, 1000 nodes. @swarm_maintainers WDYT?

**Comment by AdoHe** [comment]
Also I just found a single stress test which will schedule 100 containers to 10 nodes, it's not that enough in my eyes.

**Comment by AdoHe** [comment]
@vieux @dongluochen @nishanttotla  ptal.

**Comment by dongluochen** [comment]
Thank you @AdoHe for the proposal. It's an interesting problem. There was previous study on the end-to-end latency delay in large clusters. See https://fast.wistia.net/embed/iframe/piy5perttw. It's not clear how much gain this change would get. If you can provide some test or simulation data, it'd be helpful.
