### ISSUE TITLE
Swarm cluster not seen by docker cli (Swarm without docker machine)

### ISSUE THREAD

**Issue by BediarSofiane** [docker/classicswarm#2279]
Hello,

I am using Docker Swarm without Docker machine (I installed it with the binary : https://github.com/docker/swarm/blob/master/CONTRIBUTING.md) 
I am creating one manager and 2 cluster nodes. The registration seems to be done correctly, but when I try to execute docker info for example on the manager it still using the local version of docker and not the swarm manager. Also, when i run containers, they are locally created and the cluster is totally transparent from docker cli.

Knowing that the content of /etc/default/docker is the following on all the 3 machines:

DOCKER_OPTS="-H tcp://10.10.0.55:2376 -H unix:///var/run/docker.sock -H tcp://10.10.0.55:2375"

2376: Is another port that i use to access docker from API
2375: Is the Swarm port (used to link cluster nodes)

So, my question is:
How can use the cluster that i created with docker cli on the manager?
I hope someone could help me.
Cordially.

**Comment by gianarb** [comment]
Hello @BediarSofiane 
Can you try to use only the master-ip please?

`docker -H tcp://<master-ip> info`

Thanks a lot

**Comment by BediarSofiane** [comment]
Hi @gianarb,
thank you for answering,

I don't know if i completely understand your answer:
By master-ip, do you mean the node on witch i started swarm (swarm manage ..)?
When I try `docker -H tcp://10.10.0.55 info` (without por) i get an error
When I try `docker -H tcp://10.10.0.55:2375 info` (without por) i get the info concerning only the local machine.

**Comment by BediarSofiane** [comment]
To make it clear, 
I am setting up the cluster, I see that the two nodes register to the manager (the node on whitch i did `swarm manage`).
next, I run `docker info` on the manager. What I expect is to have the list of nodes. what I have is the classical docker info that we get when we are not using swarm.

In the same manner. When I run a container on the manager. and i do `docker ps -a`. I don't see on witch node the container is. So the cluster is completely transparent.

**Comment by gianarb** [comment]
@BediarSofiane you are right the port is required but there is something strange on your setup.
Can you provide more information about how and where did you create this cluster?

Probably you executed a command to start the manager similar to 
```bash
$ docker run -d -p <your_selected_port>:3376 -t 
    swarm manage -H 0.0.0.0:3376 token://<cluster_id>
```
To use your local docker-cli to connect and show information from the master you must use a command like:
```bash
docker -H <master_id>:<your_selected_port> info
```
In this way if your network works fine and you can speck with the master you will receive the info about the cluster.

**Comment by BediarSofiane** [comment]
No, Here is what i did in details:
I have 3 Virtual machines on Openstack ubuntu1 (IP: 10.10.0.55), ubuntu2 (IP: 10.10.0.52), ubuntu3 (IP: 10.10.0.53) 

ubuntu1 has the following in its /etc/default/docker:
DOCKER_OPTS="-H tcp://10.10.0.55:2376 -H unix:///var/run/docker.sock -H tcp://10.10.0.55:2375"

ubuntu2 has the following in its /etc/default/docker:
DOCKER_OPTS="-H tcp://10.10.0.52:2376 -H unix:///var/run/docker.sock -H tcp://10.10.0.52:2375"

ubuntu3 has the following in its /etc/default/docker:
DOCKER_OPTS="-H tcp://10.10.0.53:2376 -H unix:///var/run/docker.sock -H tcp://10.10.0.53:2375"

1- On ubuntu1 I ran: swarm create
I got a token
2- On ubuntu2 I ran: swarm join token://<the token> --addr=10.10.0.52:2375
3-  On ubuntu2 I ran: swarm join token://<the token> --addr=10.10.0.53:2375
4- On ubuntu1 I ran: swarm manage token://<the token> --addr=10.10.0.55:2375

That's it, when I run on ubuntu1 the command `swarm list token://<the token>` I see the I addresses.
 of the two other nodes, so i suppose they are successfully registered.

Now I run `docker info`  or even `docker -H tcp://10.10.0.55:2375 info`, and the cluster still not detected.

**Comment by gianarb** [comment]
`docker -H tcp://10.10.0.55:3375 info`
Can you try on this port (3375)?

**Comment by BediarSofiane** [comment]
Do you mean 2375 because with 3375 it returns an error 
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Why specially 3375?

**Comment by gianarb** [comment]
Sorry @BediarSofiane the port is 3376.
https://docs.docker.com/swarm/plan-for-production/ "Network access control" chapter :)
