### ISSUE TITLE
How to downgrade swarm version within docker-machine?

### ISSUE THREAD

**Issue by rmelick** [docker/classicswarm#2286]
I am blocked by the private registry image problems (#2217), and need to downgrade from swarm 1.2.2 to swarm 1.2.0.  However, I did not install swarm manually, I am using docker-machine to create my cluster within AWS.  How does docker-machine/docker choose which version of swarm to use? How can I change it?

Here are the relevant versions

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.2
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   34e3da3
 Built:        Mon May  9 17:03:22 UTC 2016
 OS/Arch:      linux/amd64

$ docker-machine version
docker-machine version 0.6.0, build e27fb87

$ docker-compose version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

```

I installed docker, docker-compose, and docker-machine by running the following commands

```
sudo apt-get update
sudo apt-get -y install linux-image-extra-$(uname -r) apparmor apt-transport-https ca-certificates unzip

sudo su -
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
exit
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-get update
sudo apt-get -y install docker-engine

sudo su -  
curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine
curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
exit
```

**Comment by nishanttotla** [comment]
@rmelick #2272 should fix your issue. If you can try `1.2.3-rc1`, your pulls will work. If you wish, you can also wait for the `1.2.3` stable release tomorrow that will contain the fix.

**Comment by nishanttotla** [comment]
Also to answer your question, machine will use the latest stable release (in this case `1.2.2`) unless you specify which version to use. Do you run Swarm as a container?

**Comment by rmelick** [comment]
Thanks @nishanttotla.  I do not run swarm as a container.  I don't actually invoke swarm directly.  I create my cluster by running several `docker-machine create --driver amazonec2 --swarm` commands, then I use docker-compose to deploy to the cluster.

**Comment by nishanttotla** [comment]
@rmelick is this still an issue for you?

**Comment by rmelick** [comment]
@nishanttotla the release of 1.2.3 has fixed it, but I still would like to know what command line flag to use to specify a specific version, in case I need to downgrade again in the future.
