### ISSUE TITLE
[Question] Swarm cluster with Consul restart

### ISSUE THREAD

**Issue by allamand** [docker/classicswarm#2290]
Hello,

I have a question regarding Consul behaviour expected when it is restarted.

I have a swarm cluster with 1 master & 2 slaves, and only 1 consul.
When I restart the consul (without persistence data), then 
- Consul repopulate with swarm cluster informations
- But Consul don't get back docker networks informations (even if there are still containers using docker network overlay).

docker network ls becomes empty.

And then I get this bug : https://github.com/docker/swarm/issues/1941

My question is : Does Consul expect to retrieve all existing cluster informations from swarm cluster including networks informations ? or did I need to investigate on persistence data for consul or HA consul (this is for dev environments)

thanks

**Comment by BretFisher** [comment]
@sebmoule Is this still an issue? Did you try restarting all docker swarm containers after a loss of your consul k/v during outage? swarm may not know the information is gone from k/v storage and not know to add it back. I recommend you enable a named volume to store your consul data.
