### ISSUE TITLE
swarm manage cannot recognize swarm join

### ISSUE THREAD

**Issue by zhuyuanli** [docker/classicswarm#2301]
I have 3 nodes in a cluster,before run swarm manage,every node runs swarm join,when i stop 1 node's swarm join and join again,the swarm manage cannot recognize the node.
my discovery is zookeeper,

how can i solve this problem?

another question is when i stop swarm join,how many times can swarm manage find?

**Comment by allencloud** [comment]
@zhuyuanli 
By default, `swarm join` registers itself every 60 seconds.
It is up to the K/V store to judge the lost of nodes. Then Swarm manager watched this kind of change.
