### ISSUE TITLE
Scheduler lock with concurrency

### ISSUE THREAD

**Issue by hdanniel** [docker/classicswarm#2305]
When running nodes with a high number of images and stopped containers the creation of containers take a significant time (around 5 seconds) . This time increases when creating containers at the same time. If for example we create 5 containers at the same time, the first creation process grants a scheduler lock before the scheduler.SelectNodesForContainer function . As this function takes most of the creation time (4 seconds)  all other create process must wait the unlock to start. So, in this case the last container takes more than 20 seconds to create. 

There is a patch to remove all the scheduler https://github.com/docker/swarm/pull/2182 . Not sure if it's safe to apply it in our case.

docker version (on swarm master)
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

docker -H :4000 info (we have a high overcommit because of percentage of running containers is low vs stopped containers)

Containers: 17019
 Running: 318
 Paused: 0
 Stopped: 16701
Images: 9414
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 ip-172-21-0-51: 172.21.0.51:2375
  └ Status: Healthy
  └ Containers: 7511
  └ Reserved CPUs: 7487 / 40004
  └ Reserved Memory: 2.341 TiB / 153.1 TiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-85-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-30T16:18:17Z
  └ ServerVersion: 1.10.3
 ip-172-21-0-52: 172.21.0.52:2375
  └ Status: Healthy
  └ Containers: 9508
  └ Reserved CPUs: 9713 / 40004
  └ Reserved Memory: 3.241 TiB / 153.1 TiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-85-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-30T16:18:16Z
  └ ServerVersion: 1.10.3
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.13.0-85-generic
Operating System: linux
Architecture: amd64
CPUs: 80008
Total Memory: 306.1 TiB
Name: bf7635168b38

 uname -a
Linux ip-172-21-2-90 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by allencloud** [comment]
@hdanniel 
To be honest, I do not see necessity of adding a lock in scheduler, at least in the current design of scheduler.
While it really surprises me that you said it would take so so so much time to gain this lock.

Still hope that others can have a look at this PR #2182 
cc @docker/core-swarm-maintainers

**Comment by hdanniel** [comment]
Thanks @allencloud 

According to our tests, the slowness appear when affinity.Match(images...) is called. This takes 2-3 seconds for each node. 
Replacing images with a map , and matching the image as a key , we have reduced the time to find the image to less than 1 second. But we are still testing. 
Removing the lock will also improve our times with concurrency.

Thanks again.

**Comment by allencloud** [comment]
@hdanniel Great Job.
I think your testing report is very very valuable for Swarm's performance optimization. Hope to have to more discussion with you on this area. And just ping us on Github anytime when you need.
