### ISSUE TITLE
Consul 0.4 bug causes docker swarm manager to crash

### ISSUE THREAD

**Issue by eddytruyen** [docker/classicswarm#2316]
I installed swarm using the instructions from 

https://www.upcloud.com/support/how-to-configure-docker-swarm/

in short:

```
sudo service docker stop
sudo rm nohup.out
sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &
sleep 5
docker run -d -p 8500:8500 --name=consul progrium/consul -server -bootstrap
docker run -d -p ${MASTER_IP}:4000:4000 swarm manage -H :4000 --replication --advertise ${MASTER_IP}:4000 consul://${MASTER_IP}:8500
```

Consul Crashed

Log of container:
2 errors: 
- panic: Timeout starting MDB transaction, potential deadlock 
- WARNING: It is highly recommended to set GOMAXPROCS higher than 1

Helpful links 
- panic: https://github.com/hashicorp/consul/issues/1239
- GOMAXPROCS warning: https://groups.google.com/forum/#!msg/consul-tool/qewFEqgAoF8/b9hxhmy1v6gJ

Cause of error:
- panic: bug in consul in version 0.4; this bug is removed in version 0.6

Resolution:
- run docker consul image of version 0.6
- problem: official docker image of consul does not support versions higher than 0.4
- I used another docker image: https://hub.docker.com/r/gliderlabs/consul/
- Docker run command to start consul: The agent command must be explicitly added to docker, -data-dir option is mandatory and -client=0.0.0.0 fixes the problem that consul docker container accepts connections from localhost or OpenStack IP address:

```
docker run -d -p 8500:8500 --name=consul gliderlabs/consul:0.6  agent -server -bootstrap -data-dir=/data/consul -client=0.0.0.0 
```

**Comment by krishamoud** [comment]
[According to the site](https://docs.docker.com/swarm/discovery/) Swarm doesn't support consul versions < 0.5.1

**Comment by eddytruyen** [comment]
Ok it seems I used an outdated tutorial. I will close this issue then.

**Comment by eddytruyen** [comment]
Actually, I looked for the instructions on the site:
https://docs.docker.com/swarm/install-manual/

This also uses the progrium/consul docker image. However this docker image does not support consul versions higher than 4.0

**Comment by krishamoud** [comment]
I'm running that image right now and it's at version 0.5.2 for me.

**Comment by eddytruyen** [comment]
Then you build it from a modified Dockerfile.
The dockerfile in the dockerhub repository still uses 0.4
https://hub.docker.com/r/progrium/consul/~/dockerfile/:

```

**Comment by krishamoud** [comment]
If you run `docker run -d --name consul -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h node1 progrium/consul -server -bootstrap` you will be running 0.5.2.  To verify that, run that command and then run `docker exec -it consul consul members` and it will show you that you're using build 0.5.2.

**Comment by eddytruyen** [comment]
Ok I trust you :) 
Still that container image crashed frequently on my system
Can you please check the logs of your  consul container for `panic: Timeout starting MDB transaction, potential deadlock`?
