### ISSUE TITLE
Why can't swarm generate token in docker?

### ISSUE THREAD

**Issue by NanXiao** [docker/classicswarm#2318]
I am a novice of `swarm`, and following this [tutorial](https://blog.vpetkov.net/2015/12/07/docker-swarm-tutorial-and-examples/) to try `swarm`.
My `OS` is `RHEL 7`, and I have pulled a `swarm` image successfully. But running `swarm` in `docker` can't genereate the token:  

```
# docker run --rm swarm create
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
2016/06/02 09:26:26 Post https://discovery.hub.docker.com/v1/clusters: x509: certificate is valid for FG3K6C3A15800021, not discovery.hub.docker.com
#
```

And there are no other logs.  
Is there anything wrong? Thanks very much in advance!

**Comment by allencloud** [comment]
@NanXiao 
I tried to reproduce this, but failed. While maybe your environment and mine differ in some ways.
First, Can you provide more infos about your environment, such as `uname -a`, `docker version`, `docker info`, and anything you think is valuable.

Second, about your log, `Usage of loopback devices is strongly...` is from your docker engine's improper setting.
While `Post https://discovery.hub.docker.com/v1/clusters: x509: certificate ....`, It means that your POST failed. It can be some reasons.

**Comment by NanXiao** [comment]
@allencloud :+1: 
Thanks very much for your detailed comments! The detailed info of my host is shown:  

```
# uname -a
Linux localhost.localdomain 4.5.0 #1 SMP Thu Apr 7 20:35:17 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
# docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-common-1.9.1-40.el7.x86_64
 Go version:      go1.4.2
 Git commit:      ab77bde/1.9.1
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-common-1.9.1-40.el7.x86_64
 Go version:      go1.4.2
 Git commit:      ab77bde/1.9.1
 Built:
 OS/Arch:         linux/amd64
# docker info
Containers: 0
Images: 17
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-202764498-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.621 GB
 Data Space Total: 107.4 GB
 Data Space Available: 19.12 GB
 Metadata Space Used: 2.777 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.5.0
Operating System: Red Hat Network
CPUs: 8
Total Memory: 11.68 GiB
Name: localhost.localdomain
ID: ZUIV:BMPV:3B5R:2WBC:JXEI:2S6H:XM3H:66W5:UZQI:NJON:JY4T:HIFB
Http Proxy: ${HTTP_PROXY}
Https Proxy: ${HTTPS_PROXY}
```

After captiring the packets, I find the causes: If the IP address of `discovery.hub.docker.com` is resolved to `54.210.124.176`, then the progress will succeed, else if resolved to other IP addresses, such as `52.86.94.211`, the certification will fail. The capture file is also attached. So does it mean there are some problems in `docker DNS` part? Thanks very much!
[create_failed_swarm.zip](https://github.com/docker/swarm/files/299883/create_failed_swarm.zip)

**Comment by xiaods** [comment]
yeah, the ssl is filter by gfw

**Comment by NanXiao** [comment]
@xiaods So do you mean the gfw can screen IPs? From the capture file, I can see the TCP connection can be established from `52.86.94.211`, but the certificate is bad. Thanks!

**Comment by xiaods** [comment]
@NanXiao don't ask why on gfw issue, :-) .   You can try other Discovery backend, such as etcd,zookeeper or local file. or use proxy as alternative way. see more details #607
