### ISSUE TITLE
Swarm/Compose/Consul/Overlay networking is causing reproducible timeouts on swarm manager

### ISSUE THREAD

**Issue by dougtweedy** [docker/classicswarm#2323]
While attempting to use docker-compose with swarm manager, I can reproduce a timeout on the manager node when attempting to scale a service out by 20. 
## Configuration
- Docker Swarm Cluster (using docker-compose for scale)
- Docker Container Overlay Network 
- Consul Backed Cluster
- Docker Engine v1.11.2, build b9f10c9
- Docker-compose v1.7.1, build 6c29830
- Docker swarm v1.2.3 (Build date on image was 7 days ago) 
- 6 nodes total (+1 for swarm manager)
- Swarm Nodes are Debian 8 w/ 4.5 kernel + Overlay FS Storage Driver
  -- I've also tried Debian 7 w/ 3.16 + aufs fs storage driver
- Hardware: 2vCPU/7.5G RAM/50 GB SSD 
- Each node is configured with cluster-store pointed at consul master
- Image size of service is 434.5 MB 
## Problem Description

When attempting to run _docker-compose scale service=20_ I regularly and reproducible see the error, 

> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

Based on hardware metrics, I don't see issues with CPU/Memory/Disk and network load does not seem to be an issue. Some of the behavior seems similar to #1752 and #1750.

Any help or direction would be appreciated

**Comment by allencloud** [comment]
@dougtweedy 
Thanks for your feedback.
Can you `Retry with --verbose to obtain debug information.` And this will output the compose debug log.
Then can you provide more debug log about Swarm?

**Comment by dougtweedy** [comment]
@allencloud 
Thanks, below is attempting to spin up more containers in the environment. I have redacted some of the more private information. 

I should also mention, I typically see this behavior occur the most when containers are already running in the env. Typically if its a 'fresh' env, it's not as guaranteed to fail.


[dockercompose.txt](https://github.com/docker/swarm/files/301297/dockercompose.txt)

**Comment by Z3r0Sum** [comment]
@dougtweedy I'm seeing the same problem with 12 nodes - I am unable to create and overlay network and get timeouts when creating containers trying to use a custom network.

**Comment by dougtweedy** [comment]
@Z3r0Sum So you see the issue when creating the overlay, as in, you issue the **docker network create overlay** command and see the manager hang?

**Comment by Z3r0Sum** [comment]
@dougtweedy Correct.  I was only able to resolve my problem by completing redoing everything - data nodes, service discovery, and swarm managers.

**Comment by dougtweedy** [comment]
@Z3r0Sum I have seen this behavior as well, typically it only occurred to me if I was trying to create the overlay driver after an unsuccessful attempt to do so. I should clarify, that issue is different than the one described above. The above description applies to placing service containers into the swarm network with an overlay driver already available to all nodes.

Just some more observations, I have seen the occurrences of this drop and I haven't changed any configurations or settings. However, when I saw this issue occur a lot there were some hosts listed under consul's 'members' output that had 'left' the cluster due to me shutting them down. Based on some log data, it seemed as if some of the clients and servers were still attempting to contact them. Now that all the members in the output are all truly active, I haven't seen this issue come up again.

**Comment by samginshen** [comment]
I meet same problem.  Docker-compose up 65 containers, 23 containers can not start because this error

**Comment by alexellisadp** [comment]
I'm getting a similar issue with network timeouts, this was working OK with 1.11 but after an upgrade to Docker 1.12.1 I'm facing issues. The --verbose output was not very interesting - it mainly said "timeout creating overlay network". Can I increase the timeout?

**Comment by alexellis** [comment]
I'm getting a similar issue with network timeouts, this was working OK with 1.11 but after an upgrade to Docker 1.12.1 I'm facing issues. The --verbose output was not very interesting - it mainly said "timeout creating overlay network". Can I increase the timeout?
