### ISSUE TITLE
Docker swarm manager cannot recognize swarm nodes

### ISSUE THREAD

**Issue by sj82516** [docker/classicswarm#2341]
I follow these steps to create Docker swarm cluster.
create Cunsol

<pre><code>
$ docker-machine create -d virtualbox mh-keystore  
$ eval "$(docker-machine env mh-keystore)"  
$ docker run -d \  
-p "8500:8500" \  
-h "consul" \  
progrium/consul -server -bootstrap  
</code></pre>

create swarm manager
<pre><code>
$ docker-machine create -d virtualbox node1
$ docker run -d -p 4000:4000 swarm manage -H :4000 --replication -- advertise $(docker-machine ip node1):4000 consul://$(docker-machine ip mh-keystore):8500
</pre></code>
create swarm node
<pre><code>
$ docker-machine create -d virtualbox node2
$ docker run -d swarm join --advertise=$(docker-machine ip node2):2375 consul://$(docker-machine ip mh-keystore):8500
</pre></code>
login node1
<pre><code>
$ docker-machine ssh node1
$ docker -H :4000 info
But this instruction output
</pre></code>

(unknown): 192.168.99.106:2375(node2 ip)
└ ID:
└ Status: Pending
└ Containers: 0
└ Reserved CPUs: 0 / 0
└ Reserved Memory: 0 B / 0 B
└ Labels:
└ Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?....
How can I fix this ?
I have already check node2 and it run well.

[Update] I follow this page and it works well. But I still wan't to know how set up swarm cluster without docker-machine. 

[Update] Another approach
<pre><code>
docker-machine create -d virtualbox \
    --swarm \
    --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-advertise=eth1:2376" \
  mhs-demo1
</pre></code>
Node1 docker info appear mhs-demo1 ip but info still unknown..

**Comment by dongluochen** [comment]
Following is the error. You need to fix Docker set up on the node2 so that `docker -H 192.168.99.106:2375 info` (likely with TLS) works **from manager**. 

```
Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by sj82516** [comment]
How to do that?   
I can use 'docker-machine ssh node2 ' to login and 'docker run hello-world' everything fine.  
But when I type 'docker -H 192.168.99.106:2375 info' , it's  still wrong.

**Comment by sj82516** [comment]
By the way, I cannot use 'docker -H ' to approach all my local virtual machine . 
However , eval $(docker-machine env [NODE]) is fine.

**Comment by sj82516** [comment]
when I type `eval $(docker-machine env --swarm node1)`  
It show 

> Error checking TLS connection: "node1" is not a swarm master. The --swarm flag is intended for use with swarm masters  

Does this cause error ? Why using swarm manager instruction to set up is not swarm master?  
It's so strange. How can I get the same result as 
`docker-machine create \
-d virtualbox \
--swarm --swarm-master \
--swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
--engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
--engine-opt="cluster-advertise=eth1:2376" \
mhs-demo0` using swarm instruction?  

I want to use swarm instruction because I don't want to declare swarm master when I create it.

**Comment by marcellodesales** [comment]
With the new Docker Swarm Manager on 1.12, this seems to be solved... The command `docker node ls` works properly on the `docker for mac` version, using swarm and multiple managers. The link https://docs.docker.com/engine/swarm/swarm-tutorial contains details around those commands.

* Create the machines

```
$ docker-machine create --driver virtualbox manager1
$ docker-machine create --driver virtualbox manager2
$ docker-machine create --driver virtualbox worker1
$ docker-machine create --driver virtualbox worker2
$ docker-machine create --driver virtualbox worker3
Running pre-create checks...
Creating machine...
(worker2) Copying /Users/mdesales/.docker/machine/cache/boot2docker.iso to /Users/mdesales/.docker/machine/machines/worker2/boot2docker.iso...
(worker2) Creating VirtualBox VM...
(worker2) Creating SSH key...
(worker2) Starting the VM...
(worker2) Check network to re-create if needed...
(worker2) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env MACHINE_NAME
```

The output is similar to all the machines where `MACHINE_NAME` is the name of the host.

* List of Docker Machines

```
$ eval $(docker-machine env manager1)
$ docker-machine ls
NAME            ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
manager1        *        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.0-rc2
manager2        -        virtualbox   Running   tcp://192.168.99.101:2376           v1.12.0-rc2
worker1         -        virtualbox   Running   tcp://192.168.99.104:2376           v1.12.0-rc2
worker2         -        virtualbox   Running   tcp://192.168.99.103:2376           v1.12.0-rc2
worker3         -        virtualbox   Running   tcp://192.168.99.105:2376           v1.12.0-rc2
```

* Initialize a swarm and listen to the port number

```
$ docker swarm init --listen-addr=192.168.99.100:2377
Swarm initialized: current node (eh6fzcu4kutetpjfwqpro6hpp) is now a manager.
```

* Join a host to the swarm. Make sure to use the `IP:HOST` of the manager with the RC2 version.

```
$ eval $(docker-machine env worker1)
$ docker swarm join 192.168.99.100:2377
This node joined a Swarm as a worker.
$ docker node ls
ID                           NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
6sswuicxzym21sbpuk7oa5ghi    worker1   Accepted    Ready   Active
eh6fzcu4kutetpjfwqpro6hpp *  manager1  Accepted    Ready   Active        Leader
```

* Join more machines

```
$ eval $(docker-machine env worker2)
$ docker swarm join 192.168.99.100:2377
This node joined a Swarm as a worker.

$ docker node ls
ID                           NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
6sswuicxzym21sbpuk7oa5ghi    worker1   Accepted    Ready   Active
eh6fzcu4kutetpjfwqpro6hpp *  manager1  Accepted    Ready   Active        Leader
ekhlufeucy7a0iu56ugyxmf7g    worker2   Accepted    Ready   Active

$ eval $(docker-machine env worker3)
$ docker swarm join 192.168.99.100:2377
This node joined a Swarm as a worker.

$ docker node ls
ID                           NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
5y1mbos75ehl6uiqwbxvv81iy    worker3   Accepted    Ready   Active
6sswuicxzym21sbpuk7oa5ghi    worker1   Accepted    Ready   Active
eh6fzcu4kutetpjfwqpro6hpp *  manager1  Accepted    Ready   Active        Leader
ekhlufeucy7a0iu56ugyxmf7g    worker2   Accepted    Ready   Active
```

* If you need to re-init the cluster, just force it

```
$ docker swarm init --force-new-cluster
Swarm initialized: current node (eh6fzcu4kutetpjfwqpro6hpp) is now a manager.
```

* Add more managers into the cluster. Make sure to expose the listen-address port as well as the initial manager's ip address.

```
$ docker swarm join --listen-addr=192.168.99.101:2377 --manager 192.168.99.100:2377
Error response from daemon: Your node is in the process of joining the cluster but needs to be accepted by existing cluster member.
To accept this node into cluster run "docker node accept 1alymaz2mea6qu63k01ui0aiy" in an existing cluster manager. Use "docker info" command to see the current Swarm status of your node.
```

* As the warning says, just accept the manager2 to join manager1

```
$ eval $(docker-machine env manager1)
$ docker node accept 1alymaz2mea6qu63k01ui0aiy
Node 1alymaz2mea6qu63k01ui0aiy accepted in the swarm.
```

* Use the new `docker node ls` to list of nodes in the swarm.

```
$ docker node ls
ID                         NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
1alymaz2mea6qu63k01ui0aiy  manager2  Accepted    Ready   Active        Reachable
5y1mbos75ehl6uiqwbxvv81iy  worker3   Accepted    Ready   Active
6sswuicxzym21sbpuk7oa5ghi  worker1   Accepted    Ready   Active
78h0r2r70cuufh49j8562kb32  worker1   Accepted    Down    Active
9u1rnn0y9epnbdavz3p2zltq3  manager2  Accepted    Down    Active
eh6fzcu4kutetpjfwqpro6hpp  manager1  Accepted    Ready   Active        Leader
ekhlufeucy7a0iu56ugyxmf7g  worker2   Accepted    Ready   Active
```

Cheers! 🍺

**Comment by marcusmyers** [comment]
Swarm mode doesn't work though if you are trying to balance you docker image build processes across the swarm.  Swarm mode works well when deploying an application for production or staging, but not in my case for load balancing of workers for CI build process.  I get the same error as above just building a new swarm master using `docker-machine`.

```
Nodes: 1
(unknown): X.X.X.X:2375
└ ID:
└ Status: Pending
└ Containers: 0
└ Reserved CPUs: 0 / 0
└ Reserved Memory: 0 B / 0 B
└ Labels:
└ Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?....
```

**Comment by dongluochen** [comment]
The doc  https://docs.docker.com/swarm/install-w-machine/ is broken. I'm fixing it in https://github.com/docker/swarm/pull/2442.
