### ISSUE TITLE
Configuring Swarm masters for HA across multiple datacenters with Consul

### ISSUE THREAD

**Issue by bennetimo** [docker/classicswarm#2377]
I have a question about swarm HA setup across multiple datacentres. 

From the swarm docs [here](https://docs.docker.com/swarm/plan-for-production/):

> The diagram below shows a Swarm cluster configured for HA. It has three Swarm managers and three discovery service instances spread over three failure domains (availability zones). It also has Swarm nodes balanced across all three failure domains

![Swarm HA](http://farm2.staticflickr.com/1675/24380252320_999687d2bb_b.jpg)

I would like to achieve an architecture similar to the above with Consul as the backing discovery service. I have configured Consul for multi-datacenters, as per their [guide](https://www.consul.io/docs/guides/datacenters.html).

So I have two data centres, DC1 and DC2, with Consul servers in each. Each DC is connected together across the wan via a leader, similar to:

![Consul Architecture](https://www.consul.io/assets/images/consul-arch-5d4e3623.png)

Now I would like to create a swarm cluster that spans both as the swarm diagram would suggest is possible, but have not been able to because:
1. The KV stores in disparate data centers [are not replicated](https://www.consul.io/docs/agent/http/kv.html). 
   
   > It is important to note that each datacenter has its own KV store, and there is no built-in replication between datacenters. If you are interested in replication between datacenters, look at the [Consul Replicate project](https://github.com/hashicorp/consul-replicate)
   
   This means the swarm masters in each data-center are not aware of each other, and both operate independently with their own pool of nodes from their own DC.
2. Using the consul-replicate deamon to try to sync the DCs does not work and seems to result in an inconsistent state between the two DCs. This is because the `docker/swarm/leader` key that swarm uses to register the current leader is session locked and cannot be replicated. And because replicating the node entries from e.g. DCB to DCA under `docker/swarm/nodes` results in all the B nodes being lost in favour of those in A (instead of A+B).

So my question is, is Swarm HA with multiple swarm masters (primary plus replicas across DCs) supported when using Consul and multi-datacenter setup? And if so, how do I set it up/what am I missing?

Thanks!

**Comment by gbolo** [comment]
This is exactly the issue I would like to solve. Any updates on this?

**Comment by sandeepone** [comment]
Any updates on latest Docker 1.13 ??

**Comment by wannaknowmo** [comment]
any news?

**Comment by rjrhaverkamp** [comment]
We would like to run Docker in a production environment and management requires us to run a dual datacenter setup. Is there any news or solution on this?

- Rob Haverkamp

**Comment by tkeeler33** [comment]
Definitely need this use case!

**Comment by rjrhaverkamp** [comment]
We switched to Google Container Engine in combination with Kubernetes because of this. The kubernetes community is more active with feedback and developments than the swarm community. Or so it feels.

**Comment by Emersonyh** [comment]
That setup is exactly what we are using, and working so far.

https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-placement-preferences-placement-pref

This may help you

**Comment by Vinno97** [comment]
I'm sorry for reviving such an old thread, but @Emersonyh how did you manage to keep your latency low while using containers spread across multiple datacenters? As far as I know the placement preference has no effect on the internal load balancing that docker does on overlay networks. Docker "randomly" chooses a target container when making internal calls like database queries.
Is there a way that you make sure queries from one datacenter are preferably routed to a database in that same datacenter?

**Comment by cbrunnkvist** [comment]
Idea: just name your services e.g. `${DC}-memcached` and tune your application configs to look for the local services in a corresponding fashion?
