### ISSUE TITLE
Current recommendation: What to use docker-swarm (this) or the 1.12 docker swarm (swarmkit)?

### ISSUE THREAD

**Issue by niieani** [docker/classicswarm#2379]
The announcement of the native swarm capability for docker came together with 1.12, but nowhere was is explained when to use which -- or whether this project will be deprecated. The docs aren't helpful either. Can somebody clarify this?

**Comment by maguowei** [comment]
#2353 Need some official explanation！

**Comment by codablock** [comment]
This also opens a lot of questions for us and we are currently quite unhappy that there is no information available about the future of Swarm/Swarm-Mode. It was already a nice surprise when we figured out that these are two completely different pieces of software/concepts and only share the targeted problem and name...we expected something completely different.

What is the future of docker-swarm? Will it be maintained in the future? Will it be kept compatible to new Docker API versions?

The problem currently is, that the Docker Swarm Mode is not production ready at the moment and thus not an option and I don't believe it will be ready until 1.13. And the future of docker-swarm is unclear, so it is only an option with a very bad gut feeling. Currently we really don't know what to do.

**Comment by dongluochen** [comment]
Sorry for some delay on repsonding. We updated [README](https://github.com/docker/swarm/blob/master/README.md) to clarify the 2 projects. See changes in #2403.

**Comment by dvenza** [comment]
What about new developments and features on standalone Swarm?
Is standalone Swarm going to be in maintenance mode: bug fixes, but no new features?

Also, I am unable to find documentation on swarmkit API.
We developed on top of Swarm API (with its quirks to fit swarm through the docker remote API). It seems quite obvious to me that sooner or later we will have to switch to swarmkit. Are the APIs 100% compatible? What about the various language bindings, like docker-py? Are they swarmkit ready?
