### ISSUE TITLE
Why can't create a docker on a different node if using "--volumes-from" 

### ISSUE THREAD

**Issue by wzymaster** [docker/classicswarm#2381]
I am getting error like below : 

```
root@great-lakes:~/.env# docker run -d --name consumer4 --volumes-from=40681b744b2 -e constraint:storage!=disk  ubuntu  /bin/sh -c "while true; do ping 8.8.8.8; done"
docker: Error response from daemon: Unable to find a node that satisfies the following conditions
[--volumes-from=40681b744b2]
[storage!=disk].
```

Given an existing docker `40681b744b2` on node with "constraints:storage=disk", but I want to create a new  docker on another node with   "constraints:storage!=disk". 

I don't understand why Swarm restricts this feature and function here ?

**Comment by cpuguy83** [comment]
@wzymaster `--volumes-from` requires the containers to be co-scheduled. Since `40681b744b2` is on a node with `storage=disk` and you are trying to create a container on a node where `storage!=disk`, they cannot be co-scheduled.

It would be better to use named volumes rather than rely on `--volumes-from` since named volumes do not have this requirement (though you must ensure the volume is a multi-host capable).

**Comment by wzymaster** [comment]
How can I use named volumes ? you mean that I can create multiple names volumes on node B, and then containers on node A can use those volumes ? any examples ?

**Comment by cpuguy83** [comment]
```bashtext
$ docker volume create --name important_data --driver rexray
$ docker run -v important_data:/mydata ...
```

This would create a volume using the rexray driver (which would normally be used with multi-host storage), then create a container with the volume you just created.

**Comment by wzymaster** [comment]
thanks for your quick reply ! 
Can I create a volume tied to a specific folder on the system ?

**Comment by cpuguy83** [comment]
@wzymaster This is considered a bind mount, not a volume.
There is a volume driver that will allow you to do this, but in the end it's no different than `-v /host/path:/container/path`, and in such cases you'd either need to have this path populated on every node or schedule always to the same node.

**Comment by wzymaster** [comment]
what I mean that `device=/dev/sda2` can be a specific folder in the below command ?

```
docker volume create --driver local --opt type=btrfs --opt device=/dev/sda2
```

**Comment by cpuguy83** [comment]
Yes, but you'll need to make sure that /dev/sda2 is available on every node (and pointing to the same block device).
