### ISSUE TITLE
Swarm says about connectivity error with one of the nodes, but doesn't which node 

### ISSUE THREAD

**Issue by garagatyi** [docker/classicswarm#2393]
Sometimes we see outages of docker daemon on some nodes. When our docker API client tried to build image over swarm it responded with response code 500 and message:
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

This message doesn't help to indicate which node is unavailable.
Please add some useful information about node to that error response.

**Comment by garagatyi** [comment]
I'm OK with the message. Please clarify will that work with swarm controlled by 3d party client instead of docker CLI?

**Comment by jinuxstyle** [comment]
It works for any client which uses engine-api no matter it is 3d party client or docker CLI.
