### ISSUE TITLE
Update doesn't work correctly in swarm

### ISSUE THREAD

**Issue by tomwis** [docker/classicswarm#2397]
In swarm when we use run command with cpu-shares then it is treated as number of cores and its values is translated to correct relative weight, for example:

`docker run -it --cpu-shares="1" ubuntu bash`

Then in inspect we will see (if machine has 4 cores):
`"CpuShares": 256`

However, if we do the same in update:

`docker update --cpu-shares="2" container_id`

Then in inspect we will see 2 instead of 512:
`"CpuShares": 2`

So swarm doesn't treat cpu-shares in update as cores like it does with run.

Additionaly, if we try to remove cpu-shares (set it to 0) with update then nothing happens and previous value is preserved:

`docker update --cpu-shares="0" container_id`
`docker inspect container_id | grep pu`
`"CpuShares": 2`

I assume update should work the same as run? Are you aware of this behaviour?

Swarm v. 1.2.3

**Comment by xianlubird** [comment]
Docker engine don't allow to set `cpu_share=0` when updating container. If using docker engine to update container set `cpu_share=0` , it will do nothing. Does it will change this behaviour ? @nishanttotla

**Comment by xiaods** [comment]
The minimum allowed cpu-shares is 2. so need clarify the docker version and swarm version. thanks a lot.
