### ISSUE TITLE
Move to docker engine API pulling of image on container creation

### ISSUE THREAD

**Issue by garagatyi** [docker/classicswarm#2402]
Now Swarm pulls image if it doesn't exist on node on container creation. 
I think it has some problems:
- it is not possible to see logs of pulling since container creation API doesn't provide logs streaming
- swarm behavior is not aligned with docker in that case whereas it is mostly consistent in many other cases
- clients connected over TCP with set connection read timeout suffer from disconnections due to that timeout on slow networks/big images because there is no output while Swarm pulls image

This behavior was mentioned as an improvement by @aluzzardi [here](https://github.com/docker/swarm/pull/1350#issuecomment-152112163).

Is it possible to move that to docker engine API(maybe as optional, dependent on query params)?

**Comment by xianlubird** [comment]
Docker client does not set timeout when calling `create container` API, why it will timeout ?

**Comment by garagatyi** [comment]
Because I'm using other client which sets timeout.

**Comment by ezrasilvera** [comment]
@garagatyi this was done to optimize "docker run" which sends a pull in case the image is not found. On swarm the problem is that when you are back on the client you no longer know which node failed the operation and need to pull the image, so your only choice is to explicitly pull on all nodes which is waste of effort.

**Comment by garagatyi** [comment]
I understand how it works and why it is done in such a way, but thanks for your efforts. But probably it doesn't make sense to request anything now when docker swarm mode is replacing standalone swarm.
