### ISSUE TITLE
How to mount volumes to global volume in Docker Swarm and bundle

### ISSUE THREAD

**Issue by RotemEmergi** [docker/classicswarm#2419]
I am using Docker 1.12 and Compose 1.8. I am trying to understand how to mount the volumes for an image to global volumes.

The purpose is to use Docker services and Docker bundle for deploying clusters.

This is the error that I get:

WARNING: Unsupported top level key 'volumes' - ignoring

WARNING: Unsupported key 'volumes' in services.momgodb - ignoring

**Comment by ChristianKniep** [comment]
I guess the easy answer is, that Application Bundle is not yet feature complete in regards to what `docker-compose` is able to do.
Which is similar to how compose started back in the days. Some day (I have a candle burning for that) it will provide all the bells and whistles a `docker-compose` file can declare.

To be more precise: Application bundle will implement everything that `docker service create` offers you and `docker service create` hopefully allows everything that `docker-compose up` allows you to do.
