### ISSUE TITLE
Differentiate between memory limit and reservation

### ISSUE THREAD

**Issue by schmunk42** [docker/classicswarm#2421]
according to https://github.com/docker/swarm/issues/1399#issuecomment-178135330

> It's both: -m to indicate the memory limit to Docker, which Swarm also uses to reserve the corresponding amount of space.

Swarm also **reserves** the memory defined in `mem_limit` which brings problems, when running stacks in a swarm. 

There are a few processes/requests in my container which may need, let's say, 256 MB memory, but 90% of the time my container runs with less than 25 MB.

So I'd like to set something like:

```
  mem_limit: 256M
  mem_reservation: 25M
```

Currently I have to remove the limit completely, because otherwise too much resources are allocated and I can run only 10 stacks, while the swarm is actually powerful enough to run 100 stacks.

**Comment by jeffbaier** [comment]
As a workaround I am using the swarm.overcommit cluster option parameter. You pass this to the swarm agent on startup. This isn't ideal, but is good enough until they improve memory reservation vs memory limit settings. The following sets overcommit to 50%.

swarm manage --cluster-opt swarm.overcommit=0.50 [...]

**Comment by schmunk42** [comment]
Looks pretty related: http://blog.runnable.com/post/147970274996/cost-efficient-container-scheduling-with-docker

**Comment by sepich** [comment]
This works as desired in `docker-ce 17.11.0~ce-0~debian`.
I can start 20 containers on swarm node with 8Gb RAM having: 
```
resources:
  limits:
    memory: 1g
```
but they are only partially started with:
```
resources:
  reservations:
    memory: 1g
```
And there is valid state:
```
$ docker service ps --no-trunc stack_service
ID                          NAME              IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR                                                   PORTS
4xvkpptch095qhf5122yqwtir   stack_service.1   image:latest                       Running             Pending 25 minutes ago   "no suitable node (insufficient resources on 1 node)"
```

**Comment by jmarcos-cano** [comment]
Not to sound like ads, but if anyone finds it useful ill leave it here:

[docker-swarm-stacks-resources-limit](https://medium.com/@jmarcos.cano/docker-swarm-stacks-resources-limit-f447ee74cb62)
