### ISSUE TITLE
High Availability for Docker Swarm Managers using consul

### ISSUE THREAD

**Issue by ghost** [docker/classicswarm#2440]
Hi
i am new on docker swarm and want to understand its architecture for HA setup. I went through [this](https://docs.docker.com/swarm/multi-manager-setup/) guide which explains how to setup multiple swarm managers for HA setup. But i am confused that what if consul server itself goes down. What will happen in this case? OR What could be the best plan to setup HA environment for Swarm managers?
Thanks

**Comment by arthurtsang** [comment]
you can setup consul in ha mode.  and you can have multiple swarm managers, i use a dns to load balance between them.

**Comment by 14msitaqadeer** [comment]
@arthurtsang Thanks for your response, i used [this](https://hub.docker.com/r/progrium/consul/) guide to install consul in an HA environment. But this did not work for me well. As i mentioned em a student and new on docker, could u please help me on that and share a guide how to achieve this deployment model:
Node1=Docker Swarm Manager+Consul
Node2=Docker Swarm Manager+Consul
Node3=Docker Swarm Manager+Consul
Node4=Docker Swarm Agent
If one of the above manager/consul goes down, discovery service as well as manager service does not stop.
Thanks

**Comment by m0ta** [comment]
@14msitaqadeer I'm not entirely familiar with your model but I have similar setting and what I'd do is this: first you create a consul cluster. So perhaps your Node1 consul could be your consul cluster leader. You'd run a consul container on Node1. Then for Node2 and 3, you'd run a consul container that would **join** Node 1 consul using IP address. Make sure that the consul cluster works first.

After that, in any of the nodes, let's say Node1, you run a swarm manager container. The swarm managers in other two nodes, from what I know, could run in secondary mode to the manager in Node1. For Node4, just join the agent to swarm manager in Node1.

If it works, you'll be able to run container in all nodes through any of the swarm manager. Took me a long while to figure out. Hope this helps.

**Comment by arslanqadeer** [comment]
Hi,
Thanks for commenting on this, well i have already given this a try using [this](https://hub.docker.com/r/progrium/consul/) guide, but even consul cluster did not work for me. Somehow i have to achieve this model. I'll get in touch with u whenever i get some time.

**Comment by xiaods** [comment]
anyone experience with consul cluster. it think it will not difficult with the expect.

**Comment by pascalandy** [comment]
Might help! http://blog.wescale.fr/2017/01/04/tutoriel-infastructure-resiliente-et-scalable-avec-swarm-consul-et-traefik/#comments
