### ISSUE TITLE
containerslots configuration is ignored

### ISSUE THREAD

**Issue by groyee** [docker/classicswarm#2464]
Please see the image. This is an output from my **_docker info_** command on the swarm master.

<img width="939" alt="screen shot 2016-08-24 at 9 15 10 pm" src="https://cloud.githubusercontent.com/assets/194016/17942503/4f4a789c-6a40-11e6-8029-ce3d78736c14.png">

Containers were started by remote API call to the swarm master:

/api/containers/7809e51bb1f7da22134bf4688d9fca2592238c58055be872f38f12457261125d/scale

**Comment by dongluochen** [comment]
@groyee Did you create the containers before you apply label `containerslots=4`? `containerslots` take effect at container create, not start. How did you create the containers?  

Also can you provide output on `docker -H 192.168.0.22:2376 ps`? Can you add another container to 192.168.0.22:2376 with `docker -H master:managerport run -e constraint:node==categorization2 #image#`.

**Comment by groyee** [comment]
Hi,

This is how I created the node:

**_### docker-machine create -d azure --azure-location westeurope --azure-resource-group coralogix-resource-group --azure-availability-set categorization-availability-set  --engine-label machinerole=categorization  --engine-label containerslots=4  --engine-label machinetype=D  --azure-image Canonical:UbuntuServer:16.04.0-LTS:latest  --azure-use-private-ip  --azure-size Standard_F2  --azure-subscription-id $AZURE_SUBSCRIPTION_ID  --swarm --swarm-discovery="consul://$(docker-machine ip kvstore):8500" --engine-opt="cluster-store=consul://$(docker-machine ip kvstore):8500" --engine-opt="cluster-advertise=eth0:2376" categorization2_**

These are the results from what you asked:

<img width="1328" alt="screen shot 2016-08-25 at 3 48 54 am" src="https://cloud.githubusercontent.com/assets/194016/17953072/d8728c08-6a78-11e6-813a-15dbeaa98e68.png">


So, if I run the container using docker CLI it does work. But with remote API it doesn't work.

**Comment by dongluochen** [comment]
How did you create containers from groyee/categorization using API? Can you try to create one more on this node thru swarm API?

**Comment by groyee** [comment]
I am using Shipyard. It uses docker remote API. I guess I can download the source code and take a look. Do you think this is a Shipyard issue?

Thanks.

**Comment by dongluochen** [comment]
I don't know about Shipyard. Can you use it to add another container? Swarm might exclude the container which runs `swarm join` so it could be off by 1. Give it a test.

**Comment by groyee** [comment]
I will give it a try.

**Comment by nishanttotla** [comment]
@groyee did it work out eventually?

**Comment by lenestopage** [comment]
I'm seeing a similar issue with a customer in which it seems the containerslots label is ignored. 

Supposedly, a node can tell the scheduler the max number of containers to run on it using the "containerslots" label. 

[root@soln-xxx ~]# cat /etc/docker/daemon.json 
{ 
"labels": [ 
"containerslots=16", 
"com.x.orca.cpu.cores=16", 
"com.x.orca.memory=32", 
"com.x.orca.disk=slow" 
], 
"storage-driver": "devicemapper", 
"storage-opts": [ 
"dm.thinpooldev=/dev/mapper/centos-thinpool", 
"dm.use_deferred_removal=true" 
] 
} 

After we schedule about 10 containers, trying to run anything else is consistently giving us this API error: 

APIError: 500 Server Error: Internal Server Error for url: https://ucp-dev.x.com:443/v1.25/networks/create ("Error response from daemon: Unable to find a node that satisfies the following conditions 
[available container slots]

Should I piggyback off of this, or create a new issue?
