### ISSUE TITLE
Progress during pulling image

### ISSUE THREAD

**Issue by AtomicBit** [docker/classicswarm#2479]
Hello, when I am pulling image onto one docker host I have progress where I see which layer is downloading/extracting etc.
When I am connected to the swarm I see just
`node: Pulling <image>...`
Is it possible to have more verbose progress? because when I am downloading big images I am not sure if it is working or not (many times it wasnt working).

**Comment by nishanttotla** [comment]
@AtomicBit thanks for creating the issue. This is possible to do, and we chose to have simpler behavior as of now. I'm not sure how having a full progress report will affect network traffic, but IIRC we already have access to the reader that reports progress, so perhaps it's just a matter of showing that. I'll look it up.
