### ISSUE TITLE
It happens TLS handshake timeout when pull swarm image from Docker Hub 

### ISSUE THREAD

**Issue by yuexiao-wang** [docker/classicswarm#2487]
It happens TLS handshake timeout when pull swarm image from Docker Hub by using "docker run swarm --help" as follows:

$ docker run swarm --help
Unable to find image 'swarm:latest' locally
latest: Pulling from library/swarm
220609e0bc51: Pulling fs layer 
b54bf338fe2f: Downloading [=====>                                             ] 16.38 kB/155.4 kB
d53aac5750d5: Download complete 
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/94/942fd5fd357e2fe2fcecbaf3dd77c313f22ce18a84a5a4d288c0df407a61e623/data?Expires=1474343453&Signature=ah5GtZnJaLJVDlHjj7rdFdluISrAhHEKOykuIDvZj3jb6hD3xckSNQdiYFPLeI4KfrLnIAUCqhznjA2e-DoHi3faXxyWxnjVoedfZI08If0IP52r-tts~xDf5avhL9BGHAtXiyap07x26aI2jOxVOYWVfICm-zq8IxgJEwghdrg_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: EOF.
See 'docker run --help'.

However, It works fine by using "docker pull swarm"  as follows:

$ docker pull swarm
Using default tag: latest
latest: Pulling from library/swarm
220609e0bc51: Pull complete 
b54bf338fe2f: Pull complete 
d53aac5750d5: Pull complete 
Digest: sha256:c9e1b4d4e399946c0542accf30f9a73500d6b0b075e152ed1c792214d3509d70
Status: Downloaded newer image for swarm:latest
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
swarm               latest              942fd5fd357e        4 weeks ago         19.47 MB
ubuntu              latest              97434d46f197        6 months ago        188 MB

**Comment by michelvocks** [comment]
I'm unable to reproduce this issue. This might also be more related to docker daemon than to swarm.

```sh
michel@homebox ~/go/src/github.com/docker/swarm $ docker run swarm --help
Unable to find image 'swarm:latest' locally
latest: Pulling from library/swarm
220609e0bc51: Pull complete 
b54bf338fe2f: Pull complete 
d53aac5750d5: Pull complete 
Digest: sha256:c9e1b4d4e399946c0542accf30f9a73500d6b0b075e152ed1c792214d3509d70
Status: Downloaded newer image for swarm:latest
Usage: swarm [OPTIONS] COMMAND [arg...]

A Docker-native clustering system

Version: 1.2.5 (27968ed)

Options:
  --debug			debug mode [$DEBUG]
  --log-level, -l "info"	Log level (options: debug, info, warn, error, fatal, panic)
  --experimental		enable experimental features
  --help, -h			show help
  --version, -v			print the version
  
Commands:
  create, c	Create a cluster
  list, l	List nodes in a cluster
  manage, m	Manage a docker cluster
  join, j	Join a docker cluster
  help		Shows a list of commands or help for one command
  
Run 'swarm COMMAND --help' for more information on a command.
```
