### ISSUE TITLE
Feature request for a "greedy" container label

### ISSUE THREAD

**Issue by mikedickey** [docker/classicswarm#2504]
As user of Docker Swarm/UCP, I would like to be able to add a special “greedy" container label that impacts scheduling in the following ways:
- The scheduler will only consider nodes to be eligible to run containers that have this greedy container label if there are no other containers currently running on them (other than the swarm management containers).
- The scheduler will not allow any other containers to run on a node that has an active container running on it with the greedy container label

For example, let us define the named used for the greedy container label to be “com.docker.swarm.greedy”. When I run the following command, it will trigger this special scheduling behavior:

`docker run --rm --name greedy1 --label com.docker.swarm.greedy=true some-image`

If have 3 nodes:
- Node a: has 2 containers running
- Node b: has 0 containers running (excluding swarm management)
- Node c: has 1 container running

The scheduler will consider “Node b” to be the only node eligible for greedy1, and run the container on Node b.

If I then run a similar command:

`docker run --rm --name greedy2 --label com.docker.swarm.greedy=true some-image`

The scheduler will find no eligible nodes for greedy2 and return an error.

If I were instead to run:

`docker run --rm --name not-greedy some-image`

The scheduler would consider Node b to be ineligible, and run not-greedy on either Node a or Node c.

Note that once greedy1 has finished running, Node b should again be eligible to run either not-greedy or greedy2.

**Comment by michelvocks** [comment]
This can be solved with an anti-affinity: `affinity:greedy!=true`
If you start all your containers with this affinity then no other container will be started on this node.
You have to run "greedy" containers with the specific label (e.g. `docker run --label greedy=true nginx`)

**Comment by mikedickey** [comment]
@michelvocks the problem with that approach is you would need a way to guarantee that everyone using your cluster will only create containers with the label "affinity:greedy!=true". In our case, this is too big of an assumption.

**Comment by michelvocks** [comment]
@mikedickey I think this is really specific. But feel free to create a pull request if you want to implement it. :-)
