### ISSUE TITLE
NetworkResource structure change causing test failure

### ISSUE THREAD

**Issue by dongluochen** [docker/classicswarm#2517]
`docker/engine-api` is deprecated by Docker. Swarm still using engine-api may have inconsistency with Docker API. In test/integration/api/network.bats. Docker netork inspect has an extra field `Attachable` which causes test failure. 

```
   >         "Attachable": false,
```

cc @nishanttotla.

**Comment by nishanttotla** [comment]
@dongluochen good point. Let's track the vendoring update in #2488, and target to get it done by the next release.
