### ISSUE TITLE
unable to setup discovery backend using guide

### ISSUE THREAD

**Issue by charliemaiors** [docker/classicswarm#2529]
Hi all,

I'm following this [guide](https://docs.docker.com/swarm/install-manual/) and I'm unable to run the discovery backend on raspberry  pi cluster (raspberry  pi 3, latest raspbian, docker 1.12.2) when I've tried to run consul docker image daemon returned this error
`docker: Error response from daemon: failed to create endpoint consul on network bridge: failed to add the host (vethcc00fdc) <=> sandbox (veth5738546) pair interfaces: operation not supported.`
I've used `progrium/consul` image and `hypriot/rpi-consul`.

**Comment by lidel** [comment]
Not sure if this is still relevant, but the error appeared for me after kernel upgrade.
Try to `reboot` your rpi, it fixed the issue for me.
