### ISSUE TITLE
Running a container from a private registry doesn't work

### ISSUE THREAD

**Issue by tbouvet** [docker/classicswarm#2552]
> docker -v
```
Docker version 1.12.3, build 6b644ec
```
>  docker exec -it swarm-agent-master /swarm -v
```
swarm version 1.2.5 (27968ed)
```
> docker-compose -v
```
docker-compose version 1.9.0, build 2585387
```

With this configuration I can't run a container from a private registry if I don't do a pull before.
I have the same problem with or without docker-compose.

I saw https://github.com/docker/swarm/issues/2325 https://github.com/docker/swarm/issues/2217  but it's nok for me.

Do you have any idea please ?

**Comment by mschirrmeister** [comment]
Do you have the `HttpHeaders` setting in your `~/.docker/config.json` file?. You need to add the following to the config from where you run your `docker run` commands.
```json
"HttpHeaders": {
		"X-Registry-Auth": "xxx"
	}
```
A full config looks something like this.
```json
{
	"auths": {
		"dockerregistry.company.com": {
			"auth": "xxx"
		}
	},
	"HttpHeaders": {
		"X-Registry-Auth": "xxx"
	}
}
```
You can generate `X-Registry-Auth` with the following command.
```
echo "{\"username\":\"MyUsername\",\"password\":\"MyPassword\"}" | base64 -w 0
```

**Comment by tbouvet** [comment]
Yes I have tested with this configuration but the problem is I have more than one registry. So when I use the registry connected with the `X-Registry-Auth ` it's ok but if I need to pull image from another registry I have a `403 error`.
The problem is this parameter `X-Registry-Auth` is a general parameter. In my case, I need one parameter by one auth.
Other information I am in a swarm environment.

**Comment by tbouvet** [comment]
Any news about this please ?

**Comment by dongluochen** [comment]
@tbouvet I think `~/.docker/config.json` supports multiple registries. You need to login to each registry with `docker login`. Then docker should be able to use the authentication records to pull from the registries.

**Comment by tbouvet** [comment]
Yes I'm ok for  `~/.docker/config.json`  but ` X-Registry-Auth ` only supports **one** username/password. And `docker-composer` use this parameter. 
So my workaround is to do a `docker-compose pull` before a `docker-compose run`. It's not very good and the problem is if you have a swarm environment, you pull each image on each node !

**Comment by shin-** [comment]
It should work. Each pull is done independently with the matching registry credentials.

@tbouvet What command are you running, and what error are you seeing from compose?

**Comment by tbouvet** [comment]
@shin- I'm using `docker-compose up` in a swarm environment.
But in my compose file, I have different images on different repositories.
If I run a `docker-compose up`, I have an error 'no image found'. But If I run `docker-compose pull` and then `docker-compose up`, it's ok.
