### ISSUE TITLE
Support using multiple ---volume-drivers on swarm

### ISSUE THREAD

**Issue by suryagaddipati** [docker/classicswarm#2571]
Hi, I am opening [this docker issue ](https://github.com/docker/docker/issues/27302) here since it is supported in swarm mode but not in swarm classic.

**Comment by allencloud** [comment]
Thanks @suryagaddipati  I am closing this one.

**Comment by suryagaddipati** [comment]
@allencloud why was this closed? Is this currently supported in swarm classic?

**Comment by allencloud** [comment]
Oh, where is my coffee?
I think it is my bad to close this. Sorry for that.

**Comment by suryagaddipati** [comment]
@allencloud could you reopen this issue .

**Comment by allencloud** [comment]
Yes, of source.
