### ISSUE TITLE
How should i access container output out side of swarm cluster ?

### ISSUE THREAD

**Issue by akhildangore** [docker/classicswarm#2611]
Hello Team,

I want to access to my container output outside of swarm cluster...

I have three nodes swarm cluster:
1. node 1 (192.168.55.1)
2. node 2 (192.168.55.2)
3. node 3 (192.168.55.3)

And I have one more node called management 192.168.55.12(**it is not part of swarm cluster**).

I am able to access my container output : 192.168.55.1:9000, 192.168.55.2:9000, 192.168.55.3:9000  from node1, 2 , 3.

Problem:
1. I am unable to access my container output from management node (192.168.55.12).
2. Ping from 192.168.55.12 to node 1, 2, 3 is working.
3. I was expecting curl or browser 192.168.55.1:9000 should work from management node (192.168.55.12).

Please guide me.

**Comment by akhildangore** [comment]
Please help!!

**Comment by dongluochen** [comment]
Several questions: 
1. How do you set up your cluster? Is there firewall rule set up? 
2. How do you create your containers?
