### ISSUE TITLE
Docker IPs mapped in the swarm manager are not matching with the actual docker IP [stale entries in swarm manager]

### ISSUE THREAD

**Issue by ppadashe** [docker/classicswarm#2645]
We have docker swarm setup on a akka http cluster for our service,  we had an incident today where we found that, docker swarm manager IP meta had stale entries.   How do we remove the stale IP entries from the swarm manager metadata?  Is this a known issue?

Swarm Manager level:   1.2.5

**Comment by dongluochen** [comment]
@ppadashe Can you elaborate your problem with command/outputs?
