### ISSUE TITLE
Sometimes Swarm returns error Exec not found

### ISSUE THREAD

**Issue by garagatyi** [docker/classicswarm#2664]
We use Swarm in [Codenvy](https://github.com/codenvy/codenvy) system built on top of [Eclipse Che](github.com/eclipse/che).
And we use Swarm instead of Docker to scale infrastructure.
We use docker execs to launch additional software in container.
But sometimes Swarm responds with message like:
`Exec b98fb0f4a66de8046125e262ca520f7f6af68783440ac0032cf4baf095626779 not found`
It happens when we try to start created exec.
It happens both under high and low load. Even on devs machines.
But I don't know how to reproduce it. It just happens from time to time.

I see [here](https://github.com/docker/swarm/blob/master/api/handlers.go#L965) that exec ID should be set but Swarm returns error [here](https://github.com/docker/swarm/blob/master/api/utils.go#L77)

This issue fixes codenvy/codenvy#1734

**Comment by dongluochen** [comment]
@garagatyi When this happens, do you find any useful debug info from logs? Can you describe the sequence of your API calls?

**Comment by dongluochen** [comment]
In your dev environment, can you add `GET /exec/{id}/json` to see if the exec ID is properly added? https://docs.docker.com/engine/api/v1.28/#operation/ExecInspect.

**Comment by garagatyi** [comment]
I did add this call recently, but haven't investigated what it shows when erro appears. I can't provide logs details right now. I'll try to provide more details ASAP, but it'll probably take some time since I'm on sick leave.

**Comment by garagatyi** [comment]
@dongluochen I haven't found anything useful in swarm logs. But we use default log level - info. Do you think we can find anything useful in debug log level logs?

Sequence of calls is:
1. Build image
1. Create container
1. Start container 
1. Connect to containers logs
1. Inspect container
1. Create exec 1
1. Start exec 1
1. Create exec 2
1. Start exec 2
....

And it is possible that this sequence is executed concurrently in some amount of threads. Though it may happen when there is a lot of threads executing this sequence I met the problem even when 1 or 2 threads are executed.
Also there are some API calls that happen in background of the system, like get containers list, get images list, get network list, remove container, remove image, remove network, listen events.

From what I can say now `GET /exec/{id}/json` when exec start fails returns non 200 code too.
We are going to add more logs and inspections in our code such as inspect container where this happened. If you have any advice on what we can log in addition please let me know.

**Comment by dongluochen** [comment]
I don't find extra logs around https://github.com/docker/swarm/blob/master/api/utils.go#L77 so I'm not sure if debug log level would help. 

I think the exec inspects would help clarify the problem.

**Comment by garagatyi** [comment]
Hi there. Here what I found recently from inspections added into the code.
When this situation occurs `docker exec inspect <target exec id>` fails. But `docker inspect <exec container id>` succeeds and response does contain `<target exec id>` in the list of execs!
So this is quite weird.

If you have any ideas what can lead to this situation, please, let me know. Or if you need any additional information or additional inspections.

**Comment by garagatyi** [comment]
In addition to that I suspended our java code that performs all the docker API calls when the error appeared and tried to call docker API with curl. And results are the same - exec inspect returns 404, but container inspect contains that exec ID. And the problem persists, so even when I do inspect after several minutes after facing this problem it still present. So Swarm lost these data somehow, not just delayed receiving of it. Probably some race condition, I didn't manage to spot it in Swarm code.

**Comment by dongluochen** [comment]
The exec ID is added to manager at 
https://github.com/docker/swarm/blob/master/api/handlers.go#L931. Are you using multi-manager set up? Does this happen after primary switch? I'm wondering if the new primary would collect all exec IDs.

**Comment by garagatyi** [comment]
> Are you using multi-manager set up? 

No, we don't. Just single swarm manager.

> The exec ID is added to manager at https://github.com/docker/swarm/blob/master/api/handlers.go#L931

As far as I can see it is not protected from race condition. Am I mistaken? I'm not sure that we have concurrent execs creation, but it is what comes to me when I investigate Swarm code.

**Comment by dongluochen** [comment]
I think this is a race condition. Do you build from source? You can add a log at handlers.go#L931 to log every execID. If it's not found later, it means a race happened that execID was not added. 

```
log.Infof("execID %s added to container %s", execCreateResp.ID, container.Info.ID)
```

If you can confirm this, we can add data protection for this slice.

**Comment by dongluochen** [comment]
@garagatyi Can you test the #2702 to see if it fixes this issue?

**Comment by garagatyi** [comment]
@dongluochen Thank you! I'll try it in couple of days

**Comment by dongluochen** [comment]
@garagatyi It turns out docker exec is designed for single usage. Docker daemon would remove any execID that has exited. 
https://github.com/moby/moby/blob/master/daemon/exec.go#L267

You shouldn't save an `execID` and restart it. The correct usage pattern is to create and use every time.

**Comment by garagatyi** [comment]
It hasn't existed because it was never started. On first exec start, I get a not found error. Then I try to wait and start it again. So it wasn't collected by exec GC. 

We tried to trace down the problem. We used your PR as a base, then modified it in such a way:
<details>

```
diff --git a/api/handlers.go b/api/handlers.go
index 735a59b..e40076f 100644
--- a/api/handlers.go
+++ b/api/handlers.go
@@ -939,11 +939,11 @@ func postContainersExec(c *context, w http.ResponseWriter, r *http.Request) {
        }

        // add execID to the container, so the later exec/start will work
-       container.Lock()
+//     container.Lock()
        container.Info.ExecIDs = append(container.Info.ExecIDs, execCreateResp.ID)
-       container.Unlock()
+//     container.Unlock()
        // for temporary debugging, don't merge into code, at least not at Infof level
-       log.Infof("exec id %s is added to container %s", execCreateResp.ID, container.ID)
+       log.Infof("TRACING exec id %s is added to container %s", execCreateResp.ID, container.ID)

        w.Header().Set("Content-Type", "application/json")
        w.WriteHeader(http.StatusCreated)
diff --git a/api/utils.go b/api/utils.go
index b5ba474..88dd3a7 100644
--- a/api/utils.go
+++ b/api/utils.go
@@ -58,17 +58,18 @@ func getContainerFromVars(c *context, vars map[string]string) (string, *cluster.

        if ID, ok := vars["execid"]; ok {
                for _, container := range c.cluster.Containers() {
-                       container.RLock()
+//                     container.RLock()
                        for _, execID := range container.Info.ExecIDs {
                                if ID == execID {
-                                       container.RUnlock()
+//                                     container.RUnlock()
                                        // debug info. do not merge this into master branch
-                                       log.Infof("execid %s found on container %s", ID, container.ID)
+                                       log.Infof("TRACING execid %s found on container %s", ID, container.ID)
                                        return "", container, nil
                                }
                        }
-                       container.RUnlock()
+//                     container.RUnlock()
                }
+               log.Infof("TRACING execid %s NOT found on containers", ID)
                return "", nil, fmt.Errorf("Exec %s not found", ID)
        }
```
</details>
We commented locks to ses tracing when the error  happen.
So far 3 days 2 servers where 2 instances of swarm handle their own clusters of dockers. 
We got 0 errors on the 1st server and 3 errors on the 2nd.
Here is an example of the log in such situation:
<details>

```
[root@nightly-onprem swarm]# grep -C 5 "NOT found" swarm.log
time="2017-05-16T06:48:04Z" level=info msg="TRACING exec id a8e6b9a0e451413c1436df420cbedb5770baa22460cbdb6dd527e2adf3939f09 is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c" 
time="2017-05-16T06:48:04Z" level=info msg="TRACING exec id 90ae170a890ee749e1dd87c1d21012066ced584750e1eb3d271bb73930621f3b is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c" 
time="2017-05-16T06:48:04Z" level=info msg="TRACING execid a8e6b9a0e451413c1436df420cbedb5770baa22460cbdb6dd527e2adf3939f09 found on container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9a6f5
e490455c" 
time="2017-05-16T06:48:04Z" level=info msg="TRACING execid 90ae170a890ee749e1dd87c1d21012066ced584750e1eb3d271bb73930621f3b found on container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9a6f5
e490455c" 
time="2017-05-16T06:48:05Z" level=info msg="TRACING exec id 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c" 
time="2017-05-16T06:48:05Z" level=info msg="TRACING execid 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 NOT found on containers" 
time="2017-05-16T06:48:05Z" level=error msg="HTTP error: Exec 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 not found" status=404 
time="2017-05-16T06:48:05Z" level=info msg="TRACING execid 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 NOT found on containers" 
time="2017-05-16T06:48:05Z" level=error msg="HTTP error: Exec 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 not found" status=404 
time="2017-05-16T06:48:08Z" level=info msg="TRACING execid 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 NOT found on containers" 
time="2017-05-16T06:48:08Z" level=error msg="HTTP error: Exec 4ded11d6af91ba2ee2566ee8ad2e6431d7c476487e470e2e2ea877c9d32c3b63 not found" status=404 
time="2017-05-16T06:48:08Z" level=info msg="TRACING exec id 4b64de372f56e86dafde6c1134b4e23f9771f91bc80f491f01f1c6d34aab4610 is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c" 
time="2017-05-16T06:48:08Z" level=info msg="TRACING execid 4b64de372f56e86dafde6c1134b4e23f9771f91bc80f491f01f1c6d34aab4610 found on container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9a6f5
e490455c" 
time="2017-05-16T06:48:08Z" level=info msg="TRACING exec id 15e9afe9176e3d233557ac5cbc33a163ceb26a1fed077c089a492f53a0ada13e is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c" 
time="2017-05-16T06:48:08Z" level=info msg="TRACING exec id 9d6caf423ed36d0f467276131432ec146c1ed45e9b6fb354f05e3759f9b6e815 is added to container 98c48fb85e383c302d8d617312e0af3b8e5125fbbbb5627884a9
a6f5e490455c"
```
</details>
Now we are going to uncomment your locks to figureout whether it helps. But since we can't reliably reproduce the problem we would wait at least a week with a fix before assuming that it helps.

**Comment by garagatyi** [comment]
We tried those locks and it didn't help:
<details>

```
time=“2017-05-18T21:27:21Z” level=error msg=“HTTP error: No such image: eclipse-che/workspace7wa9pss7yjatlwv4_machine0so2c496czwnj8wt_user6nax_ws-machine” status=404
time=“2017-05-18T21:27:27Z” level=error msg=“HTTP error: No such image: eclipse-che/workspacenj2dxg9v1a7057cy_machinez604sjb8025vgkk3_user6nax_ws-machine” status=404
time=“2017-05-18T21:27:35Z” level=info msg=“TRACING LOCKS exec id e0c578f7f9af6f16260569f7d2d3c604707740115214eb49b2a41eacc96db935 is added to container 3df7de0478c13137b0932baa25dec557e3b336a89d0a200ef931b2b132bd6f4e”
time=“2017-05-18T21:27:35Z” level=info msg=“TRACING LOCKS execid e0c578f7f9af6f16260569f7d2d3c604707740115214eb49b2a41eacc96db935 found on container 3df7de0478c13137b0932baa25dec557e3b336a89d0a200ef931b2b132bd6f4e”
time=“2017-05-18T21:27:36Z” level=info msg=“TRACING LOCKS exec id f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f is added to container 3df7de0478c13137b0932baa25dec557e3b336a89d0a200ef931b2b132bd6f4e”
time=“2017-05-18T21:27:36Z” level=info msg=“TRACING LOCKS execid f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f NOT found on containers”
time=“2017-05-18T21:27:36Z” level=error msg=“HTTP error: Exec f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f not found” status=404
time=“2017-05-18T21:27:36Z” level=info msg=“TRACING LOCKS exec id fe146f8369f6473979c3a4d87901fa27de03a9a29178b33dbb68c46ef039121c is added to container 3df7de0478c13137b0932baa25dec557e3b336a89d0a200ef931b2b132bd6f4e”
time=“2017-05-18T21:27:36Z” level=info msg=“TRACING LOCKS execid fe146f8369f6473979c3a4d87901fa27de03a9a29178b33dbb68c46ef039121c found on container 3df7de0478c13137b0932baa25dec557e3b336a89d0a200ef931b2b132bd6f4e”
time=“2017-05-18T21:27:36Z” level=info msg=“TRACING LOCKS execid f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f NOT found on containers”
time=“2017-05-18T21:27:36Z” level=error msg=“HTTP error: Exec f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f not found” status=404
time=“2017-05-18T21:27:39Z” level=info msg=“TRACING LOCKS execid f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f NOT found on containers”
time=“2017-05-18T21:27:39Z” level=error msg=“HTTP error: Exec f3865081e750466a2393c58c2f8d0840f055313dde6a4c5da133451d3f821c2f not found” status=404
time=“2017-05-18T21:27:40Z” level=info msg=“TRACING LOCKS exec id 745f97326802ff6da852433e5b420e2e1f789e330f744c0837efb65a71bb5b0a is added to container d7d2ba3ccf27874492b28705657cea13d04725dcec70ae2f68ee2da217deac3a”
time=“2017-05-18T21:27:40Z” level=info msg=“TRACING LOCKS execid 745f97326802ff6da852433e5b420e2e1f789e330f744c0837efb65a71bb5b0a found on container d7d2ba3ccf27874492b28705657cea13d04725dcec70ae2f68ee2da217deac3a”
time=“2017-05-18T21:27:40Z” level=info msg=“TRACING LOCKS exec id 00dacb7fb94b6b6879ccba2f18ade306ba7bf16ed403597db7768f99a0c8d148 is added to container d7d2ba3ccf27874492b28705657cea13d04725dcec70ae2f68ee2da217deac3a”
time=“2017-05-18T21:27:40Z” level=info msg=“TRACING LOCKS execid 00dacb7fb94b6b6879ccba2f18ade306ba7bf16ed403597db7768f99a0c8d148 found on container d7d2ba3ccf27874492b28705657cea13d04725dcec70ae2f68ee2da217deac3a”
```
</details>

**Comment by dongluochen** [comment]
@garagatyi I think there might be 3 possibilities for `exec xxx not found`. The first one is the execIDs was garbage collected. You can add a debug log https://github.com/moby/moby/blob/master/daemon/exec.go#L276 to track the removal. 

The second one could be the container with a specific execID is missing in Swarm manager's cache. The following log should show the missing of the corresponding container.
https://github.com/docker/swarm/pull/2702/files#diff-81d7f76e438bada5617ba1e27943e05eL66

The 3rd possibility is execIDs inside `contianer.Info` was changed in container refresh or other operation, and for some reason, the execIDs are not properly set. I haven't found such a path.
