### ISSUE TITLE
docker run does not show any output

### ISSUE THREAD

**Issue by wsong** [docker/classicswarm#2673]
On master, `docker run` simply never shows any output:

```
$ docker run busybox echo hello
$
```

Compare this to running the same command against a standalone Docker engine:

```
$ docker run busybox echo hello
hello
$
```

This error appears to have been introduced by https://github.com/docker/swarm/pull/1463

**Comment by nishanttotla** [comment]
@wsong is this something you require? It would of course be ideal for the output to be as similar as possible to that of a standalone engine, but we just haven't built it in the past I guess.
