### ISSUE TITLE
Containers not reachable from one host to another

### ISSUE THREAD

**Issue by breakthewall** [docker/classicswarm#2687]
Hello,

I read related issues but none fit exactly with my problem.

I have 3 nodes integratred in a Swarm cluster with one manager. After creating an overlay network and launching containers as a service attached to this network, containers from one host are not able to reach containers that are running on the others hosts.

NOTE 1: `docker inspect <network>` only shows containers that are running on the current host.

NOTE 2: `ping` and `curl` work fine with containers IPs that are running on the current host.

Is there someone who has an idea?

Please find below usual informations:

```
root@docker-swarm-3:~# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
root@docker-swarm-3:~# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 61
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: jcpjbp5x7uxff4drjxgwg78w6
 Is Manager: true
 ClusterID: uegeaoike0nha4ic1wloidzsj
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.103
 Manager Addresses:
  192.168.0.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 9.787 GiB
Name: docker-swarm-3
ID: GWKU:AR4H:TSS2:C7VX:X4LT:MPNW:GMPY:4H26:7OAA:7QE6:7TIF:ZD5K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by breakthewall** [comment]
NOTE 3: containers are reachable from evrywhere if not put in a specific network, I can ping all containers IPs in the docker 172.17.0 subnet.

It still does not work within an overlay network.

Thank you for your help,
Joe

**Comment by Goram** [comment]
I have a similar problem, I have 2 stacks where one container from the first stack has the same overlay as 3 container in the second stack. The three in the second can ping each other just fine, but can´t reach the one in the other stack. This is a haproxy container which can´t start because it doesn´t reach the other 3:

[ALERT] 124/135641 (7) : parsing [/usr/local/etc/haproxy/haproxy.cfg:33] : 'server slave1' : could not resolve address 'slave1'.
[ALERT] 124/135641 (7) : parsing [/usr/local/etc/haproxy/haproxy.cfg:34] : 'server slave2' : could not resolve address 'slave2'.
[ALERT] 124/135641 (7) : parsing [/usr/local/etc/haproxy/haproxy.cfg:35] : 'server slave3' : could not resolve address 'slave3'.

I created the network in composer-stack and tried it in cmd with docker network create, same results.

**Comment by abarsov** [comment]
I have experienced the same or similar issue.

- 4 nodes in swarm cluster 
- overlay network
- docker-compose

Services started on different nodes could not talk to each other by service aliases.
At the same tome communication by internal IPs from overlay network subnet works fine.

It seems the issue was related to the node hostnames. 
I have cloned all nodes from the same VM template and hostname of one node was left the same as the hostname of swarm master. As soon as I excluded that node from cluster everything started working.

**Comment by TinyCamera** [comment]
I am also experiencing this issue. 

I followed this guide 
http://www.mchubarov.com/2017/02/running-selenium-grid-with-docker-in.html which describes how to use docker-compose to deploy a selenium grid stack.

Nodes running on the same machine as the hub are able to register. Nodes on different machines are not.
> 04:56:32.187 INFO - Couldn't register this node: The hub is down or not responding: hub: Name or service not known

**Comment by TinyCamera** [comment]
Is there a fix planned for this issue? I really want to use docker compose/docker swarm but this key feature is missing for quite some time.

**Comment by antoinetran** [comment]
Does ping resolve the name? This bug is happening all the time, or just randomly? Does a restart of docker daemon solve the issue?

**Comment by lyphtec** [comment]
I ran into a similar issue - but I've finally figured out my problem.

In my particular case, all my nodes are NOT on the same subnet.  They all have public IPs & reachable over the internet.  I followed the swarm setup guide in Docker docs - and opened all the required ports for all my nodes (2377/tcp; 7946/tcp; 7946/udp; & 4789/udp).  I setup the manager node and used the `--advertise-addr` option with the public IP of this node.  I then joined the worker nodes (using the output from `docker swarm join-token worker` on the manager node) & everything seemed to be working.  Deploying any stack with multiple replicas would correctly distribute to multiple nodes - however, the overlay network didn't work correctly as it was not talking to the containers on the other nodes - so there was no load balancing between nodes.

The fix for me was to make sure when I joined the worker nodes to the swarm to ALSO SPECIFY the `--advertise-addr` option using the public IP address of that node!  So all the nodes should be talking to each other over the public IP addresses!  If is option is not specified when a worker node joins the swarm, then it will register itself to the swarm using it's internal IP address and the overlay network will not route correctly!

This point is not clear both from the output of  `docker swarm join-token worker|manager` & also in the Docker guides and is deceiving in that stack deployment & node registration etc seemed to be working fine!

Hopefully this fixes the issue for some of you if your setup is the same as mine 😄

**Comment by antoinetran** [comment]
We always set advertise-addr for all managers and node, so this does not fix the issue for us. Except we set with a domain name. Maybe changing to IP will solve this...

**Comment by lyphtec** [comment]
@antoinetran - assuming you have a stack deployed with replicas spanning multiple nodes - doing: 

```
docker network inspect <overlay_network_name>
```

will show you the peering info between the nodes.  I think this is what the overlay network uses to route traffic between nodes.  Check that the info listed there is correct for your setup?

**Comment by antoinetran** [comment]
> @antoinetran - assuming you have a stack deployed with replicas spanning multiple nodes - doing:
> 
> docker network inspect <overlay_network_name>
> 
> will show you the peering info between the nodes. I think this is what the overlay network uses to route traffic between nodes. Check that the info listed there is correct for your setup?

Doing this will show me the network name, id, and all related endpoints, with their IPs in the configured subnet. This seems correct. However, I do not see the Swarm Node that you told me.

> [
>     {
>         "Name": "fac_internal_data",
>         "Id": "684d59e0da259258efab0733324b6240fc576fd936819c2b311b1514ebefa210",
>         "Created": "2017-07-10T09:27:23.198531111Z",
>         "Scope": "global",
>         "Driver": "overlay",
>         "EnableIPv6": false,
>         "IPAM": {
>             "Driver": "default",
>             "Options": null,
>             "Config": [
>                 {
>                     "Subnet": "192.168.214.0/24"
>                 }
>             ]
>         },
>         "Internal": false,
>         "Attachable": false,
>         "Containers": {
>             "144f577c472d3f1220fbd9f3dd2987124b31caf8535fcf080cef8a5861626d02": {
>                 "Name": "fac_elasticsearch_1",
>                 "EndpointID": "6b5d63b7164d828bf3aebae7e7ef2853ce5cd580c210bb37d5707279a32968f0",
>                 "MacAddress": "02:42:c0:a8:d6:20",
>                 "IPv4Address": "192.168.214.32/24",
>                 "IPv6Address": ""
>             },
> ...
>             "1db4ba0723fb1763bbd7248018432549f3877f85b412ea4d11dd168435b74102": {
>                 "Name": "ldapadmin",
>                 "EndpointID": "a09ef27fd9971cc4af536a8b22e37c27583dd5a9424b3424fc8d0611ede4c910",
>                 "MacAddress": "02:42:c0:a8:d6:14",
>                 "IPv4Address": "192.168.214.20/24",
>                 "IPv6Address": ""
>             },
>         },
>         "Options": {},
>         "Labels": {}
>     }
> ]

**Comment by lyphtec** [comment]
Are you running in swarm mode?  Your output appears much different than mine.  The scope for my overlay network is "swarm" not "global".  The "Peers" is what I'm talking about:

```
[
    {
        "Name": "webnet",
        "Id": "gjems29a3twwmmwpgjnjncbgx",
        "Created": "2017-08-24T09:48:42.066156228Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.3.0/24",
                    "Gateway": "10.0.3.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1b47ae54b1691961f7dcfdc374ac0967beb9075347862b070b4edff5739baa1a": {
                "Name": "viz_visualizer.u7l9v7sfvt7595h2o6tq7dn1b.bmk90w7stlv4j9b1d9es6j9zj",
                "EndpointID": "98bad7992039a22a68270a459659acece33dcf059b32f84d7f940d60f15c64ae",
                "MacAddress": "02:42:0a:00:03:09",
                "IPv4Address": "10.0.3.9/24",
                "IPv6Address": ""
            },
            "7ab0ae59e7bcbb60d5cf8db6edefe818eb6ca99e82ef02438882e5e8fcb28173": {
                "Name": "node-test_node-test.2.eu84wcqwlgkqeggd7c6ff1ix6",
                "EndpointID": "67a81c3b74c21467450d92aeb5a69ef38dd7655a962ba18ffac29d8e33c393c5",
                "MacAddress": "02:42:0a:00:03:05",
                "IPv4Address": "10.0.3.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "docker-node1-c31224d0f5c1",
                "IP": "x.x.x.x" (redacted)
            },
            {
                "Name": "docker-node3-2062cb20e598",
                "IP": "y.y.y.y"
            },
            {
                "Name": "docker-node4-af599b4f2ae0",
                "IP": "z.z.z.z"
            }
        ]
    }
]
```

My docker version:

```

Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by antoinetran** [comment]
> Are you running in swarm mode?
No, Swarm classic (1.2.6). This explains our difference. Can you do a:
`docker info`?
Mine gives entries like:
fl2p-s01.[domain]: fl2p-s01:2375
You should have IP.

**Comment by lyphtec** [comment]
No.  `docker info` in new mode doesn't show any details from other nodes:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: u7l9v7sfvt7595h2o6tq7dn1b
 Is Manager: true
 ClusterID: 51ziee044xpfcegkfpry5rx18
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: x.x.x.x
 Manager Addresses:
  x.x.x.x:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
...
```

**Comment by realcbb** [comment]
@ygokirmak I have the same problem with yours. When using docker stack deploy with overlay network, I can ping the service VIPs, but can never ping the container's real IP on different node.

Have you worked this out?  Can anyone give some help?

**Comment by jorisbertomeu** [comment]
I have the same issue guys :( 3 nodes on 3 different hosts, I can ping containers on the same host but can't ping other containers on a different host. On the same overlay network ..

> [
   {
      "Name": "SwarmNet",
      "Id": "jzafvaiku3czja7cqthjzxsdv",
      "Created": "2017-10-02T17:46:24.664000638+02:00",
      "Scope": "swarm",
      "Driver": "overlay",
      "EnableIPv6": false,
      "IPAM": {
         "Driver": "default",
         "Options": null,
         "Config": [
            {
               "Subnet": "10.1.9.0/24",
               "Gateway": "10.1.9.1"
            }
         ]
      },
      "Internal": false,
      "Attachable": false,
      "Ingress": false,
      "Containers": {
         "0718f22ba7f4c03d591ab7156879046c8e7a92e0db30e93b5699d3e54a214b3e": {
            "Name": "pdfbox-service-1.7.c5eimyw4qoz3ibvzfahbdrnwx",
            "EndpointID": "0d14fefbbe8155823c900861b02bbc3656ada02ca930eae4e7f69dfe6ecea161",
            "MacAddress": "02:42:0a:01:09:08",
            "IPv4Address": "10.1.9.8/24",
            "IPv6Address": ""
         },
         "3c0eb99bd6350f5808f55897b12e17045d32ae5ef4b2427122dd91a0e59faa40": {
            "Name": "pdfbox-service-1.17.6nclnsbtkaytxwobbdcub7ahn",
            "EndpointID": "a5528dcdd578c2ab17b3b880923a6f57819dffbc48a2bc225a0d72d7b338d881",
            "MacAddress": "02:42:0a:01:09:0b",
            "IPv4Address": "10.1.9.11/24",
            "IPv6Address": ""
         },
         "644006f5d6a6102b3f9ab6062e16a24a79dcd9a737f5d6334d4b714cf7ef306c": {
            "Name": "pdfbox-service-1.16.s2kicivaxeaaaw0hzeyk9q4dl",
            "EndpointID": "333c0e5db23a553aeef2f41f35691d86aa4751bbd13a408bbe72ca48defef023",
            "MacAddress": "02:42:0a:01:09:05",
            "IPv4Address": "10.1.9.5/24",
            "IPv6Address": ""
         },
         "7938112001a18b68941f1bd1691b724458e8082fcf273c0b2c7930ff2a245142": {
            "Name": "pdfbox-service-1.8.r7ogzke9r1a5to3yn5jqgzjfn",
            "EndpointID": "7b89da0beca3f8bcd538d95ca750ed47466b73545c0d00a6789b2c8947c5f543",
            "MacAddress": "02:42:0a:01:09:09",
            "IPv4Address": "10.1.9.9/24",
            "IPv6Address": ""
         },
         "9ac941511659194fe61cc7e9fa4643297322c52c8d7f1377af2e1cf5f09f6c11": {
            "Name": "pdfbox-service-1.15.kgnim54chdwascxa2b65nbfig",
            "EndpointID": "a2e74797163a77b7f4acdba092f433d651aa30a583e140e3418f24b06768e514",
            "MacAddress": "02:42:0a:01:09:0a",
            "IPv4Address": "10.1.9.10/24",
            "IPv6Address": ""
         },
         "e90b6e9a98c56a5f8463aa02b6d43d2bf445da49952e17582e7686cc647cae13": {
            "Name": "pdfbox-service-1.1.uuho4338silukbzt3d10d67x7",
            "EndpointID": "6c3c6375b1d0a8539d2d81fa4b196d0c87310c4fc5fa90054f22d47a73041cf1",
            "MacAddress": "02:42:0a:01:09:07",
            "IPv4Address": "10.1.9.7/24",
            "IPv6Address": ""
         },
         "ffe9d3a5eccf36293f18de83a544c6423a70707adea72526a4e11e120c718f27": {
            "Name": "pdfbox-service-1.13.twiw1uyah2mzx2w643ysgjlb8",
            "EndpointID": "d5e86d76d397af356ef1ccc3435a552bb5d3f458aa485b051b710199fc4b26ef",
            "MacAddress": "02:42:0a:01:09:12",
            "IPv4Address": "10.1.9.18/24",
            "IPv6Address": ""
         }
      },
      "Options": {
         "com.docker.network.driver.overlay.vxlanid_list": "4097"
      },
      "Labels": {},
      "Peers": [
         {
            "Name": "dockernode1-44f1565043a6",
            "IP": "10.10.2.52"
         },
         {
            "Name": "dockernode2-6516815a1184",
            "IP": "10.10.2.51"
         }
      ]
   }
]

**Comment by realcbb** [comment]
I have found that 4789 udp was blocked by some underlying network rules which cannot be controlled on my host machine. Hope this can help you.

**Comment by jorisbertomeu** [comment]
@realcbb firewall disabled on all my hosts :/

**Comment by bweston92** [comment]
Similar issue, I have a 5 node cluster, I have a swarm network using overlay driver. Everything has been working fine with services being able to talk to each other, until Docker restarted a container for being "unhealthy" and it restarted the container however no other container could communicate to it. I exec `sh` in the container and could call the endpoints fine, from another container I could only ping but it wouldn't do HTTP requests.
The only way I could fix was to scale down the container and scale it back up, any ideas on making sure this doesn't happen again?

**Comment by viniciusartur** [comment]
I had the same issue and the fix for me was the one pointed by @lyphtec, setting the --advertise-addr when joining the workers into the cluster.

**Comment by rammaram06** [comment]
I'm having similar issue, I tried above methods but no luck. Is there a proper fix for this? @thaJeztah 
It works sometimes and suddenly it stops working. I can ping other containers from but can't access them through http.

**Comment by akatiyar** [comment]
I had the container-connectivity issue in a standalone docker overlay network when containers were restarted.  No issues since I configured containers to have static IPs.  Issue - Overlay network IPAM logic was reusing IPs, however, failed to update host/container-ip mapping... resulted routes looking for containers on wrong hosts.

**Comment by albertorm95** [comment]
I'm having the same issue:

Swarm Cluster:
1 Manager, 4 Workers.

Only one of them have the issue, all ports seems to be open.

**Comment by FFng** [comment]
+1, 
finally, I figured out `4789/udp` is NOT available across nodes (in SDN network).
Reason:
The `4789/udp` of overlay network which Docker Swarm using by default is same with the `4789/udp` of VXLAN which some SDN may use it. 
This results in conflict or being blocked by cloud infrastructure provider ?

Solution:
Waiting for a new stable version after 2018-11-24 [moby: VXLAN UDP Port configuration support #38102](https://github.com/moby/moby/pull/38102)

Or,try this: [moby #33416](https://github.com/moby/moby/issues/33416#issuecomment-304427922)

**Comment by PhilipSchmid** [comment]
Hi there, 

I had the same problem on my setup with 3 nodes each with 1 internal and 1 external NIC. For me the correct configuration of `--advertise-addr` and `--data-path-addr` solved the problem (thanks to @lyphtec!):
```
# On the master:
docker swarm init --advertise-addr <internal-master-IP> --data-path-addr <external-master-IP> --default-addr-pool 10.254.0.0/15 --default-addr-pool-mask-length 27
# On the worker1:
docker swarm join --advertise-addr <internal-worker1-IP> --data-path-addr <external-worker1-IP> --token <swarm-worker-join-token> <internal-master-IP>:2377
# On the workerX:
docker swarm join --advertise-addr <internal-workerX-IP> --data-path-addr <external-workerX-IP> --token <swarm-worker-join-token> <internal-master-IP>:2377
```

It would be awesome if the official documentation (https://docs.docker.com/engine/reference/commandline/swarm_join/) would provide 2-3 examples of different node setups and their corresponding join statements... 

Regards,
Philip
