### ISSUE TITLE
Swarm and basic HTTP authentication

### ISSUE THREAD

**Issue by issam03** [docker/classicswarm#2729]
In my architecture, i have a gateway micro-service that implements an HTTP basic authentication (spring security). 

In local environement (stack deployed with a docker-compose), the HTTP authentication works when i send a GET/POST request to the gateway, the credential are accepted. Swarm is not used here.

But in preprod environement, the stack is deployed in swarm cluster and the gateway allways return "bad credential"

1. Is the authentication is made with swarm instead of my gateway image when the HTTP authentication is present in my request header ? 
2. Or does swarm does not forward the right header to the image 

Thank you for your ansers

**Comment by nishanttotla** [comment]
@issam03 can you provide more information about how you start the cluster and run the image?
