### ISSUE TITLE
Question: Roadmap, release-cycles and milestones?

### ISSUE THREAD

**Issue by schmunk42** [docker/classicswarm#2731]
This is not a bug-report but a general question.

When is the next release (1.2.7) planned? It has been 6 months since the last release, an eternity in Docker terms ;)

There are only a handful of issues marked for 1.2.7, see https://github.com/docker/swarm/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.2.7

But there are still plenty of issues open for 1.2.5, see
https://github.com/docker/swarm/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.2.5

Would be nice if docker/swarm could get shorter release cycles and if someone would update the issue-milestone planning.

**Comment by vincentwoo** [comment]
My assumption is that it is functionally on life support: https://github.com/docker/swarm/issues/2507

**Comment by nishanttotla** [comment]
@schmunk42 1.2.7 has been delayed due to some test failures and pending updates, but we want to release it soon (few days).

Since Swarm release cycles don't exactly match the new Docker release cycles, some Docker versions got released without a Swarm release. That said, we try to keep it stable and up to date with new features as much as possible.

If you have suggestions about what kind of milestones you'd like to see, feel free to share. It would also be useful if you pointed out areas that are of interest to you, to help with milestone planning.

**Comment by schmunk42** [comment]
@nishanttotla One thing I'd like to see is a `:experimental` image with the latest green build.

**Comment by nishanttotla** [comment]
@schmunk42 that is a good idea, I'll look into making that possible. Opened https://github.com/docker/swarm/issues/2737 to track that.

**Comment by nishanttotla** [comment]
Just released 1.2.7: https://github.com/docker/swarm/releases/tag/v1.2.7

Next release is supposed to be 1.3. The rough goals for that have been updated in the wiki.

**Comment by vincentwoo** [comment]
We're about half a year behind the wiki target for 1.3.0. Any word?

**Comment by nishanttotla** [comment]
@vincentwoo thanks for asking. While we haven't been doing active releases on Swarm classic, there have been bug fixes and other additions. This is also balanced out with a lot of the focus being on features for SwarmKit, based on community requirements.

I am looking forward to hearing if you are waiting on any specific points that we can address.

**Comment by vincentwoo** [comment]
Specifically, then:

1. Please do a point release with all the bug fixes from the last year or so. I download the binaries, so haven't been receiving these changes. Please document the changes as well.

2. Please clarify what your plans are for Swarm classic if the roadmap is now no longer realistic.

**Comment by nishanttotla** [comment]
@vincentwoo you can now download the 1.2.9 release that includes all fixes and updates since 1.2.8: https://github.com/docker/swarm/releases/tag/v1.2.9

**Comment by nishanttotla** [comment]
Plans for Swarm classic going forward are going to be updated soon.

**Comment by schmunk42** [comment]
@nishanttotla Please drop a note here, when the plan has been updated.

**Comment by bitsofinfo** [comment]
https://github.com/docker/swarmkit/issues/2665

**Comment by vincentwoo** [comment]
@nishanttotla was a roadmap update for swarm classic made? If so, where can I find it?

**Comment by nishanttotla** [comment]
@vincentwoo sorry for the late response, but I stepped down as maintainer of the project recently. You will have to contact the other maintainers for planning information. Thanks.
