### ISSUE TITLE
Create experimental image for Swarm

### ISSUE THREAD

**Issue by nishanttotla** [docker/classicswarm#2737]
Based on @schmunk42's suggestion, I think it would be a good idea to have an `:experimental` tagged build (nightly) for swarm that has the latest features in the master branch.

This would be particularly nice since the Swarm releases are now decoupled from the Docker Engine releases.

**Comment by schmunk42** [comment]
Even better: Add some tags like `1.2.8-alpha1`, `1.2.8-alpha2` from time to time. This would allow us this use an early version, but not taking the risk of getting unintended updates.

**Comment by nishanttotla** [comment]
@schmunk42 just FYI, I believe you can try new features with the `dockerswarm/swarm:master` image: https://hub.docker.com/r/dockerswarm/swarm/tags/

It might be sufficient to just add monthly or otherwise regular tags so that builds are triggered on that repo.

**Comment by schmunk42** [comment]
```
docker run dockerswarm/swarm --version
swarm version 1.2.8 (48d86b1)
```

@nishanttotla Looks not like the latest master
