### ISSUE TITLE
use docker swarm to manage all container create/delete/run cross all the hosts in swarm cluster

### ISSUE THREAD

**Issue by eshengit** [docker/classicswarm#2784]
I didn't see it possible or did i miss anything? 
What i want:  
1. create a docker swarm with host A and host B. With A as manager. 

```
 [A]# docker node ls  
ID                                             HOSTNAME              STATUS              AVAILABILITY        MANAGER STATUS   
4eklw9pb7997ehyxfxu7mtwt8 *   A                            Ready               Active              Leader   
c6y8r3sxnwk0ljmufwaxfln25         B                        Ready               Active   
```

2. We have multiple users 
In their local docker config, they config docker host as host A. 
so whatever the docker cmd they issue, the cmd fired against host A. 
they build docker images.   
they run docker containers.  
I expect
1. all those docker images can be shared in host A&B 
2. those docker containers are run  in either A or B 

Even the swarm does not support this now, is there any possible workaround?

**Comment by eshengit** [comment]
seems like standalone swarm is the solution?

**Comment by nishanttotla** [comment]
@eshengit can you clarify further what you mean? I'm not sure what your exact use case is.

**Comment by eshengit** [comment]
hi, @nishanttotla 
my use cases:   
a group of devs expect to talk to single $DOCKER_HOST:$DOCKER_PORT to start their own cluster of containers for testing. 
To them, there is only one docker host. they can use same docker cli(we actually use docker-java API) to manage container creation/removal.  
Underneath, its actually a swarm of docker hosts to do all the load balancing as to which container should be created in which docker host.
