### ISSUE TITLE
Inconsistent reference to license for docs

### ISSUE THREAD

**Issue by swinslow** [docker/classicswarm#2833]
Hello,

The README.md and LICENSE.docs files are inconsistent about which license applies to the swarm documentation.

The README.md file says that docs are:
"...licensed under the _Creative Commons Attribution 4.0 International License_ under the terms and conditions set forth in the file "**LICENSE.docs**". You may obtain a duplicate copy of the same license, titled **CC-BY-SA-4.0**, at _http://creativecommons.org/licenses/by/4.0/_."

The bolded items say that the docs license is CC-BY-SA-4.0 (and that's the text in the LICENSE.docs file), but the italicized items say that it is CC-BY-4.0 (which is a different license).

If the intent is for the docs license to be CC-BY-4.0, could the following changes be made?

1. The LICENSE.docs file should likely be replaced with the CC-BY-4.0 license text, available from https://creativecommons.org/licenses/by/4.0/legalcode.txt

2. The bolded reference above to **CC-BY-SA-4.0** in README.md should likely be changed to CC-BY-4.0.

Thank you!

**Comment by justincormack** [comment]
appears to have always meant to be cc-by-sa as far as I can tell, fixed readme in #2984

**Comment by swinslow** [comment]
that's great, thank you @justincormack!
