### ISSUE TITLE
"Docker run/start" exit with code 125 under load (container exit code is 0)

### ISSUE THREAD

**Issue by cfraenkel** [docker/classicswarm#2835]
When running lots of containers against docker swarm some ```docker run``` and ```docker start -a``` calls exit with code 125 while the container itself exits with code 0.

I've reproduced this Issue both against a multi node swarm with a consul backend and a new token based swarm created with docker-machine.

I've used the following shell script to reproduce this using the hello-world image:
```
#!/bin/bash -e
RUNFILE=`mktemp`

function runTest {
   THREADNO=$1
   while [ -e "${RUNFILE}" ] ; do
      CIDFILE=$(mktemp -u)
      docker run --cidfile ${CIDFILE} hello-world > /dev/null || (
         err=$?
         echo "Failure in Thread ${THREADNO}. Exit code : $err";
         CID=$(cat ${CIDFILE})
         docker inspect ${CID} > thread_${THREADNO}_inspect_${CID}.txt
         rm "${RUNFILE}"
         exit $err
      )
      CID=$(cat ${CIDFILE})
      docker rm -v ${CID}
      rm ${CIDFILE} 2>&1 > /dev/null || true

   done
}

for num in `seq 2 10`; do
  (runTest $num )&
done

runTest 1
```

This issue does not appear when running directly against the docker port.

<details><summary>docker info output</summary>

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: swarm/1.2.8
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 2
 (unknown): 192.168.99.101:2376
  └ ID:
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels:
  └ UpdatedAt: 2018-01-19T15:05:48Z
  └ ServerVersion:
 swarm-manager: 192.168.99.100:2376
  └ ID: EWQQ:VGZY:YGCQ:GMWV:R5VI:XDZA:ZCG6:RHDQ:MJQW:UWHD:RXC5:GIUA|192.168.99.100:2376
  └ Status: Healthy
  └ Containers: 2 (2 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: kernelversion=4.4.111-boot2docker, operatingsystem=Boot2Docker 18.01.0-ce (TCL 8.2.1); HEAD : 0bb7bbd - Thu Jan 11 16:32:39 UTC 2018, ostype=linux, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2018-01-19T15:05:48Z
  └ ServerVersion: 18.01.0-ce
Plugins:
 Volume:
 Network:
 Log:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Kernel Version: 4.4.111-boot2docker
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 1.021GiB
Name: 2c7fad8d8f61
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Experimental: false
Live Restore Enabled: false

WARNING: No kernel memory limit support
```
</details>

<details><summary>docker client version</summary>

```
$ docker -v
Docker version 17.10.0-ce, build f4ffd25
```
</details>

**Comment by arkuhn** [comment]
+1, I've been experiencing the same issue sporadically in a nearly identical environment.

**Comment by nishanttotla** [comment]
@cfraenkel does the container actually start? If it does, what does the inspect look like?

**Comment by cfraenkel** [comment]
The container starts and is listed on docker ps as exited (0). I've attached the inspect output for one of the containers that failed: [thread_2_inspect_49bf0d85a434f17d20baf86991bf4f98ff01808294dd96251bac6b6b501950dc.txt](https://github.com/docker/swarm/files/1914976/thread_2_inspect_49bf0d85a434f17d20baf86991bf4f98ff01808294dd96251bac6b6b501950dc.txt)
There's no interesting output in the logs of the agent or swarm. I've further attached the output of docker events from the docker host (not the swarm): 
[events.txt](https://github.com/docker/swarm/files/1914993/events.txt)
