### ISSUE TITLE
Docker swarm update accepts no arguments

### ISSUE THREAD

**Issue by MartinMajewski** [docker/classicswarm#2871]
I experience an odd behavior. Running

`docker swarm update --autolock false`

results in

```
"docker swarm update\" accepts no argument(s).
See 'docker swarm update --help'.

Usage:  docker swarm update [OPTIONS]

Update the swarm
```

However, running

`docker swarm update --autolock`

works. But where is the reason to run it without a true/false value?

I'm on Docker EE 17.06.2-ee-13

**Comment by dantuluri** [comment]
Also noticed this -- pretty odd behavior / syntax.

Well, seems like its time to get on board with k8s.
