### ISSUE TITLE
Installing ucp on a server with autolock enabled aks for key but fails

### ISSUE THREAD

**Issue by MartinMajewski** [docker/classicswarm#2872]
Related to 17.06.2-ee-13

Hi there,

I am trying to install ucp on an autolock enabled swarm and I am asked for setting the UNLOCK_KEY variable. What does this mean anyway? No documentation on this variable exists. Setting a Linux CLI variable does not help either.

Running the installation command with

`--unlock-key`

Results in 

```
INFO[0000] Your engine version 17.06.2-ee-13, build ac44d73 (3.10.0-862.3.2.el7.x86_64) is compatible with UCP 3.0.1 (2f7c7e1) 
Unlock Key: 
```

However, providing the key fails with the message

`FATA[0054] this swarm-mode cluster has an unlock key, which is required for UCP installation. Please set the UNLOCK_KEY environment variable``

Providing the key directly after `--unlock-key` does not change anything.

The key I provide is the current one, as checked with

`docker swarm unlock`

Please look also on issue https://github.com/docker/swarm/issues/2871 as I am not able do deactivate autolock anymore.

Best regards,
Martin

**Comment by lijinjayan** [comment]
Please try with  "docker swarm update --autolock=false" and try with ucp installation.
