### ISSUE TITLE
Help doesn't work with 1.2.9 (ff454b4a0e84) docker image

### ISSUE THREAD

**Issue by dpgeekzero** [docker/classicswarm#2877]
I get the same error running help for all commands, same behavior when using the option style, 'create --help'

>> docker run swarm help create
panic: template: help:18: unexpected EOF

goroutine 1 [running]:
panic(0xa66920, 0xc420013810)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
text/template.Must(0x0, 0xe6de00, 0xc420013810, 0x0)
	/usr/local/go/src/text/template/helper.go:23 +0x66
github.com/docker/swarm/vendor/github.com/urfave/cli.printHelp(0xe6f3c0, 0xc420028010, 0xc420366700, 0x32e, 0xb45420, 0xc4203702d0)
	/go/src/github.com/docker/swarm/vendor/github.com/urfave/cli/help.go:180 +0x1cc
github.com/docker/swarm/vendor/github.com/urfave/cli.ShowCommandHelp(0xc42036c240, 0x7fff7110ff7a, 0x6)
	/go/src/github.com/docker/swarm/vendor/github.com/urfave/cli/help.go:132 +0x348
github.com/docker/swarm/vendor/github.com/urfave/cli.glob..func1(0xc42036c240)
	/go/src/github.com/docker/swarm/vendor/github.com/urfave/cli/help.go:79 +0x52
github.com/docker/swarm/vendor/github.com/urfave/cli.Command.Run(0xb5e9e5, 0x4, 0x0, 0x0, 0xe8a3e0, 0x1, 0x1, 0xb7c8bc, 0x30, 0x0, ...)
	/go/src/github.com/docker/swarm/vendor/github.com/urfave/cli/command.go:137 +0xa8b
github.com/docker/swarm/vendor/github.com/urfave/cli.(*App).Run(0xc42036c000, 0xc42000a0f0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/swarm/vendor/github.com/urfave/cli/app.go:176 +0x919
github.com/docker/swarm/cli.Run()
	/go/src/github.com/docker/swarm/cli/cli.go:67 +0x446
main.main()
	/go/src/github.com/docker/swarm/main.go:13 +0x14

**Comment by dpgeekzero** [comment]
Why was this closed?  I just tried it today and it still doesn't work.  Is this project being shutdown?

**Comment by justincormack** [comment]
Hi, as per https://github.com/docker/roadmap/issues/86 we are planning to officially deprecate this project. No on has been working on it for some years now, and nor has there been any community input. The project was replaced by the integrated Swarm mode some years back, and this is what users have moved to in general.
