### ISSUE TITLE
dockersamples/examplevotingapp_worker is not working

### ISSUE THREAD

**Issue by sduggisetty** [docker/classicswarm#2887]
Hi,

dockersamples/examplevotingapp_worker image is not working.. It is given by docker INC itself, but still not working properly.

docker network create --driver overlay frontend
docker network create --driver overlay backend

docker service create --name worker --network frontend  --network backend dockersamples/examplevotingapp_worker

Error::
[root@ip-172-31-80-155 ~]# docker service ps ul0xpvoc0ysczom3jm7lmn8ul
ID                  NAME                IMAGE                                          NODE                DESIRED STATE       CURRENT STATE           ERROR                       PORTS
jep57xrjqqqm        worker.1            dockersamples/examplevotingapp_worker:latest   ip-172-31-80-155    Ready               Ready 3 seconds ago
4koc8mxx8rr9         \_ worker.1        dockersamples/examplevotingapp_worker:latest   ip-172-31-80-155    Shutdown            Failed 3 seconds ago    "task: non-zero exit (1)"
q24y20s8z0zu         \_ worker.1        dockersamples/examplevotingapp_worker:latest   ip-172-31-80-155    Shutdown            Failed 10 seconds ago   "task: non-zero exit (1)"
07yozz7ct3gq         \_ worker.1        dockersamples/examplevotingapp_worker:latest   ip-172-31-80-155    Shutdown            Failed 17 seconds ago   "task: non-zero exit (1)"

Every time i start, it is getting failed automatically by showing above error.

Kindly help.

**Comment by naveenmettu** [comment]
Thanks, @daveclement360 , it is magic.
