### ISSUE TITLE
Swarm cluster with single manager

### ISSUE THREAD

**Issue by umardraz** [docker/classicswarm#2895]
Hello

I am running Swarm cluster with one manager and two workers, right now running perfect for me :) Now how I can take the backup of my swarm manager. And restore the backup whenever I need.

**Comment by crwenner** [comment]
@umardraz Given that you are using a single manager in your cluster, this will cause downtime as the backup involves stopping the engine on one of the manager nodes. It is recommended you have _at least_ 3 managers to keep the quorum and prevent downtime.

[Link to Backup and Restore of a swarm cluster](https://success.docker.com/article/backup-restore-swarm-manager)
