### ISSUE TITLE
Proper way to remove unused images in swarm?

### ISSUE THREAD

**Issue by caub** [docker/classicswarm#2910]
Since `docker system prune` is 'unsafe' to use in swam context: an unused image can be used by a service in another swarm node, and thus needed if swarm decides to start the service on that node

What's a proper way to eliminate old unused docker images in Swarm?

**Comment by jony4** [comment]
docker image prune -a

**Comment by caub** [comment]
@jony4 that's not safe in a multi-node swarm cluster, because it prune local images, but local images might be unused but necessary for the swarm orchestrator

**Comment by jony4** [comment]
maybe do it one by one, simple 🤣

**Comment by caub** [comment]
@jony4 I don't think you understand the problem, swarm images are deployed on every swarm node, but they're not necessarly used on each node, pruning the image on node where it's not currently used will prevent a swarm service to run on that node
