### ISSUE TITLE
Docker Swarm ignores iptables=false 

### ISSUE THREAD

**Issue by mtippmann** [docker/classicswarm#2917]
Here is related Stackoverflow Issue: https://stackoverflow.com/q/48661114/772013

<quote>
I'm trying to setup a docker swarm, but I want to use ufw to create my own network rules. I've tried both putting --iptables=false in the docker service file, and also putting { "iptables": false } in /etc/docker/daemon.json.

However, whenever I deploy a service e.g.

docker service create -p 80:80 nginx:alpine
I still get the following output whenever I run

sudo iptables -L | grep -i docker

=>
696 39904 DOCKER-USER    all -- any   any  anywhere  anywhere
696 39904 DOCKER-INGRESS all -- any   any  anywhere  anywhere
Chain DOCKER-INGRESS (1 references)
Chain DOCKER-USER (1 references)
Docker version: 18.01.0-ce (installed with https://get.docker.com)

OS: Ubuntu 16.04

Is there anything i'm not seeing?
</quote> 

I can confirm the issue with the latest Docker Swarm Version (19.01-ce) and Debian 9 with ufw. iptables=false is ignored in Swarm mode but works *without* swarm mode.

**Comment by bockaerts** [comment]
I have the same problem.

**Comment by mtippmann** [comment]
@bockaerts the workaround seems to be to filter on the `DOCKER-USER` chain and use iptables instead of ufw - not exactly nice but at least it's a solution.

**Comment by hlj** [comment]
18.09.6-ce still have same problem.

**Comment by thiagomatar** [comment]
Hi guys, i've found an elegant way to fix this issue on chaifeng's github page:
https://github.com/chaifeng/ufw-docker
I hope this can helps you

**Comment by silviuvulcan** [comment]
Confirmed, docker swarm still ignores DOCKER_OPTS="--iptables=false"

**Comment by cenkalti** [comment]
In Ubuntu, I manage my own iptables rules. I don't want docker swarm to touch those. Because of this reason, I cannot use `docker stack deploy ...` command.

I wish docker swarm to respect `{"iptables": false}` setting defined in `/etc/docker/daemon.js`.

**Comment by cenkalti** [comment]
@justincormack Why is this closed?

**Comment by justincormack** [comment]
This is an issue for swarmkit https://github.com/docker/swarmkit not this repo, classic swarm, which is a much earlier version which we are deprecating. Unfortunately they confusingly share a name and many issues here are for the swarm mode/swarmkit/swarm that is built into Docker.
