### ISSUE TITLE
Not run docker swarm in startup

### ISSUE THREAD

**Issue by KooshkakiH** [docker/classicswarm#2921]
Hi, 
I have a docker swarm worker after joined to manger swarm and after reset my computer that has win server 2019(1809), docker service not run in startup and get below error in  event viewer:

The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Bulk sync to node 63ce8b856255 timed out

Information event:
The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

NetworkDB stats hyperv-test2(76badbe3f199) - netID:iy8xbxaba9lxliqvtk6tpcz6z leaving:false netPeers:2 entries:34 Queue qLen:0 netMsg/s:0

**Comment by justincormack** [comment]
This repo is for classic swarm, not swarmkit (swarm mode).
