### ISSUE TITLE
--enpoint-mode dnsrr service update failed due to port already use

### ISSUE THREAD

**Issue by paullaleu** [docker/classicswarm#2925]
Hi,
We are curently trying to use docker swarm to achieve this architecture : 

google cloud load balancer -> autoscaling group of VM compose of swarm worker node 

The docker we try to run is nginx listening on port 80
We do not want to use network mesh because we already have a load-balancer (gcloud lb) in front of our swarm.

Everything works but the problem is we cannot simply update our service because swarm is unable to pop our new version of docker because it uses the same port 80. 

if we keep the mesh system (--enpoint-mode vip) everything works but we have an unnecessary loadbalancing system (mesh network) inside our swarm that we do not want/need. 

I can't find how updating a service is possible (without downtime) with --enpoint-mode dnsrr ?

**Comment by justincormack** [comment]
This repo is for classic swarm, not swarmkit (swarm mode).
