### ISSUE TITLE
Docker service create not working as expected in docker 18.03 and above versions

### ISSUE THREAD

**Issue by preetammshetty** [docker/classicswarm#2927]
Hi,

I am from the Oracle Nosql Database Cloud development team. We use docker swarm to manage the docker containers for all the services deployed in the cloud.

In order to orchestrate the services, we issue a docker service command to the docker swarm manager which does the following:

Pulls the docker images for the given service in the worker node(s)
Create the docker containers running the service in the worker node(s)
Above used to work well until docker 17.52 release in OEL images. Recently we started using docker 18.03 and docker service create started giving issues. Specifically, the docker service create command is unable to pull the docker images in the worker node(s). It complains that the given image is not found.

We were able to find a workaround -> Explicitly go to each worker node and execute a docker pull image. Once the docker images were pulled on each worker node, if we execute the docker service create in the swarm manager, it is able to create the services in all the worker nodes.

However, we would like the initial behavior of docker swarm wherein a docker service create command would do both step (1) and step (2). Can you please check if:

This is a regression in 18.03 and above (OR)
This is an expected behavior in 18.03 and above
Regards,
Preetam

**Comment by justincormack** [comment]
This repo is for classic swarm not swarmkit.
