### ISSUE TITLE
How to use static IP in swarm

### ISSUE THREAD

**Issue by tutuerhao** [docker/classicswarm#2928]
How to use static IP in swarm?

**Comment by Dzhuneyt** [comment]
Please elaborate. The question is not really clear. Using static IPs in Docker Swarm doesn't require any special setup. In fact, having a static IP for all nodes, I think, is a rule for participating in Swarm mode.

**Comment by tutuerhao** [comment]
@Dzhuneyt How to allocate dynamic IP in overlay network

**Comment by tutuerhao** [comment]
@Dzhuneyt  How to allocate static IP in overlay network

**Comment by justincormack** [comment]
This repo is for classic swarm, not swarmkit (swarm mode).
