### ISSUE TITLE
Froce to remove docker network 

### ISSUE THREAD

**Issue by MikeChenfu** [docker/classicswarm#2934]
Hello,

I set up a Swarm and  generate several overlap networks. However, I am not able to remove these networks when this swarm was terminated. It always shows 

`Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
`
When I try to set up a swarm again by using "docker swarm init", it takes so long time  and get no response. I really appreciate if someone can give me any suggestions.

**Comment by jony4** [comment]
do again on your swarm manager node?

**Comment by justincormack** [comment]
This repo is for classic swarm, not swarmkit (swarm mode).
