### ISSUE TITLE
Error response from daemon: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.65.3:2377: connect: connection refused"

### ISSUE THREAD

**Issue by ghost** [docker/classicswarm#2952]
I have the manager started using Docker for Mac. I am trying to register a worker with the join command (using Docker for Windows), but I get:

`Error response from daemon: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.65.3:2377: connect: connection refused"`

Both versions of Docker are the same: 2.0.0.3

**Comment by srinivaskantetichintu** [comment]
https://linuxacademy.com/community/show/29612-docker-swarm-add-worker-node/

**Comment by justincormack** [comment]
This repo is for classic swarm, not swarmkit (swarm mode).
