### ISSUE TITLE
Please help me ....................................What is alternative method to get discover token for docker-machine swarm ?????

### ISSUE THREAD

**Issue by nethjai** [docker/classicswarm#2972]
When run the below command got the error ,
$ docker run swarm create

2020/02/04 17:54:04 Post https://discovery.hub.docker.com/v1/clusters: dial tcp: lookup discovery.hub.docker.com on 169.254.169.254:53: no such host

Is their any alternative method for creating discovery method to Discovery token for docker-machine swarm ???

Even in docker documentation they had mentioned token command , here my question is without getting the token, how we can create ????????????????????

docs link 
https://docs.docker.com/machine/reference/create/#specifying-docker-swarm-options-for-the-created-machine

**Comment by justincormack** [comment]
The classic swarm discovery service has been shut down. You can use static files, or etcd, but I recommend you use swarm mode in the Docker engine that replaced classic swaem instead.
