### ISSUE TITLE
Port redirection not working with docker swarm

### ISSUE THREAD

**Issue by ukreddy-erwin** [docker/classicswarm#2977]
docker service create --name postgres1 --publish 5432:5432 uday1kiran/postgres:9.6.10

working  but

docker service create --name postgres1 --publish 9000:5432 uday1kiran/postgres:9.6.10

not working.

Service is created but not able to connect to db.
database:postgres
user: postgres
password: postgres

creating an individual container working.

**Comment by justincormack** [comment]
This repo is not for Docker swarm you are looking for https://github.com/docker/swarmkit
