### ISSUE TITLE
Container / ContainerInfo refactoring

### ISSUE THREAD

**Issue by aluzzardi** [docker/classicswarm#736]
I'm wondering if having `Container` being a `dockerclient.Container` and `Container.Info` a `dockerclient.ContainerInfo` still makes sense.

Back then, the idea is that the two contained different informations. I believe however that now we have everything we need in `dockerclient.ContainerInfo` and no longer need the data in `dockerclient.Container` since we can generate it from the former.

We used to do an `inspect` to get the `ContainerInfo` only once and updated `Container` at every change, but now we got smarter in the way we do updates (filter on events), and also we **have** to update `ContainerInfo` to get some data we need anyway.

**Comment by amitshukla** [comment]
@aluzzardi is this question still relevant?

**Comment by abronan** [comment]
@amitshukla Yes, please do not close.
