### ISSUE TITLE
Docker API Proxy

### ISSUE THREAD

**Issue by ghost** [docker/classicswarm#990]
Current usage of Swarm requires modification of default daemon options or Systemd socket file to expose Docker's API over TCP. How about as an alternative, have Swarm be able to open a port that proxies to Docker's default Unix socket. Something like 

```
$ docker run -d --restart always --name swarm-agent -p 2376:2376 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/docker/tls:/etc/docker/tls swarm:latest ...
```

Thoughts?

**Comment by aluzzardi** [comment]
Sorry for the slow response - been busy at DockerCon.

We've been talking about this and I kinda like the idea.

A few thoughts:
- For backward compatibility, how about leaving `swarm join` as is (and deprecate it), and move this new stuff into a `swarm agent` sub-command?
- Security is a pain here. It becomes much easier to leave docker in the open (before you explicitly had to alter the docker settings and people were kinda aware of what they were doing). Perhaps we should have an easy way to generate TLS certs (similar to docker machine) and **require** TLS in `swarm agent`?

/cc @vieux @abronan @chanwit @jimmyxian

**Comment by nathanleclaire** [comment]
What would be the benefit of this approach?

**Comment by ehazlett** [comment]
It means we wouldn't have to expose the engine on TCP or worry about TLS
settings for it as well. It would also reduce the attack area as it's just
listening on the socket.
